/*
 * panelLogBook.java
 *
 * Created on July 25, 2001, 5:25 PM
 */

package ca.gc.space.quicksat.ground.client;
import javax.swing.*;
import java.io.*;
import java.util.*;
/**
 *
 * @author  jfcusson
 */
public class PanelLogBook extends javax.swing.JPanel {
String baseDir;
private boolean logbookChanged = false;

    /** Creates new form panelLogBook */
    public PanelLogBook( String baseDirToUse ) {
        baseDir = baseDirToUse;
        initComponents();
        /*---------------------------------------------*/
        /* Setup logbook selection radio buttons group */
        /* then load the selected log book             */
        /*---------------------------------------------*/
        ButtonGroup radiogroupLogbookSelection = new ButtonGroup();        
        radiogroupLogbookSelection.add( radLogbookActivities );
        radiogroupLogbookSelection.add( radLogbookTests );
        radiogroupLogbookSelection.add( radLogbookNotes );
        radLogbookActivities.setSelected( true );
        if( baseDir == null ) baseDir = "";
        try {
            FileReader fr = new FileReader( baseDir + "activities.txt" );
            txtLogbook.read( fr, null );
            fr.close();
            txtLogbook.setCaretPosition(txtLogbook.getText().length());
            txtLogbook.revalidate();
        } catch( IOException ioe ) { System.out.println("ERROR reading activity log:"+ioe); }
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
            panelLogbook = new javax.swing.JPanel();
            scrollLogbook = new javax.swing.JScrollPane();
            txtLogbook = new javax.swing.JTextArea();
            jPanel33 = new javax.swing.JPanel();
            lblLogbook = new javax.swing.JLabel();
            jPanel75 = new javax.swing.JPanel();
            radLogbookActivities = new javax.swing.JRadioButton();
            radLogbookTests = new javax.swing.JRadioButton();
            radLogbookNotes = new javax.swing.JRadioButton();
            jPanel76 = new javax.swing.JPanel();
            btnLogInsertDate = new javax.swing.JButton();
            btnLogSave = new javax.swing.JButton();
            
            setLayout(new java.awt.BorderLayout());
            
            panelLogbook.setLayout(new javax.swing.BoxLayout(panelLogbook, javax.swing.BoxLayout.X_AXIS));
            
            panelLogbook.setName("logbook");
            scrollLogbook.setPreferredSize(new java.awt.Dimension(500, 120));
            scrollLogbook.setAutoscrolls(true);
            txtLogbook.addFocusListener(new java.awt.event.FocusAdapter() {
                public void focusLost(java.awt.event.FocusEvent evt) {
                    txtLogbookFocusLost(evt);
                }
            });
            
            txtLogbook.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyTyped(java.awt.event.KeyEvent evt) {
                    txtLogbookKeyTyped(evt);
                }
            });
            
            scrollLogbook.setViewportView(txtLogbook);
            
            panelLogbook.add(scrollLogbook);
          
          jPanel33.setLayout(new javax.swing.BoxLayout(jPanel33, javax.swing.BoxLayout.Y_AXIS));
            
            jPanel33.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
            lblLogbook.setText("LOG BOOK");
            lblLogbook.setForeground(java.awt.Color.yellow);
            lblLogbook.setBackground(java.awt.Color.blue);
            lblLogbook.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            lblLogbook.setFont(new java.awt.Font("Arial Black", 0, 14));
            lblLogbook.setAlignmentX(0.5F);
            lblLogbook.setMaximumSize(new java.awt.Dimension(1500, 21));
            lblLogbook.setOpaque(true);
            jPanel33.add(lblLogbook);
            
            jPanel75.setLayout(new javax.swing.BoxLayout(jPanel75, javax.swing.BoxLayout.Y_AXIS));
              
              jPanel75.setBorder(new javax.swing.border.TitledBorder("Book Selection"));
              jPanel75.setEnabled(false);
              radLogbookActivities.setText("Activities");
              radLogbookActivities.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                      radLogbookActivitiesActionPerformed(evt);
                  }
              });
              
              jPanel75.add(radLogbookActivities);
              
              radLogbookTests.setText("Test Results");
              radLogbookTests.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                      radLogbookTestsActionPerformed(evt);
                  }
              });
              
              jPanel75.add(radLogbookTests);
              
              radLogbookNotes.setText("Notes");
              radLogbookNotes.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                      radLogbookNotesActionPerformed(evt);
                  }
              });
              
              jPanel75.add(radLogbookNotes);
              
              jPanel33.add(jPanel75);
            
            jPanel76.setBorder(new javax.swing.border.TitledBorder(""));
              btnLogInsertDate.setText("Insert Date");
              btnLogInsertDate.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                      btnLogInsertDateActionPerformed(evt);
                  }
              });
              
              jPanel76.add(btnLogInsertDate);
              
              btnLogSave.setText("Save");
              btnLogSave.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                      btnLogSaveActionPerformed(evt);
                  }
              });
              
              jPanel76.add(btnLogSave);
              
              jPanel33.add(jPanel76);
            
            panelLogbook.add(jPanel33);
          
          add(panelLogbook, java.awt.BorderLayout.CENTER);
        
    }//GEN-END:initComponents

    private void btnLogInsertDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInsertDateActionPerformed
    txtLogbook.append( "\n############################################ "+new Date().toLocaleString()+"\n" );
    txtLogbook.grabFocus();
    txtLogbook.revalidate();    
    }//GEN-LAST:event_btnLogInsertDateActionPerformed

    private void radLogbookNotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radLogbookNotesActionPerformed
      txtLogbook.setText("");  
      if( baseDir == null ) baseDir = "";
        try {
            FileReader fr = new FileReader( baseDir + "notes.txt" );
            txtLogbook.read( fr, null );
            fr.close();
            txtLogbook.setCaretPosition(txtLogbook.getText().length());
        } catch( IOException ioe ) { System.out.println("ERROR reading notes log:"+ioe); }
        txtLogbook.grabFocus();
        txtLogbook.revalidate();
    }//GEN-LAST:event_radLogbookNotesActionPerformed

    private void radLogbookActivitiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radLogbookActivitiesActionPerformed
      txtLogbook.setText("");  
      if( baseDir == null ) baseDir = "";
        try {
            FileReader fr = new FileReader( baseDir + "activities.txt" );
            txtLogbook.read( fr, null );
            fr.close();
            txtLogbook.setCaretPosition(txtLogbook.getText().length());
        } catch( IOException ioe ) { System.out.println("ERROR reading activity log:"+ioe); }
        txtLogbook.grabFocus();
        txtLogbook.revalidate();
    }//GEN-LAST:event_radLogbookActivitiesActionPerformed

    private void radLogbookTestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radLogbookTestsActionPerformed
      txtLogbook.setText("");  
      if( baseDir == null ) baseDir = "";
        try {
            FileReader fr = new FileReader( baseDir + "tests.txt" );
            txtLogbook.read( fr, null );
            fr.close();
            txtLogbook.setCaretPosition(txtLogbook.getText().length());
        } catch( IOException ioe ) { System.out.println("ERROR reading tests log:"+ioe); }
        txtLogbook.grabFocus();
        txtLogbook.revalidate();        
    }//GEN-LAST:event_radLogbookTestsActionPerformed

    private void btnLogSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogSaveActionPerformed
String filename = null;

      if( baseDir == null ) baseDir = "";  
      if( radLogbookActivities.isSelected() )
              filename = baseDir.trim()+"activities.txt";
      else if( radLogbookTests.isSelected() )
              filename = baseDir.trim()+"tests.txt";
      else
              filename = baseDir.trim()+"notes.txt";

      try{
          FileWriter fw = new FileWriter( filename);
          fw.write( txtLogbook.getText() );
          fw.close();
          System.out.println("File "+filename+" saved");
          logbookChanged = false;
      } catch( IOException ioe ) {}
    }//GEN-LAST:event_btnLogSaveActionPerformed

    private void txtLogbookKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLogbookKeyTyped
        logbookChanged = true;
    }//GEN-LAST:event_txtLogbookKeyTyped

    private void txtLogbookFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLogbookFocusLost
String filename = null;

      if( baseDir == null ) baseDir = "";
      if( logbookChanged ) {
            if( radLogbookActivities.isSelected() )
              filename = baseDir.trim()+"activities.txt";
            else if( radLogbookTests.isSelected() )
              filename = baseDir.trim()+"tests.txt";
            else
              filename = baseDir.trim()+"notes.txt";

            try{
                FileWriter fw = new FileWriter( filename);
                fw.write( txtLogbook.getText() );
                fw.close();
                System.out.println("File "+filename+" saved");
                logbookChanged = false;
            } catch( IOException ioe ) {}
      }
    }//GEN-LAST:event_txtLogbookFocusLost

    public void verifyTextChanged() {
        /*-----------------------------------------------*/
        /* Add an asterisk in logbook label if not saved */
        /*-----------------------------------------------*/
        if( logbookChanged )
            lblLogbook.setText( "LOG BOOK(*)" );
        else
            lblLogbook.setText( "LOG BOOK" );
    }        
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelLogbook;
    private javax.swing.JScrollPane scrollLogbook;
    public javax.swing.JTextArea txtLogbook;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JLabel lblLogbook;
    private javax.swing.JPanel jPanel75;
    private javax.swing.JRadioButton radLogbookActivities;
    private javax.swing.JRadioButton radLogbookTests;
    private javax.swing.JRadioButton radLogbookNotes;
    private javax.swing.JPanel jPanel76;
    private javax.swing.JButton btnLogInsertDate;
    private javax.swing.JButton btnLogSave;
    // End of variables declaration//GEN-END:variables

}
