/*
 * PanelSettings.java
 *
 * Created on July 23, 2001, 2:38 PM
 */

package ca.gc.space.quicksat.ground.client;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import java.io.*;

/**
 *
 * @author  jfcusson
 * @version 
 */
public class PanelSettings extends javax.swing.JPanel {
public jload mainProgram;
    
    /** Creates new form PanelSettings */
    public PanelSettings(jload initializer) {
        mainProgram = initializer;        
        initComponents ();
    }
    
    public String getGroundStationCallsign() {
        return( txtGsCallsign.getText().trim() );
    }

    public int getGroundStationSSID() {
        int val = 0;
        try{
            val = Integer.parseInt(txtGsSSID.getText().trim());
            if( (val<0) || (val>0x0F) )
                val = 0;
        } catch( NumberFormatException e ) {
            val = 0;
        }
        return( val );
    }
    
    public String getGroundStationAddress() {        
        return(getGroundStationCallsign()+"-"+getGroundStationSSID());
    }
    
    public int getUploadPacingTime() {
        return(Integer.parseInt(txtUploadPacingTime.getText()));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
            scrollSettings = new javax.swing.JScrollPane();
            panel2Settings = new javax.swing.JPanel();
            jPanel1 = new javax.swing.JPanel();
            jPanel3 = new javax.swing.JPanel();
            jPanel4 = new javax.swing.JPanel();
            jLabel1 = new javax.swing.JLabel();
            txtUploadPacingTime = new javax.swing.JTextField();
            jLabel3 = new javax.swing.JLabel();
            jPanel5 = new javax.swing.JPanel();
            jLabel4 = new javax.swing.JLabel();
            txtGsCallsign = new javax.swing.JTextField();
            jLabel5 = new javax.swing.JLabel();
            txtGsSSID = new javax.swing.JTextField();
            currTimeOffset = new javax.swing.JLabel();
            jButton1 = new javax.swing.JButton();
            serverAdd = new javax.swing.JTextField();
            currTime = new javax.swing.JLabel();
            status = new javax.swing.JLabel();
            lastUpdateTime = new javax.swing.JLabel();
            
            setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));
            
            panel2Settings.setBorder(new javax.swing.border.TitledBorder(new javax.swing.border.EtchedBorder(), "Settings"));
            panel2Settings.setPreferredSize(new java.awt.Dimension(800, 187));
            panel2Settings.setMaximumSize(new java.awt.Dimension(800, 32767));
            panel2Settings.add(jPanel1);
            
            jPanel3.setBorder(new javax.swing.border.TitledBorder("Extended Proto (upload task)"));
                jLabel1.setText("Pacing Delay:");
                jPanel4.add(jLabel1);
                
                txtUploadPacingTime.setText("625");
                txtUploadPacingTime.setPreferredSize(new java.awt.Dimension(50, 21));
                jPanel4.add(txtUploadPacingTime);
                
                jPanel3.add(jPanel4);
              
              jLabel3.setText("mSec");
              jPanel3.add(jLabel3);
              
              panel2Settings.add(jPanel3);
            
            jPanel5.setBorder(new javax.swing.border.TitledBorder("Ground Station Address"));
              jLabel4.setText("Callsign:");
              jPanel5.add(jLabel4);
              
              txtGsCallsign.setText("CSA");
              txtGsCallsign.setPreferredSize(new java.awt.Dimension(75, 21));
              jPanel5.add(txtGsCallsign);
              
              jLabel5.setText("SSID:");
              jPanel5.add(jLabel5);
              
              txtGsSSID.setText("0");
              txtGsSSID.setPreferredSize(new java.awt.Dimension(20, 21));
              jPanel5.add(txtGsSSID);
              
              panel2Settings.add(jPanel5);
            
            currTimeOffset.setPreferredSize(new java.awt.Dimension(10, 4));
            currTimeOffset.setMaximumSize(new java.awt.Dimension(16, 4));
            panel2Settings.add(currTimeOffset);
            
            jButton1.setText("Update application time");
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });
            
            panel2Settings.add(jButton1);
            
            serverAdd.setText("time.nrc.ca");
            panel2Settings.add(serverAdd);
            
            panel2Settings.add(currTime);
            
            status.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(1, 1, 1, 1)));
            panel2Settings.add(status);
            
            panel2Settings.add(lastUpdateTime);
            
            scrollSettings.setViewportView(panel2Settings);
          
          add(scrollSettings);
        
    }//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     try{
        ca.gc.space.quicksat.ground.Time.TimeCorrector tc = new ca.gc.space.quicksat.ground.Time.TimeCorrector();
       long toff = tc.getTimeOffset(this.serverAdd.getText());
      java.sql.Timestamp ts = new java.sql.Timestamp(System.currentTimeMillis());
       this.currTime.setText("On update computer clock was set to: "+ ts);
       this.currTimeOffset.setText("Offset is: "+Long.toString(toff) + " millis");
      
         mainProgram.timeOffset = toff;
         this.status.setText("Update successfull");
         this.status.setForeground(Color.green);
         mainProgram.lastSync = ts;
         this.lastUpdateTime.setText("Last succesfull update was "+ mainProgram.lastSync.toString());
     }
     catch(Exception e){
        this.currTimeOffset.setText(e.toString());
                this.status.setText("Update failed");
                this.status.setForeground(Color.red);
     }
     
       
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void radSSID2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radSSID2ActionPerformed
    }//GEN-LAST:event_radSSID2ActionPerformed

    private void radSSID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radSSID1ActionPerformed
    }//GEN-LAST:event_radSSID1ActionPerformed

    private void chkUseSCUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkUseSCUActionPerformed
    }//GEN-LAST:event_chkUseSCUActionPerformed

  private void radTNCSerialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radTNCSerialActionPerformed
  }//GEN-LAST:event_radTNCSerialActionPerformed

  private void radSCUSerialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radSCUSerialActionPerformed
  }//GEN-LAST:event_radSCUSerialActionPerformed

  private void radNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radNetworkActionPerformed
  }//GEN-LAST:event_radNetworkActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JScrollPane scrollSettings;
  private javax.swing.JPanel panel2Settings;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JTextField txtUploadPacingTime;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JPanel jPanel5;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JTextField txtGsCallsign;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JTextField txtGsSSID;
  private javax.swing.JLabel currTimeOffset;
  private javax.swing.JButton jButton1;
  private javax.swing.JTextField serverAdd;
  private javax.swing.JLabel currTime;
  private javax.swing.JLabel status;
  private javax.swing.JLabel lastUpdateTime;
  // End of variables declaration//GEN-END:variables

}
