/*
 * panelPACSAT.java
 *
 * Created on July 25, 2001, 5:17 PM
 */

package ca.gc.space.quicksat.ground.pacsat;

import ca.gc.space.quicksat.ground.client.*;
import ca.gc.space.quicksat.ground.satellite.*;
import ca.gc.space.quicksat.ground.control.*;
import ca.gc.space.quicksat.ground.util.*;

/**
 *
 * @author  jfcusson
 */
public class PanelPACSAT extends javax.swing.JPanel {
public jload mainProgram;
ServerLink  srvLnk               = null;
Satellite   sat                  = null;
Log         log                  = null;
   

    /** Creates new form panelPACSAT */
    public PanelPACSAT(jload initializer, Log log) {
        mainProgram = initializer;
        initComponents();
        this.log = log;                
        if( this.log == null ) this.log = new Log();
    }
    /*========================================================================*/    
    /** Set the object that is in charge of managing the link with the ground
     *  station server.
     *  @param srvLnk ServerLink used to communicate with the server.     */
    /*========================================================================*/
    public void setServerLink( ServerLink srvLnk ) {
    /*========================================================================*/    
        this.srvLnk = srvLnk;
    }
    
    /*========================================================================*/
    /** Set the object representing the satellite that we want to communicate
     *  with, and understanding the format of the commands.
     *  @param sat Satellite object representing our satellite.               */
    /*========================================================================*/
    public void setSatellite( Satellite sat ) {
    /*========================================================================*/    
        this.sat = sat;
    }

    
    public void setPacsatAddress( String callsign, int ssid ) {
        txtBBSCallsign.setText( callsign );
        txtBBSSSID.setText( ""+ssid );
    }
    
    public void println( String message ) {
        txtInfo.append(message+"\n");
        txtInfo.setCaretPosition(txtInfo.getText().length());
        txtInfo.revalidate();        
    }
    public void print( String message ) {
        txtInfo.append(message);
        txtInfo.setCaretPosition(txtInfo.getText().length());
        txtInfo.revalidate();        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
              panelPACSAT = new javax.swing.JPanel();
              jPanel103 = new javax.swing.JPanel();
              jPanel108 = new javax.swing.JPanel();
              jLabel47 = new javax.swing.JLabel();
              txtBCASTCallsign = new javax.swing.JTextField();
              jLabel48 = new javax.swing.JLabel();
              txtBCASTSSID = new javax.swing.JTextField();
              jPanel109 = new javax.swing.JPanel();
              jLabel49 = new javax.swing.JLabel();
              txtBBSCallsign = new javax.swing.JTextField();
              jLabel50 = new javax.swing.JLabel();
              txtBBSSSID = new javax.swing.JTextField();
              jPanel1 = new javax.swing.JPanel();
              jButton2 = new javax.swing.JButton();
              btnConnect = new javax.swing.JButton();
              btnDisconnect = new javax.swing.JButton();
              jPanel105 = new javax.swing.JPanel();
              jPanel106 = new javax.swing.JPanel();
              jScrollPane1 = new javax.swing.JScrollPane();
              txtInfo = new javax.swing.JTextArea();
              jPanel107 = new javax.swing.JPanel();
              btnGetFileList = new javax.swing.JButton();
              jButton3 = new javax.swing.JButton();
              jButton1 = new javax.swing.JButton();
              
              setLayout(new java.awt.BorderLayout());
              
              panelPACSAT.setLayout(new javax.swing.BoxLayout(panelPACSAT, javax.swing.BoxLayout.Y_AXIS));
              
              jPanel103.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));
              
              jPanel103.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
              jPanel108.setBorder(new javax.swing.border.TitledBorder("Broadcast"));
              jLabel47.setText("Callsign:");
              jPanel108.add(jLabel47);
              
              txtBCASTCallsign.setText("QIKSAT");
              txtBCASTCallsign.setPreferredSize(new java.awt.Dimension(70, 20));
              jPanel108.add(txtBCASTCallsign);
              
              jLabel48.setText("SSID:");
              jPanel108.add(jLabel48);
              
              txtBCASTSSID.setText("11");
              txtBCASTSSID.setPreferredSize(new java.awt.Dimension(25, 20));
              jPanel108.add(txtBCASTSSID);
              
              jPanel103.add(jPanel108);
            
            jPanel109.setBorder(new javax.swing.border.TitledBorder(new javax.swing.border.EtchedBorder(), "BBS"));
              jLabel49.setText("Callsign:");
              jPanel109.add(jLabel49);
              
              txtBBSCallsign.setText("QIKSAT");
              txtBBSCallsign.setPreferredSize(new java.awt.Dimension(70, 20));
              jPanel109.add(txtBBSCallsign);
              
              jLabel50.setText("SSID:");
              jPanel109.add(jLabel50);
              
              txtBBSSSID.setText("12");
              txtBBSSSID.setPreferredSize(new java.awt.Dimension(25, 20));
              jPanel109.add(txtBBSSSID);
              
              jPanel103.add(jPanel109);
            
            jPanel1.setBorder(new javax.swing.border.TitledBorder("Uplink"));
              jButton2.setText("Upload");
              jPanel1.add(jButton2);
              
              btnConnect.setText("Connect");
              btnConnect.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                      btnConnectActionPerformed(evt);
                  }
              });
              
              jPanel1.add(btnConnect);
              
              btnDisconnect.setText("Disconnect");
              btnDisconnect.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                      btnDisconnectActionPerformed(evt);
                  }
              });
              
              jPanel1.add(btnDisconnect);
              
              jPanel103.add(jPanel1);
            
            panelPACSAT.add(jPanel103);
          
          jPanel105.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                jPanel106.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                jScrollPane1.setPreferredSize(new java.awt.Dimension(500, 100));
                jScrollPane1.setViewportView(txtInfo);
                
                jPanel106.add(jScrollPane1);
              
              jPanel105.add(jPanel106);
            
            jPanel107.setLayout(new javax.swing.BoxLayout(jPanel107, javax.swing.BoxLayout.Y_AXIS));
              
              jPanel107.setBorder(new javax.swing.border.TitledBorder("Downlink"));
              btnGetFileList.setText("Get Short Dir");
              btnGetFileList.setMaximumSize(new java.awt.Dimension(1000, 27));
              btnGetFileList.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                      btnGetFileListActionPerformed(evt);
                  }
              });
              
              jPanel107.add(btnGetFileList);
              
              jButton3.setText("Get Long Dir");
              jButton3.setMaximumSize(new java.awt.Dimension(1000, 27));
              jPanel107.add(jButton3);
              
              jButton1.setText("Download");
              jButton1.setMaximumSize(new java.awt.Dimension(1000, 27));
              jPanel107.add(jButton1);
              
              jPanel105.add(jPanel107);
            
            panelPACSAT.add(jPanel105);
          
          add(panelPACSAT, java.awt.BorderLayout.CENTER);
        
    }//GEN-END:initComponents

    private void btnDisconnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisconnectActionPerformed
        mainProgram.pacsatDisconnect();
    }//GEN-LAST:event_btnDisconnectActionPerformed

    private void btnConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectActionPerformed
        mainProgram.pacsatConnect();
    }//GEN-LAST:event_btnConnectActionPerformed

    private void btnGetFileListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetFileListActionPerformed
        // Add your handling code here:
    }//GEN-LAST:event_btnGetFileListActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelPACSAT;
    private javax.swing.JPanel jPanel103;
    private javax.swing.JPanel jPanel108;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JTextField txtBCASTCallsign;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JTextField txtBCASTSSID;
    private javax.swing.JPanel jPanel109;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JTextField txtBBSCallsign;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JTextField txtBBSSSID;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton btnConnect;
    private javax.swing.JButton btnDisconnect;
    private javax.swing.JPanel jPanel105;
    private javax.swing.JPanel jPanel106;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtInfo;
    private javax.swing.JPanel jPanel107;
    private javax.swing.JButton btnGetFileList;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables

}
