/*
 * test.java
 *
 * Created on August 1, 2001, 9:53 AM
 */

package ca.gc.space.quicksat.ground.tracking;

import java.net.*;
import java.io.*;
import javax.swing.*;

/**
 *
 * @author  jfcusson
 */
public class DialogLoadKeps extends javax.swing.JDialog {
private boolean errorLoading = true;
private String baseDir = "";
    
    /** Creates new form test */
    public DialogLoadKeps(java.awt.Frame parent, String baseDirToUse) {        
        super(parent, true);
        baseDir = baseDirToUse;
        initComponents();
        listKepsSourceURL.addItem( "http://www.celestrak.com/NORAD/elements/amateur.txt" );
    }

    public void setBaseDir( String baseDirToUse ) {
        baseDir = baseDirToUse;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
          jPanel1 = new javax.swing.JPanel();
          jLabel2 = new javax.swing.JLabel();
          listKepsSourceURL = new javax.swing.JComboBox();
          jPanel3 = new javax.swing.JPanel();
          jScrollPane1 = new javax.swing.JScrollPane();
          txtPreview = new javax.swing.JTextArea();
          jPanel4 = new javax.swing.JPanel();
          prgrssLoad = new javax.swing.JProgressBar();
          jPanel2 = new javax.swing.JPanel();
          jButton3 = new javax.swing.JButton();
          jButton4 = new javax.swing.JButton();
          
          getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.Y_AXIS));
          
          setTitle("Download Latest Orbital Elemets");
          setName("dialogLoadKeps");
          setModal(true);
          addWindowListener(new java.awt.event.WindowAdapter() {
              public void windowClosing(java.awt.event.WindowEvent evt) {
                  closeDialog(evt);
              }
          });
          
          jPanel1.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
          jLabel2.setText("Source URL:");
          jPanel1.add(jLabel2);
          
          listKepsSourceURL.setEditable(true);
          listKepsSourceURL.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
                  listKepsSourceURLActionPerformed(evt);
              }
          });
          
          jPanel1.add(listKepsSourceURL);
          
          getContentPane().add(jPanel1);
            
            jPanel3.setBorder(new javax.swing.border.TitledBorder("Preview"));
            jScrollPane1.setPreferredSize(new java.awt.Dimension(650, 200));
            jScrollPane1.setViewportView(txtPreview);
            
            jPanel3.add(jScrollPane1);
          
          getContentPane().add(jPanel3);
          
          jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.X_AXIS));
          
          jPanel4.setBorder(new javax.swing.border.TitledBorder("Downloading Progress"));
          jPanel4.add(prgrssLoad);
          
          getContentPane().add(jPanel4);
          
          jPanel2.setBorder(new javax.swing.border.BevelBorder(javax.swing.border.BevelBorder.RAISED));
          jButton3.setText("Update Local Data");
          jButton3.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
                  jButton3ActionPerformed(evt);
              }
          });
          
          jPanel2.add(jButton3);
          
          jButton4.setText("Close");
          jButton4.addActionListener(new java.awt.event.ActionListener() {
              public void actionPerformed(java.awt.event.ActionEvent evt) {
                  jButton4ActionPerformed(evt);
              }
          });
          
          jPanel2.add(jButton4);
          
          getContentPane().add(jPanel2);
        
        pack();
    }//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        /* 0 = OK, 2 = CANCEL */
        int dRes = 0;
        if( errorLoading ) {
            dRes = JOptionPane.showConfirmDialog(this,
            "WARNING: There seems to be an error loading the file.\nVerify the preview area to see if you really want to replace the local file with this data.\nCONTINUE?",
            "Replace Local Data",
            JOptionPane.OK_CANCEL_OPTION );
        }
        if( dRes == 0 ) {
            try{
                FileOutputStream fo = null;
                fo = new FileOutputStream( baseDir + "qsgs_keps.txt");
                fo.write( txtPreview.getText().getBytes() );
                fo.close();
                JOptionPane.showMessageDialog( this, "Local File Updated" );
            } catch( IOException ioe ) {
                JOptionPane.showMessageDialog( this, "There was an error creating the local file: "+ioe );
            }
                
            
        } else {
            JOptionPane.showMessageDialog( this, "Operation Cancelled" );
        }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void listKepsSourceURLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listKepsSourceURLActionPerformed
        
        URL url = null;
        try {
            url = new URL((String)listKepsSourceURL.getSelectedItem());
        } catch( MalformedURLException mue ) {
            txtPreview.setText("Source URL invalid: "+mue);
            errorLoading = true;
            return;
        }
        try {
            DataInputStream di = null;
            
            URLConnection urlConnection = url.openConnection();
            urlConnection.connect();
            di = new DataInputStream(urlConnection.getInputStream());
            
            txtPreview.setText("");
            
            int fileSize = urlConnection.getContentLength();
            
            int loadedSoFar = 0;
            int bytesAvailable = 0;
            prgrssLoad.setValue( 0 );
            
            LOADING:
            while( true ) {
                bytesAvailable = di.available();
                //if( bytesAvailable <= 0 ) break LOADING;
                loadedSoFar += bytesAvailable;
                byte[] byteInput = new byte[bytesAvailable];
                int dRes = di.read( byteInput );
                if( dRes < 0 ) break LOADING;
                double ratio = (double)((double)loadedSoFar*100.0)/((double)fileSize*100.0);
                ratio = ratio * 100.0;
                
                prgrssLoad.setValue( (int)ratio );
                txtPreview.append( new String( byteInput ) );
            }
            di.close();
        } catch( IOException ioe ) {
            txtPreview.setText("Error reading source: "+ioe);
            errorLoading = true;
            return;            
        }
        errorLoading = false;
        return;
        
    }//GEN-LAST:event_listKepsSourceURLActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        new DialogLoadKeps(new javax.swing.JFrame(), "C:/jload/").show();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox listKepsSourceURL;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtPreview;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JProgressBar prgrssLoad;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    // End of variables declaration//GEN-END:variables

}
