/*
 * PanelHeaters.java
 *
 * Created on July 25, 2001, 3:21 PM
 */

package ca.gc.space.quicksat.ground.control;

import javax.swing.*;
import ca.gc.space.quicksat.ground.client.*;
import ca.gc.space.quicksat.ground.satellite.*;
import ca.gc.space.quicksat.ground.control.*;
import ca.gc.space.quicksat.ground.util.*;

/**
 *
 * @author  jfcusson
 */
public class PanelHeaters_cmd extends javax.swing.JPanel {
ServerLink  srvLnk               = null;
Satellite   sat                  = null;
Log         log                  = null;
private final String LED_OFF="/ca/gc/space/quicksat/ground/images/led_off.gif";
private final String LED_GREEN_ON="/ca/gc/space/quicksat/ground/images/led_green_on.gif";
private final String LED_RED_ON="/ca/gc/space/quicksat/ground/images/led_red_on.gif";
private final String LED_WHITE="/ca/gc/space/quicksat/ground/images/led_white.gif";
    
    /** Creates new form PanelHeaters */
    public PanelHeaters_cmd( Log log ) {
        initComponents();
        this.log = log;                
        if( this.log == null ) this.log = new Log();
    }
    /*========================================================================*/    
    /** Set the object that is in charge of managing the link with the ground
     *  station server.
     *  @param srvLnk ServerLink used to communicate with the server.     */
    /*========================================================================*/
    public void setServerLink( ServerLink srvLnk ) {
    /*========================================================================*/    
        this.srvLnk = srvLnk;
    }
    
    /*========================================================================*/
    /** Set the object representing the satellite that we want to communicate
     *  with, and understanding the format of the commands.
     *  @param sat Satellite object representing our satellite.               */
    /*========================================================================*/
    public void setSatellite( Satellite sat ) {
    /*========================================================================*/    
        this.sat = sat;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
              panelHeaters = new javax.swing.JPanel();
              jPanel73 = new javax.swing.JPanel();
              jPanel74 = new javax.swing.JPanel();
              btnHtrEnable = new javax.swing.JButton();
              btnHtrDisable = new javax.swing.JButton();
              jPanel87 = new javax.swing.JPanel();
              panHtrSurvBank = new javax.swing.JPanel();
              jLabel60 = new javax.swing.JLabel();
              panHtrSurvPower = new javax.swing.JPanel();
              btnHtrSurvON = new javax.swing.JButton();
              btnHtrSurvOFF = new javax.swing.JButton();
              jPanel78 = new javax.swing.JPanel();
              btnHtr1ON = new javax.swing.JButton();
              btnHtr1OFF = new javax.swing.JButton();
              jLabel28 = new javax.swing.JLabel();
              jPanel79 = new javax.swing.JPanel();
              btnHtr2ON = new javax.swing.JButton();
              btnHtr2OFF = new javax.swing.JButton();
              jLabel29 = new javax.swing.JLabel();
              jPanel80 = new javax.swing.JPanel();
              btnHtr3ON = new javax.swing.JButton();
              btnHtr3OFF = new javax.swing.JButton();
              jLabel30 = new javax.swing.JLabel();
              jPanel81 = new javax.swing.JPanel();
              btnHtr4ON = new javax.swing.JButton();
              btnHtr4OFF = new javax.swing.JButton();
              jLabel31 = new javax.swing.JLabel();
              panHtrOpBank = new javax.swing.JPanel();
              jLabel173 = new javax.swing.JLabel();
              panHtrOpPower = new javax.swing.JPanel();
              btnHtrOpON = new javax.swing.JButton();
              btnHtrOpOFF = new javax.swing.JButton();
              jPanel83 = new javax.swing.JPanel();
              btnHtr5ON = new javax.swing.JButton();
              btnHtr5OFF = new javax.swing.JButton();
              jLabel33 = new javax.swing.JLabel();
              jPanel84 = new javax.swing.JPanel();
              btnHtr6ON = new javax.swing.JButton();
              btnHtr6OFF = new javax.swing.JButton();
              jLabel34 = new javax.swing.JLabel();
              jPanel85 = new javax.swing.JPanel();
              btnHtr7ON = new javax.swing.JButton();
              btnHtr7OFF = new javax.swing.JButton();
              jLabel35 = new javax.swing.JLabel();
              jPanel86 = new javax.swing.JPanel();
              btnHtr8ON = new javax.swing.JButton();
              btnHtr8OFF = new javax.swing.JButton();
              jLabel36 = new javax.swing.JLabel();
              
              setLayout(new java.awt.BorderLayout());
              
              jPanel73.setLayout(new javax.swing.BoxLayout(jPanel73, javax.swing.BoxLayout.X_AXIS));
              
              jPanel73.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
              jPanel74.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));
              
              btnHtrEnable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
              btnHtrEnable.setText("ENABLE");
              btnHtrEnable.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                      btnHtrEnableActionPerformed(evt);
                  }
              });
              
              jPanel74.add(btnHtrEnable);
              
              btnHtrDisable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
              btnHtrDisable.setText("DISABLE");
              btnHtrDisable.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                      btnHtrDisableActionPerformed(evt);
                  }
              });
              
              jPanel74.add(btnHtrDisable);
              
              jPanel73.add(jPanel74);
            
            panHtrSurvBank.setLayout(new javax.swing.BoxLayout(panHtrSurvBank, javax.swing.BoxLayout.Y_AXIS));
                
                panHtrSurvBank.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                panHtrSurvBank.setPreferredSize(new java.awt.Dimension(206, 203));
                jLabel60.setText("SURVIVAL");
                jLabel60.setForeground(java.awt.Color.white);
                jLabel60.setBackground(java.awt.Color.darkGray);
                jLabel60.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel60.setFont(new java.awt.Font("Arial Black", 0, 14));
                jLabel60.setAlignmentX(0.5F);
                jLabel60.setMaximumSize(new java.awt.Dimension(1500, 21));
                jLabel60.setOpaque(true);
                panHtrSurvBank.add(jLabel60);
                
                panHtrSurvPower.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));
                  
                  panHtrSurvPower.setBorder(new javax.swing.border.TitledBorder("Power - Primary Command"));
                  panHtrSurvPower.setPreferredSize(new java.awt.Dimension(205, 66));
                  btnHtrSurvON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                  btnHtrSurvON.setText("ON");
                  btnHtrSurvON.setPreferredSize(new java.awt.Dimension(77, 29));
                  btnHtrSurvON.setMaximumSize(new java.awt.Dimension(77, 29));
                  btnHtrSurvON.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnHtrSurvONActionPerformed(evt);
                      }
                  });
                  
                  panHtrSurvPower.add(btnHtrSurvON);
                  
                  btnHtrSurvOFF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                  btnHtrSurvOFF.setText("OFF");
                  btnHtrSurvOFF.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnHtrSurvOFFActionPerformed(evt);
                      }
                  });
                  
                  panHtrSurvPower.add(btnHtrSurvOFF);
                  
                  panHtrSurvBank.add(panHtrSurvPower);
                
                jPanel78.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));
                  
                  jPanel78.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                  btnHtr1ON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                  btnHtr1ON.setText("ON");
                  btnHtr1ON.setPreferredSize(new java.awt.Dimension(77, 29));
                  btnHtr1ON.setMaximumSize(new java.awt.Dimension(77, 29));
                  btnHtr1ON.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnHtr1ONActionPerformed(evt);
                      }
                  });
                  
                  jPanel78.add(btnHtr1ON);
                  
                  btnHtr1OFF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                  btnHtr1OFF.setText("OFF");
                  btnHtr1OFF.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnHtr1OFFActionPerformed(evt);
                      }
                  });
                  
                  jPanel78.add(btnHtr1OFF);
                  
                  jLabel28.setText(" 1 ");
                  jLabel28.setForeground(java.awt.Color.white);
                  jLabel28.setBackground(java.awt.Color.darkGray);
                  jLabel28.setFont(new java.awt.Font("Zurich BlkEx BT", 1, 18));
                  jLabel28.setOpaque(true);
                  jPanel78.add(jLabel28);
                  
                  panHtrSurvBank.add(jPanel78);
                
                jPanel79.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));
                  
                  jPanel79.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                  btnHtr2ON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                  btnHtr2ON.setText("ON");
                  btnHtr2ON.setPreferredSize(new java.awt.Dimension(77, 29));
                  btnHtr2ON.setMaximumSize(new java.awt.Dimension(77, 29));
                  btnHtr2ON.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnHtr2ONActionPerformed(evt);
                      }
                  });
                  
                  jPanel79.add(btnHtr2ON);
                  
                  btnHtr2OFF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                  btnHtr2OFF.setText("OFF");
                  btnHtr2OFF.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnHtr2OFFActionPerformed(evt);
                      }
                  });
                  
                  jPanel79.add(btnHtr2OFF);
                  
                  jLabel29.setText(" 2 ");
                  jLabel29.setForeground(java.awt.Color.white);
                  jLabel29.setBackground(java.awt.Color.darkGray);
                  jLabel29.setFont(new java.awt.Font("Zurich BlkEx BT", 1, 18));
                  jLabel29.setOpaque(true);
                  jPanel79.add(jLabel29);
                  
                  panHtrSurvBank.add(jPanel79);
                
                jPanel80.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));
                  
                  jPanel80.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                  btnHtr3ON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                  btnHtr3ON.setText("ON");
                  btnHtr3ON.setPreferredSize(new java.awt.Dimension(77, 29));
                  btnHtr3ON.setMaximumSize(new java.awt.Dimension(77, 29));
                  btnHtr3ON.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnHtr3ONActionPerformed(evt);
                      }
                  });
                  
                  jPanel80.add(btnHtr3ON);
                  
                  btnHtr3OFF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                  btnHtr3OFF.setText("OFF");
                  btnHtr3OFF.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnHtr3OFFActionPerformed(evt);
                      }
                  });
                  
                  jPanel80.add(btnHtr3OFF);
                  
                  jLabel30.setText(" 3 ");
                  jLabel30.setForeground(java.awt.Color.white);
                  jLabel30.setBackground(java.awt.Color.darkGray);
                  jLabel30.setFont(new java.awt.Font("Zurich BlkEx BT", 1, 18));
                  jLabel30.setOpaque(true);
                  jPanel80.add(jLabel30);
                  
                  panHtrSurvBank.add(jPanel80);
                
                jPanel81.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));
                  
                  jPanel81.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                  btnHtr4ON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                  btnHtr4ON.setText("ON");
                  btnHtr4ON.setPreferredSize(new java.awt.Dimension(77, 29));
                  btnHtr4ON.setMaximumSize(new java.awt.Dimension(77, 29));
                  btnHtr4ON.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnHtr4ONActionPerformed(evt);
                      }
                  });
                  
                  jPanel81.add(btnHtr4ON);
                  
                  btnHtr4OFF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                  btnHtr4OFF.setText("OFF");
                  btnHtr4OFF.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnHtr4OFFActionPerformed(evt);
                      }
                  });
                  
                  jPanel81.add(btnHtr4OFF);
                  
                  jLabel31.setText(" 4 ");
                  jLabel31.setForeground(java.awt.Color.white);
                  jLabel31.setBackground(java.awt.Color.darkGray);
                  jLabel31.setFont(new java.awt.Font("Zurich BlkEx BT", 1, 18));
                  jLabel31.setOpaque(true);
                  jPanel81.add(jLabel31);
                  
                  panHtrSurvBank.add(jPanel81);
                
                jPanel87.add(panHtrSurvBank);
              
              panHtrOpBank.setLayout(new javax.swing.BoxLayout(panHtrOpBank, javax.swing.BoxLayout.Y_AXIS));
                
                panHtrOpBank.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                jLabel173.setText("OPERATIONAL");
                jLabel173.setForeground(java.awt.Color.white);
                jLabel173.setBackground(java.awt.Color.darkGray);
                jLabel173.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel173.setFont(new java.awt.Font("Arial Black", 0, 14));
                jLabel173.setAlignmentX(0.5F);
                jLabel173.setMaximumSize(new java.awt.Dimension(1500, 21));
                jLabel173.setOpaque(true);
                panHtrOpBank.add(jLabel173);
                
                panHtrOpPower.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));
                  
                  panHtrOpPower.setBorder(new javax.swing.border.TitledBorder("Power - Primary Command"));
                  btnHtrOpON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                  btnHtrOpON.setText("ON");
                  btnHtrOpON.setPreferredSize(new java.awt.Dimension(77, 29));
                  btnHtrOpON.setMaximumSize(new java.awt.Dimension(77, 29));
                  btnHtrOpON.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnHtrOpONActionPerformed(evt);
                      }
                  });
                  
                  panHtrOpPower.add(btnHtrOpON);
                  
                  btnHtrOpOFF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                  btnHtrOpOFF.setText("OFF");
                  btnHtrOpOFF.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnHtrOpOFFActionPerformed(evt);
                      }
                  });
                  
                  panHtrOpPower.add(btnHtrOpOFF);
                  
                  panHtrOpBank.add(panHtrOpPower);
                
                jPanel83.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));
                  
                  jPanel83.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                  btnHtr5ON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                  btnHtr5ON.setText("ON");
                  btnHtr5ON.setPreferredSize(new java.awt.Dimension(77, 29));
                  btnHtr5ON.setMaximumSize(new java.awt.Dimension(77, 29));
                  btnHtr5ON.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnHtr5ONActionPerformed(evt);
                      }
                  });
                  
                  jPanel83.add(btnHtr5ON);
                  
                  btnHtr5OFF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                  btnHtr5OFF.setText("OFF");
                  btnHtr5OFF.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnHtr5OFFActionPerformed(evt);
                      }
                  });
                  
                  jPanel83.add(btnHtr5OFF);
                  
                  jLabel33.setText(" 5 ");
                  jLabel33.setForeground(java.awt.Color.white);
                  jLabel33.setBackground(java.awt.Color.darkGray);
                  jLabel33.setFont(new java.awt.Font("Zurich BlkEx BT", 1, 18));
                  jLabel33.setOpaque(true);
                  jPanel83.add(jLabel33);
                  
                  panHtrOpBank.add(jPanel83);
                
                jPanel84.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));
                  
                  jPanel84.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                  btnHtr6ON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                  btnHtr6ON.setText("ON");
                  btnHtr6ON.setPreferredSize(new java.awt.Dimension(77, 29));
                  btnHtr6ON.setMaximumSize(new java.awt.Dimension(77, 29));
                  btnHtr6ON.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnHtr6ONActionPerformed(evt);
                      }
                  });
                  
                  jPanel84.add(btnHtr6ON);
                  
                  btnHtr6OFF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                  btnHtr6OFF.setText("OFF");
                  btnHtr6OFF.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnHtr6OFFActionPerformed(evt);
                      }
                  });
                  
                  jPanel84.add(btnHtr6OFF);
                  
                  jLabel34.setText(" 6 ");
                  jLabel34.setForeground(java.awt.Color.white);
                  jLabel34.setBackground(java.awt.Color.darkGray);
                  jLabel34.setFont(new java.awt.Font("Zurich BlkEx BT", 1, 18));
                  jLabel34.setOpaque(true);
                  jPanel84.add(jLabel34);
                  
                  panHtrOpBank.add(jPanel84);
                
                jPanel85.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));
                  
                  jPanel85.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                  btnHtr7ON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                  btnHtr7ON.setText("ON");
                  btnHtr7ON.setPreferredSize(new java.awt.Dimension(77, 29));
                  btnHtr7ON.setMaximumSize(new java.awt.Dimension(77, 29));
                  btnHtr7ON.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnHtr7ONActionPerformed(evt);
                      }
                  });
                  
                  jPanel85.add(btnHtr7ON);
                  
                  btnHtr7OFF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                  btnHtr7OFF.setText("OFF");
                  btnHtr7OFF.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnHtr7OFFActionPerformed(evt);
                      }
                  });
                  
                  jPanel85.add(btnHtr7OFF);
                  
                  jLabel35.setText(" 7 ");
                  jLabel35.setForeground(java.awt.Color.white);
                  jLabel35.setBackground(java.awt.Color.darkGray);
                  jLabel35.setFont(new java.awt.Font("Zurich BlkEx BT", 1, 18));
                  jLabel35.setOpaque(true);
                  jPanel85.add(jLabel35);
                  
                  panHtrOpBank.add(jPanel85);
                
                jPanel86.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 0));
                  
                  jPanel86.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                  btnHtr8ON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                  btnHtr8ON.setText("ON");
                  btnHtr8ON.setPreferredSize(new java.awt.Dimension(77, 29));
                  btnHtr8ON.setMaximumSize(new java.awt.Dimension(77, 29));
                  btnHtr8ON.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnHtr8ONActionPerformed(evt);
                      }
                  });
                  
                  jPanel86.add(btnHtr8ON);
                  
                  btnHtr8OFF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                  btnHtr8OFF.setText("OFF");
                  btnHtr8OFF.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnHtr8OFFActionPerformed(evt);
                      }
                  });
                  
                  jPanel86.add(btnHtr8OFF);
                  
                  jLabel36.setText(" 8 ");
                  jLabel36.setForeground(java.awt.Color.white);
                  jLabel36.setBackground(java.awt.Color.darkGray);
                  jLabel36.setFont(new java.awt.Font("Zurich BlkEx BT", 1, 18));
                  jLabel36.setOpaque(true);
                  jPanel86.add(jLabel36);
                  
                  panHtrOpBank.add(jPanel86);
                
                jPanel87.add(panHtrOpBank);
              
              jPanel73.add(jPanel87);
            
            panelHeaters.add(jPanel73);
          
          add(panelHeaters, java.awt.BorderLayout.CENTER);
        
    }//GEN-END:initComponents

    private void btnHtr8OFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHtr8OFFActionPerformed
        showButtonInactive( btnHtr8ON );
        SatControl ctrl = sat.getControl();
        if( (ctrl==null) || (srvLnk==null) ) return;
        srvLnk.sendPacketToSpacecraft(ctrl.messageToDeactivateHeater(8));
    }//GEN-LAST:event_btnHtr8OFFActionPerformed

    private void btnHtr7OFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHtr7OFFActionPerformed
        showButtonInactive( btnHtr7ON );
        SatControl ctrl = sat.getControl();
        if( (ctrl==null) || (srvLnk==null) ) return;
        srvLnk.sendPacketToSpacecraft(ctrl.messageToDeactivateHeater(7));
    }//GEN-LAST:event_btnHtr7OFFActionPerformed

    private void btnHtr6OFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHtr6OFFActionPerformed
        showButtonInactive( btnHtr6ON );
        SatControl ctrl = sat.getControl();
        if( (ctrl==null) || (srvLnk==null) ) return;
        srvLnk.sendPacketToSpacecraft(ctrl.messageToDeactivateHeater(6));
    }//GEN-LAST:event_btnHtr6OFFActionPerformed

    private void btnHtr5OFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHtr5OFFActionPerformed
        showButtonInactive( btnHtr5ON );
        SatControl ctrl = sat.getControl();
        if( (ctrl==null) || (srvLnk==null) ) return;
        srvLnk.sendPacketToSpacecraft(ctrl.messageToDeactivateHeater(5));
    }//GEN-LAST:event_btnHtr5OFFActionPerformed

    private void btnHtr4OFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHtr4OFFActionPerformed
        showButtonInactive( btnHtr4ON );
        SatControl ctrl = sat.getControl();
        if( (ctrl==null) || (srvLnk==null) ) return;
        srvLnk.sendPacketToSpacecraft(ctrl.messageToDeactivateHeater(4));
    }//GEN-LAST:event_btnHtr4OFFActionPerformed

    private void btnHtr3OFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHtr3OFFActionPerformed
        showButtonInactive( btnHtr3ON );
        SatControl ctrl = sat.getControl();
        if( (ctrl==null) || (srvLnk==null) ) return;
        srvLnk.sendPacketToSpacecraft(ctrl.messageToDeactivateHeater(3));
    }//GEN-LAST:event_btnHtr3OFFActionPerformed

    private void btnHtr2OFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHtr2OFFActionPerformed
        showButtonInactive( btnHtr2ON );
        SatControl ctrl = sat.getControl();
        if( (ctrl==null) || (srvLnk==null) ) return;
        srvLnk.sendPacketToSpacecraft(ctrl.messageToDeactivateHeater(2));
    }//GEN-LAST:event_btnHtr2OFFActionPerformed

    private void btnHtr1OFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHtr1OFFActionPerformed
        showButtonInactive( btnHtr1ON );
        SatControl ctrl = sat.getControl();
        if( (ctrl==null) || (srvLnk==null) ) return;
        srvLnk.sendPacketToSpacecraft(ctrl.messageToDeactivateHeater(1));
    }//GEN-LAST:event_btnHtr1OFFActionPerformed

    private void btnHtr8ONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHtr8ONActionPerformed
        showButtonInactive( btnHtr8OFF );
        SatControl ctrl = sat.getControl();
        if( (ctrl==null) || (srvLnk==null) ) return;
        srvLnk.sendPacketToSpacecraft(ctrl.messageToActivateHeater(8));
    }//GEN-LAST:event_btnHtr8ONActionPerformed

    private void btnHtr7ONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHtr7ONActionPerformed
        showButtonInactive( btnHtr7OFF );
        SatControl ctrl = sat.getControl();
        if( (ctrl==null) || (srvLnk==null) ) return;
        srvLnk.sendPacketToSpacecraft(ctrl.messageToActivateHeater(7));
    }//GEN-LAST:event_btnHtr7ONActionPerformed

    private void btnHtr6ONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHtr6ONActionPerformed
        showButtonInactive( btnHtr6OFF );
        SatControl ctrl = sat.getControl();
        if( (ctrl==null) || (srvLnk==null) ) return;
        srvLnk.sendPacketToSpacecraft(ctrl.messageToActivateHeater(6));
    }//GEN-LAST:event_btnHtr6ONActionPerformed

    private void btnHtr5ONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHtr5ONActionPerformed
        showButtonInactive( btnHtr5OFF );
        SatControl ctrl = sat.getControl();
        if( (ctrl==null) || (srvLnk==null) ) return;
        srvLnk.sendPacketToSpacecraft(ctrl.messageToActivateHeater(5));
    }//GEN-LAST:event_btnHtr5ONActionPerformed

    private void btnHtr4ONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHtr4ONActionPerformed
        showButtonInactive( btnHtr4OFF );
        SatControl ctrl = sat.getControl();
        if( (ctrl==null) || (srvLnk==null) ) return;
        srvLnk.sendPacketToSpacecraft(ctrl.messageToActivateHeater(4));
    }//GEN-LAST:event_btnHtr4ONActionPerformed

    private void btnHtr3ONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHtr3ONActionPerformed
        showButtonInactive( btnHtr3OFF );
        SatControl ctrl = sat.getControl();
        if( (ctrl==null) || (srvLnk==null) ) return;
        srvLnk.sendPacketToSpacecraft(ctrl.messageToActivateHeater(3));
    }//GEN-LAST:event_btnHtr3ONActionPerformed

    private void btnHtr2ONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHtr2ONActionPerformed
        showButtonInactive( btnHtr2OFF );
        SatControl ctrl = sat.getControl();
        if( (ctrl==null) || (srvLnk==null) ) return;
        srvLnk.sendPacketToSpacecraft(ctrl.messageToActivateHeater(2));
    }//GEN-LAST:event_btnHtr2ONActionPerformed

    private void btnHtr1ONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHtr1ONActionPerformed
        showButtonInactive( btnHtr1OFF );
        SatControl ctrl = sat.getControl();
        if( (ctrl==null) || (srvLnk==null) ) return;
        srvLnk.sendPacketToSpacecraft(ctrl.messageToActivateHeater(1));
    }//GEN-LAST:event_btnHtr1ONActionPerformed

    private void btnHtrOpOFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHtrOpOFFActionPerformed
     showButtonInactive( btnHtrOpON );
     SatControl ctrl = sat.getControl();
     if( (ctrl==null) || (srvLnk==null) ) return;
     srvLnk.sendPacketToSpacecraft(ctrl.messageToDisableOperationHeatersBank());
    }//GEN-LAST:event_btnHtrOpOFFActionPerformed

    private void btnHtrOpONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHtrOpONActionPerformed
     showButtonInactive( btnHtrOpOFF );
     SatControl ctrl = sat.getControl();
     if( (ctrl==null) || (srvLnk==null) ) return;
     srvLnk.sendPacketToSpacecraft(ctrl.messageToEnableOperationHeatersBank());
    }//GEN-LAST:event_btnHtrOpONActionPerformed

    private void btnHtrSurvOFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHtrSurvOFFActionPerformed
     showButtonInactive( btnHtrSurvON );
     SatControl ctrl = sat.getControl();
     if( (ctrl==null) || (srvLnk==null) ) return;
     srvLnk.sendPacketToSpacecraft(ctrl.messageToDisableSurvivalHeatersBank());
    }//GEN-LAST:event_btnHtrSurvOFFActionPerformed

    private void btnHtrSurvONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHtrSurvONActionPerformed
     showButtonInactive( btnHtrSurvOFF );
     SatControl ctrl = sat.getControl();
     if( (ctrl==null) || (srvLnk==null) ) return;
     srvLnk.sendPacketToSpacecraft(ctrl.messageToEnableSurvivalHeatersBank());
    }//GEN-LAST:event_btnHtrSurvONActionPerformed

    private void btnHtrEnableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHtrEnableActionPerformed
     showButtonInactive( btnHtrDisable );
     SatControl ctrl = sat.getControl();
     if( (ctrl==null) || (srvLnk==null) ) return;
     srvLnk.sendPacketToSpacecraft(ctrl.messageToTurnHeatersPowerON());
    }//GEN-LAST:event_btnHtrEnableActionPerformed

    private void btnHtrDisableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHtrDisableActionPerformed
     showButtonInactive( btnHtrEnable );
     SatControl ctrl = sat.getControl();
     if( (ctrl==null) || (srvLnk==null) ) return;
     srvLnk.sendPacketToSpacecraft(ctrl.messageToTurnHeatersPowerOFF());
    }//GEN-LAST:event_btnHtrDisableActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelHeaters;
    private javax.swing.JPanel jPanel73;
    private javax.swing.JPanel jPanel74;
    public javax.swing.JButton btnHtrEnable;
    public javax.swing.JButton btnHtrDisable;
    private javax.swing.JPanel jPanel87;
    private javax.swing.JPanel panHtrSurvBank;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JPanel panHtrSurvPower;
    public javax.swing.JButton btnHtrSurvON;
    public javax.swing.JButton btnHtrSurvOFF;
    private javax.swing.JPanel jPanel78;
    public javax.swing.JButton btnHtr1ON;
    public javax.swing.JButton btnHtr1OFF;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JPanel jPanel79;
    public javax.swing.JButton btnHtr2ON;
    public javax.swing.JButton btnHtr2OFF;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JPanel jPanel80;
    public javax.swing.JButton btnHtr3ON;
    public javax.swing.JButton btnHtr3OFF;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JPanel jPanel81;
    public javax.swing.JButton btnHtr4ON;
    public javax.swing.JButton btnHtr4OFF;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JPanel panHtrOpBank;
    private javax.swing.JLabel jLabel173;
    private javax.swing.JPanel panHtrOpPower;
    public javax.swing.JButton btnHtrOpON;
    public javax.swing.JButton btnHtrOpOFF;
    private javax.swing.JPanel jPanel83;
    public javax.swing.JButton btnHtr5ON;
    public javax.swing.JButton btnHtr5OFF;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JPanel jPanel84;
    public javax.swing.JButton btnHtr6ON;
    public javax.swing.JButton btnHtr6OFF;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JPanel jPanel85;
    public javax.swing.JButton btnHtr7ON;
    public javax.swing.JButton btnHtr7OFF;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JPanel jPanel86;
    public javax.swing.JButton btnHtr8ON;
    public javax.swing.JButton btnHtr8OFF;
    private javax.swing.JLabel jLabel36;
    // End of variables declaration//GEN-END:variables
    
    /*------------------------------------------------------------------------*/
    /** Change the appearance of the button so that user knows that the
     *  function associated with this button is not known, but will be as soon
     *  as we receive telemetry information.
     *  @param button The swing button.                                       */
    /*------------------------------------------------------------------------*/
    public void showButtonInactive( JButton button ) {
    /*------------------------------------------------------------------------*/
     button.setIcon(
       new javax.swing.ImageIcon(
        getClass().getResource(LED_OFF)));
    }
    
    /*------------------------------------------------------------------------*/
    /** Change the appearance of the button so that user knows that the
     *  function associated with this button is "active" or "on".
     *  @param button The swing button.                                       */
    /*------------------------------------------------------------------------*/
    public void showButtonActiveON( JButton button ) {
    /*------------------------------------------------------------------------*/
     button.setIcon(
       new javax.swing.ImageIcon(
        getClass().getResource(LED_GREEN_ON)));
    }
    
    /*------------------------------------------------------------------------*/
    /** Change the appearance of the button so that user knows that the
     *  function associated with this button is "inactive" or "off".
     *  @param button The swing button.                                       */
    /*------------------------------------------------------------------------*/
    public void showButtonActiveOFF( JButton button ) {
    /*------------------------------------------------------------------------*/
     button.setIcon(
       new javax.swing.ImageIcon(
        getClass().getResource(LED_RED_ON)));
    }
    
    /*------------------------------------------------------------------------*/
    /** Change the appearance of the button so that user knows that the
     *  state of the function associated with this button is unknown.
     *  @param button The swing button.                                       */
    /*------------------------------------------------------------------------*/
    public void showButtonNeutral( JButton button ) {
    /*------------------------------------------------------------------------*/
     button.setIcon(
       new javax.swing.ImageIcon(
        getClass().getResource(LED_WHITE)));
    } 
   
    
}
