/*
 * panelHouseKeeping_cmd.java
 *
 * Created on July 25, 2001, 4:58 PM
 */

package ca.gc.space.quicksat.ground.control;

import javax.swing.*;
import ca.gc.space.quicksat.ground.client.*;
import ca.gc.space.quicksat.ground.satellite.*;
import ca.gc.space.quicksat.ground.control.*;
import ca.gc.space.quicksat.ground.util.*;

/**
 *
 * @author  jfcusson
 */
public class PanelHouseKeeping_cmd extends javax.swing.JPanel {
ServerLink  srvLnk               = null;
Satellite   sat                  = null;
Log         log                  = null;

private final String LED_OFF="/ca/gc/space/quicksat/ground/images/led_off.gif";
private final String LED_GREEN_ON="/ca/gc/space/quicksat/ground/images/led_green_on.gif";
private final String LED_RED_ON="/ca/gc/space/quicksat/ground/images/led_red_on.gif";
private final String LED_WHITE="/ca/gc/space/quicksat/ground/images/led_white.gif";
    
    /** Creates new form panelHouseKeeping_cmd */
    public PanelHouseKeeping_cmd( Log log ) {        
        initComponents();
        this.log = log;                
        if( this.log == null ) this.log = new Log();        
    }
    /*========================================================================*/    
    /** Set the object that is in charge of managing the link with the ground
     *  station server.
     *  @param srvLnk ServerLink used to communicate with the server.     */
    /*========================================================================*/
    public void setServerLink( ServerLink srvLnk ) {
    /*========================================================================*/    
        this.srvLnk = srvLnk;
    }
    
    /*========================================================================*/
    /** Set the object representing the satellite that we want to communicate
     *  with, and understanding the format of the commands.
     *  @param sat Satellite object representing our satellite.               */
    /*========================================================================*/
    public void setSatellite( Satellite sat ) {
    /*========================================================================*/    
        this.sat = sat;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
                      jScrollPane1 = new javax.swing.JScrollPane();
                      panelHousekeeping = new javax.swing.JPanel();
                      jPanel159 = new javax.swing.JPanel();
                      jPanel188 = new javax.swing.JPanel();
                      panelTelemRate = new javax.swing.JPanel();
                      jPanel245 = new javax.swing.JPanel();
                      jPanel206 = new javax.swing.JPanel();
                      jLabel165 = new javax.swing.JLabel();
                      txtTelemRate = new javax.swing.JTextField();
                      slidTelemRate = new javax.swing.JSlider();
                      btnTelemRate = new javax.swing.JButton();
                      jSeparator11 = new javax.swing.JSeparator();
                      panelTelemState = new javax.swing.JPanel();
                      btnTelemStandbye = new javax.swing.JButton();
                      btnTelemContinuous = new javax.swing.JButton();
                      btnTelemDisable = new javax.swing.JButton();
                      btnTelemOneShot = new javax.swing.JButton();
                      jPanel249 = new javax.swing.JPanel();
                      panelStatusRate = new javax.swing.JPanel();
                      jPanel244 = new javax.swing.JPanel();
                      jLabel166 = new javax.swing.JLabel();
                      txtStatusRate = new javax.swing.JTextField();
                      btnStatusRate = new javax.swing.JButton();
                      panelBroadcastRate = new javax.swing.JPanel();
                      jPanel243 = new javax.swing.JPanel();
                      jLabel168 = new javax.swing.JLabel();
                      txtBroadcastRate = new javax.swing.JTextField();
                      btnBroadcastRate = new javax.swing.JButton();
                      jSeparator10 = new javax.swing.JSeparator();
                      jPanel208 = new javax.swing.JPanel();
                      jLabel167 = new javax.swing.JLabel();
                      txtBroadcastText = new javax.swing.JTextField();
                      btnBroadcastText = new javax.swing.JButton();
                      jPanel136 = new javax.swing.JPanel();
                      jPanel179 = new javax.swing.JPanel();
                      jPanel184 = new javax.swing.JPanel();
                      jLabel169 = new javax.swing.JLabel();
                      txtPHTWakeupDelay = new javax.swing.JTextField();
                      jLabel170 = new javax.swing.JLabel();
                      btnPHTWakeupDelay = new javax.swing.JButton();
                      jPanel204 = new javax.swing.JPanel();
                      jPanel104 = new javax.swing.JPanel();
                      jLabel46 = new javax.swing.JLabel();
                      txtGenericCommand = new javax.swing.JTextField();
                      btnGenericCommand = new javax.swing.JButton();
                      jPanel205 = new javax.swing.JPanel();
                      jPanel168 = new javax.swing.JPanel();
                      btnPHTCrash = new javax.swing.JButton();
                      btnHWACCrash = new javax.swing.JButton();
                      btnSyncTime = new javax.swing.JButton();
                      btnRequestAck = new javax.swing.JButton();
                      
                      setPreferredSize(new java.awt.Dimension(780, 200));
                      setMaximumSize(new java.awt.Dimension(32767, 30000));
                      jScrollPane1.setPreferredSize(new java.awt.Dimension(790, 225));
                      jScrollPane1.setMaximumSize(new java.awt.Dimension(790, 250));
                      jScrollPane1.setAutoscrolls(true);
                      panelHousekeeping.setLayout(new javax.swing.BoxLayout(panelHousekeeping, javax.swing.BoxLayout.X_AXIS));
                      
                      panelHousekeeping.setPreferredSize(new java.awt.Dimension(750, 150));
                      panelHousekeeping.setMaximumSize(new java.awt.Dimension(32767, 400));
                      jPanel159.setLayout(new javax.swing.BoxLayout(jPanel159, javax.swing.BoxLayout.X_AXIS));
                      
                      jPanel159.setPreferredSize(new java.awt.Dimension(380, 200));
                      jPanel188.setLayout(new javax.swing.BoxLayout(jPanel188, javax.swing.BoxLayout.Y_AXIS));
                      
                      jPanel188.setPreferredSize(new java.awt.Dimension(380, 200));
                      jPanel188.setMinimumSize(new java.awt.Dimension(300, 125));
                      panelTelemRate.setLayout(new javax.swing.BoxLayout(panelTelemRate, javax.swing.BoxLayout.Y_AXIS));
                      
                      panelTelemRate.setBorder(new javax.swing.border.TitledBorder("Telemetry Downlink"));
                      panelTelemRate.setPreferredSize(new java.awt.Dimension(380, 60));
                      panelTelemRate.setMinimumSize(new java.awt.Dimension(300, 50));
                      jPanel245.setLayout(new javax.swing.BoxLayout(jPanel245, javax.swing.BoxLayout.Y_AXIS));
                      
                      jPanel245.setPreferredSize(new java.awt.Dimension(390, 94));
                      jPanel206.setPreferredSize(new java.awt.Dimension(338, 30));
                      jPanel206.setMinimumSize(new java.awt.Dimension(193, 25));
                      jLabel165.setText("Rate Divider:");
                      jPanel206.add(jLabel165);
                      
                      txtTelemRate.setToolTipText("0-15");
                      txtTelemRate.setPreferredSize(new java.awt.Dimension(35, 20));
                      txtTelemRate.addKeyListener(new java.awt.event.KeyAdapter() {
                          public void keyReleased(java.awt.event.KeyEvent evt) {
                              txtTelemRateKeyReleased(evt);
                          }
                      });
                      
                      jPanel206.add(txtTelemRate);
                      
                      slidTelemRate.setMinorTickSpacing(1);
                      slidTelemRate.setPaintLabels(true);
                      slidTelemRate.setPaintTicks(true);
                      slidTelemRate.setMajorTickSpacing(10);
                      slidTelemRate.setMaximum(15);
                      slidTelemRate.setValue(0);
                      slidTelemRate.setPreferredSize(new java.awt.Dimension(150, 43));
                      txtTelemRate.setText(""+slidTelemRate.getValue());
                      slidTelemRate.addChangeListener(new javax.swing.event.ChangeListener() {
                          public void stateChanged(javax.swing.event.ChangeEvent evt) {
                              slidTelemRateStateChanged(evt);
                          }
                      });
                      
                      jPanel206.add(slidTelemRate);
                      
                      btnTelemRate.setText("SET");
                      btnTelemRate.addActionListener(new java.awt.event.ActionListener() {
                          public void actionPerformed(java.awt.event.ActionEvent evt) {
                              btnTelemRateActionPerformed(evt);
                          }
                      });
                      
                      jPanel206.add(btnTelemRate);
                      
                      jPanel245.add(jPanel206);
                    
                    jPanel245.add(jSeparator11);
                    
                    panelTelemState.setPreferredSize(new java.awt.Dimension(380, 25));
                      panelTelemState.setMinimumSize(new java.awt.Dimension(377, 20));
                      btnTelemStandbye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                      btnTelemStandbye.setText("Stndbye");
                      btnTelemStandbye.addActionListener(new java.awt.event.ActionListener() {
                          public void actionPerformed(java.awt.event.ActionEvent evt) {
                              btnTelemStandbyeActionPerformed(evt);
                          }
                      });
                      
                      panelTelemState.add(btnTelemStandbye);
                      
                      btnTelemContinuous.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                      btnTelemContinuous.setText("Cont.");
                      btnTelemContinuous.addActionListener(new java.awt.event.ActionListener() {
                          public void actionPerformed(java.awt.event.ActionEvent evt) {
                              btnTelemContinuousActionPerformed(evt);
                          }
                      });
                      
                      panelTelemState.add(btnTelemContinuous);
                      
                      btnTelemDisable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                      btnTelemDisable.setText("Disable");
                      btnTelemDisable.addActionListener(new java.awt.event.ActionListener() {
                          public void actionPerformed(java.awt.event.ActionEvent evt) {
                              btnTelemDisableActionPerformed(evt);
                          }
                      });
                      
                      panelTelemState.add(btnTelemDisable);
                      
                      btnTelemOneShot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                      btnTelemOneShot.setText("Once");
                      btnTelemOneShot.addActionListener(new java.awt.event.ActionListener() {
                          public void actionPerformed(java.awt.event.ActionEvent evt) {
                              btnTelemOneShotActionPerformed(evt);
                          }
                      });
                      
                      panelTelemState.add(btnTelemOneShot);
                      
                      jPanel245.add(panelTelemState);
                    
                    panelTelemRate.add(jPanel245);
                  
                  jPanel188.add(panelTelemRate);
                
                jPanel249.setLayout(new javax.swing.BoxLayout(jPanel249, javax.swing.BoxLayout.X_AXIS));
                      
                      jPanel249.setPreferredSize(new java.awt.Dimension(380, 30));
                      jPanel249.setMinimumSize(new java.awt.Dimension(300, 20));
                      panelStatusRate.setLayout(new javax.swing.BoxLayout(panelStatusRate, javax.swing.BoxLayout.Y_AXIS));
                      
                      panelStatusRate.setBorder(new javax.swing.border.TitledBorder("Status Message"));
                      panelStatusRate.setPreferredSize(new java.awt.Dimension(165, 25));
                      panelStatusRate.setMinimumSize(new java.awt.Dimension(162, 20));
                      jPanel244.setPreferredSize(new java.awt.Dimension(160, 37));
                      jLabel166.setText("Rate Divider:");
                      jPanel244.add(jLabel166);
                      
                      txtStatusRate.setToolTipText("0-15");
                      txtStatusRate.setPreferredSize(new java.awt.Dimension(35, 20));
                      jPanel244.add(txtStatusRate);
                      
                      btnStatusRate.setText("SET");
                      btnStatusRate.addActionListener(new java.awt.event.ActionListener() {
                          public void actionPerformed(java.awt.event.ActionEvent evt) {
                              btnStatusRateActionPerformed(evt);
                          }
                      });
                      
                      jPanel244.add(btnStatusRate);
                      
                      panelStatusRate.add(jPanel244);
                    
                    jPanel249.add(panelStatusRate);
                  
                  panelBroadcastRate.setLayout(new javax.swing.BoxLayout(panelBroadcastRate, javax.swing.BoxLayout.Y_AXIS));
                      
                      panelBroadcastRate.setBorder(new javax.swing.border.TitledBorder("Broadcast Message"));
                      panelBroadcastRate.setPreferredSize(new java.awt.Dimension(180, 30));
                      panelBroadcastRate.setMinimumSize(new java.awt.Dimension(162, 20));
                      jPanel243.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 1));
                      
                      jLabel168.setText("Rate Divider:");
                      jPanel243.add(jLabel168);
                      
                      txtBroadcastRate.setToolTipText("0-15");
                      txtBroadcastRate.setPreferredSize(new java.awt.Dimension(35, 20));
                      jPanel243.add(txtBroadcastRate);
                      
                      btnBroadcastRate.setText("SET");
                      btnBroadcastRate.addActionListener(new java.awt.event.ActionListener() {
                          public void actionPerformed(java.awt.event.ActionEvent evt) {
                              btnBroadcastRateActionPerformed(evt);
                          }
                      });
                      
                      jPanel243.add(btnBroadcastRate);
                      
                      panelBroadcastRate.add(jPanel243);
                    
                    panelBroadcastRate.add(jSeparator10);
                    
                    jPanel208.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 1));
                      
                      jLabel167.setText("Text:");
                      jPanel208.add(jLabel167);
                      
                      txtBroadcastText.setToolTipText("Max 199 characters");
                      txtBroadcastText.setPreferredSize(new java.awt.Dimension(100, 20));
                      jPanel208.add(txtBroadcastText);
                      
                      btnBroadcastText.setText("SET");
                      btnBroadcastText.addActionListener(new java.awt.event.ActionListener() {
                          public void actionPerformed(java.awt.event.ActionEvent evt) {
                              btnBroadcastTextActionPerformed(evt);
                          }
                      });
                      
                      jPanel208.add(btnBroadcastText);
                      
                      panelBroadcastRate.add(jPanel208);
                    
                    jPanel249.add(panelBroadcastRate);
                  
                  jPanel188.add(jPanel249);
                
                jPanel159.add(jPanel188);
              
              panelHousekeeping.add(jPanel159);
            
            jPanel136.setLayout(new javax.swing.BoxLayout(jPanel136, javax.swing.BoxLayout.Y_AXIS));
                  
                  jPanel136.setPreferredSize(new java.awt.Dimension(200, 200));
                  jPanel136.setMinimumSize(new java.awt.Dimension(200, 118));
                  jPanel179.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 2, 1));
                  
                  jPanel179.setBorder(new javax.swing.border.TitledBorder("Housekeeping Task Rate"));
                  jPanel179.setPreferredSize(new java.awt.Dimension(180, 60));
                  jPanel184.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 1, 1));
                  
                  jPanel184.setPreferredSize(new java.awt.Dimension(170, 30));
                  jPanel184.setMinimumSize(new java.awt.Dimension(132, 20));
                  jLabel169.setText("Rate:");
                  jPanel184.add(jLabel169);
                  
                  txtPHTWakeupDelay.setToolTipText("0-15");
                  txtPHTWakeupDelay.setPreferredSize(new java.awt.Dimension(30, 20));
                  jPanel184.add(txtPHTWakeupDelay);
                  
                  jLabel170.setText("Sec");
                  jPanel184.add(jLabel170);
                  
                  btnPHTWakeupDelay.setText("SET");
                  btnPHTWakeupDelay.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnPHTWakeupDelayActionPerformed(evt);
                      }
                  });
                  
                  jPanel184.add(btnPHTWakeupDelay);
                  
                  jPanel179.add(jPanel184);
                
                jPanel136.add(jPanel179);
              
              jPanel204.setLayout(new javax.swing.BoxLayout(jPanel204, javax.swing.BoxLayout.Y_AXIS));
                  
                  jPanel204.setBorder(new javax.swing.border.TitledBorder("Generic Command"));
                  jPanel204.setPreferredSize(new java.awt.Dimension(250, 55));
                  jPanel104.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 1));
                  
                  jPanel104.setPreferredSize(new java.awt.Dimension(300, 30));
                  jPanel104.setMinimumSize(new java.awt.Dimension(200, 20));
                  jPanel104.setMaximumSize(new java.awt.Dimension(500, 64));
                  jLabel46.setText("COMMND");
                  jPanel104.add(jLabel46);
                  
                  txtGenericCommand.setPreferredSize(new java.awt.Dimension(100, 20));
                  txtGenericCommand.setMinimumSize(new java.awt.Dimension(100, 20));
                  jPanel104.add(txtGenericCommand);
                  
                  btnGenericCommand.setText("SEND");
                  btnGenericCommand.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnGenericCommandActionPerformed(evt);
                      }
                  });
                  
                  jPanel104.add(btnGenericCommand);
                  
                  jPanel204.add(jPanel104);
                
                jPanel136.add(jPanel204);
              
              jPanel205.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));
                  
                  jPanel205.setBorder(new javax.swing.border.TitledBorder("Task Control & Other Commands"));
                  jPanel205.setPreferredSize(new java.awt.Dimension(180, 60));
                  jPanel205.setMinimumSize(new java.awt.Dimension(250, 30));
                  jPanel168.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 1));
                  
                  jPanel168.setPreferredSize(new java.awt.Dimension(250, 60));
                  jPanel168.setMinimumSize(new java.awt.Dimension(199, 20));
                  btnPHTCrash.setForeground(java.awt.Color.yellow);
                  btnPHTCrash.setFont(new java.awt.Font("Arial Narrow", 1, 12));
                  btnPHTCrash.setText("HOT RESET");
                  btnPHTCrash.setBackground(java.awt.Color.red);
                  btnPHTCrash.setAlignmentX(0.5F);
                  btnPHTCrash.setPreferredSize(new java.awt.Dimension(97, 25));
                  btnPHTCrash.setMaximumSize(new java.awt.Dimension(97, 25));
                  btnPHTCrash.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnPHTCrashActionPerformed(evt);
                      }
                  });
                  
                  jPanel168.add(btnPHTCrash);
                  
                  btnHWACCrash.setText("Kill HWAC");
                  btnHWACCrash.setPreferredSize(new java.awt.Dimension(107, 27));
                  btnHWACCrash.setMaximumSize(new java.awt.Dimension(107, 27));
                  btnHWACCrash.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnHWACCrashActionPerformed(evt);
                      }
                  });
                  
                  jPanel168.add(btnHWACCrash);
                  
                  btnSyncTime.setToolTipText("Synchronize with the PC clock");
                  btnSyncTime.setText("Sync. Time");
                  btnSyncTime.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnSyncTimeActionPerformed(evt);
                      }
                  });
                  
                  jPanel168.add(btnSyncTime);
                  
                  btnRequestAck.setToolTipText("COMMAND \"A\": Request an acknowledge from first PHT");
                  btnRequestAck.setText("Request Ack");
                  btnRequestAck.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnRequestAckActionPerformed(evt);
                      }
                  });
                  
                  jPanel168.add(btnRequestAck);
                  
                  jPanel205.add(jPanel168);
                
                jPanel136.add(jPanel205);
              
              panelHousekeeping.add(jPanel136);
            
            jScrollPane1.setViewportView(panelHousekeeping);
          
          add(jScrollPane1);
        
    }//GEN-END:initComponents

  private void btnRequestAckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestAckActionPerformed
        SatControl ctrl = sat.getControl();
        if( (ctrl==null) || (srvLnk==null) ) return;
        srvLnk.sendPacketToSpacecraft(ctrl.messageToRequestBeacon());
  }//GEN-LAST:event_btnRequestAckActionPerformed

  private void btnSyncTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSyncTimeActionPerformed
        SatControl ctrl = sat.getControl();
        if( (ctrl==null) || (srvLnk==null) ) return;
        long currentTime = (long)(System.currentTimeMillis()/1000);
        srvLnk.sendPacketToSpacecraft(ctrl.messageToSetTime(currentTime));
  }//GEN-LAST:event_btnSyncTimeActionPerformed

    private void txtTelemRateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelemRateKeyReleased
        slidTelemRate.setValue( Integer.parseInt(txtTelemRate.getText()) );
    }//GEN-LAST:event_txtTelemRateKeyReleased
 
    private void slidTelemRateStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slidTelemRateStateChanged
        txtTelemRate.setText(""+slidTelemRate.getValue());
    }//GEN-LAST:event_slidTelemRateStateChanged

    private void btnTelemStandbyeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelemStandbyeActionPerformed
        showButtonActiveON( btnTelemStandbye );
        showButtonActiveOFF( btnTelemContinuous );
        showButtonActiveOFF( btnTelemDisable );
        SatControl ctrl = sat.getControl();
        if( (ctrl==null) || (srvLnk==null) ) return;
        srvLnk.sendPacketToSpacecraft(ctrl.messageToPutTelemetryOnStandbye());
    }//GEN-LAST:event_btnTelemStandbyeActionPerformed

    private void btnBroadcastTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBroadcastTextActionPerformed
        SatControl ctrl = sat.getControl();
        if( (ctrl==null) || (srvLnk==null) ) return;
        srvLnk.sendPacketToSpacecraft(
             ctrl.messageToSetTextBroadcast(txtBroadcastText.getText().trim()));
    }//GEN-LAST:event_btnBroadcastTextActionPerformed

    private void btnHWACCrashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHWACCrashActionPerformed
        int result = JOptionPane.showConfirmDialog(this,"TERMINATE the Hardware Access Task?","TERMINATE HWAC", JOptionPane.OK_CANCEL_OPTION);
        if( result != JOptionPane.OK_OPTION ) return;
        SatControl ctrl = sat.getControl();
        if( (ctrl==null) || (srvLnk==null) ) return;
        srvLnk.sendPacketToSpacecraft(ctrl.messageToTerminateHWAC());      
    }//GEN-LAST:event_btnHWACCrashActionPerformed

    private void btnTelemContinuousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelemContinuousActionPerformed
        showButtonActiveOFF( btnTelemStandbye );
        showButtonActiveON( btnTelemContinuous );
        showButtonActiveOFF( btnTelemDisable );
        SatControl ctrl = sat.getControl();
        if( (ctrl==null) || (srvLnk==null) ) return;
        srvLnk.sendPacketToSpacecraft(ctrl.messageToSetContinuousTelemetry());
    }//GEN-LAST:event_btnTelemContinuousActionPerformed

    private void btnTelemDisableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelemDisableActionPerformed
        showButtonActiveOFF( btnTelemStandbye );
        showButtonActiveOFF( btnTelemContinuous );
        showButtonActiveON( btnTelemDisable );
        SatControl ctrl = sat.getControl();
        if( (ctrl==null) || (srvLnk==null) ) return;
        srvLnk.sendPacketToSpacecraft(ctrl.messageToDisableTelemetry());
    }//GEN-LAST:event_btnTelemDisableActionPerformed

    private void btnPHTCrashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPHTCrashActionPerformed
        int result = JOptionPane.showConfirmDialog(this,"CRASH the flight software and return to bootloader?","CRASH", JOptionPane.OK_CANCEL_OPTION);
        if( result != JOptionPane.OK_OPTION ) return;
        SatControl ctrl = sat.getControl();
        if( (ctrl==null) || (srvLnk==null) ) return;
        srvLnk.sendPacketToSpacecraft(ctrl.messageToCrashToBootloader());      
    }//GEN-LAST:event_btnPHTCrashActionPerformed

    private void btnGenericCommandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenericCommandActionPerformed
        SatControl ctrl = sat.getControl();
        if( (ctrl==null) || (srvLnk==null) ) return;
        srvLnk.sendPacketToSpacecraft(
            ctrl.messageGeneric(txtGenericCommand.getText().trim().getBytes()));
    }//GEN-LAST:event_btnGenericCommandActionPerformed

    private void btnPHTWakeupDelayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPHTWakeupDelayActionPerformed
      SatControl ctrl = sat.getControl();
      if( (ctrl==null) || (srvLnk==null) ) return;
      int delay = 0;
      try{
        delay = Integer.parseInt(txtPHTWakeupDelay.getText().trim());
        srvLnk.sendPacketToSpacecraft(ctrl.messageToSetHousekeepingRate(delay));
      }catch(NumberFormatException e){}
    }//GEN-LAST:event_btnPHTWakeupDelayActionPerformed

    private void btnTelemRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelemRateActionPerformed
        SatControl ctrl = sat.getControl();
        if( (ctrl==null) || (srvLnk==null) ) return;
        srvLnk.sendPacketToSpacecraft(
            ctrl.messageToSetBinaryTelemetryRate(slidTelemRate.getValue()));
    }//GEN-LAST:event_btnTelemRateActionPerformed

    private void btnStatusRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStatusRateActionPerformed
        SatControl ctrl = sat.getControl();
        if( (ctrl==null) || (srvLnk==null) ) return;
        int rate = 0;
        try{
            rate = Integer.parseInt(txtStatusRate.getText());            
            srvLnk.sendPacketToSpacecraft(
                                     ctrl.messageToSetASCIITelemetryRate(rate));
        }catch(NumberFormatException e){}
    }//GEN-LAST:event_btnStatusRateActionPerformed

    private void btnBroadcastRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBroadcastRateActionPerformed
        SatControl ctrl = sat.getControl();
        if( (ctrl==null) || (srvLnk==null) ) return;
        int rate = 0;
        try{
            rate = Integer.parseInt(txtBroadcastRate.getText());            
            srvLnk.sendPacketToSpacecraft(
                                     ctrl.messageToSetTextBroadcastRate(rate));
        }catch(NumberFormatException e){}
    }//GEN-LAST:event_btnBroadcastRateActionPerformed

    private void btnTelemOneShotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelemOneShotActionPerformed
        showButtonActiveOFF( btnTelemStandbye );
        showButtonActiveOFF( btnTelemContinuous );
        showButtonActiveOFF( btnTelemDisable );
        
        SatControl ctrl = sat.getControl();
        if( (ctrl==null) || (srvLnk==null) ) return;
        srvLnk.sendPacketToSpacecraft(ctrl.messageToPutTelemetryOnStandbye());
        srvLnk.sendPacketToSpacecraft(ctrl.messageToRequestOneShotTelemetry());
    }//GEN-LAST:event_btnTelemOneShotActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelHousekeeping;
    private javax.swing.JPanel jPanel159;
    private javax.swing.JPanel jPanel188;
    private javax.swing.JPanel panelTelemRate;
    private javax.swing.JPanel jPanel245;
    private javax.swing.JPanel jPanel206;
    private javax.swing.JLabel jLabel165;
    private javax.swing.JTextField txtTelemRate;
    private javax.swing.JSlider slidTelemRate;
    private javax.swing.JButton btnTelemRate;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JPanel panelTelemState;
    private javax.swing.JButton btnTelemStandbye;
    private javax.swing.JButton btnTelemContinuous;
    private javax.swing.JButton btnTelemDisable;
    private javax.swing.JButton btnTelemOneShot;
    private javax.swing.JPanel jPanel249;
    private javax.swing.JPanel panelStatusRate;
    private javax.swing.JPanel jPanel244;
    private javax.swing.JLabel jLabel166;
    private javax.swing.JTextField txtStatusRate;
    private javax.swing.JButton btnStatusRate;
    private javax.swing.JPanel panelBroadcastRate;
    private javax.swing.JPanel jPanel243;
    private javax.swing.JLabel jLabel168;
    private javax.swing.JTextField txtBroadcastRate;
    private javax.swing.JButton btnBroadcastRate;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JPanel jPanel208;
    private javax.swing.JLabel jLabel167;
    private javax.swing.JTextField txtBroadcastText;
    private javax.swing.JButton btnBroadcastText;
    private javax.swing.JPanel jPanel136;
    private javax.swing.JPanel jPanel179;
    private javax.swing.JPanel jPanel184;
    private javax.swing.JLabel jLabel169;
    private javax.swing.JTextField txtPHTWakeupDelay;
    private javax.swing.JLabel jLabel170;
    private javax.swing.JButton btnPHTWakeupDelay;
    private javax.swing.JPanel jPanel204;
    private javax.swing.JPanel jPanel104;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JTextField txtGenericCommand;
    private javax.swing.JButton btnGenericCommand;
    private javax.swing.JPanel jPanel205;
    private javax.swing.JPanel jPanel168;
    private javax.swing.JButton btnPHTCrash;
    private javax.swing.JButton btnHWACCrash;
    private javax.swing.JButton btnSyncTime;
    private javax.swing.JButton btnRequestAck;
    // End of variables declaration//GEN-END:variables
    /*------------------------------------------------------------------------*/
    /** Change the appearance of the button so that user knows that the
     *  function associated with this button is not known, but will be as soon
     *  as we receive telemetry information.
     *  @param button The swing button.                                       */
    /*------------------------------------------------------------------------*/
    public void showButtonInactive( JButton button ) {
    /*------------------------------------------------------------------------*/
     button.setIcon(new javax.swing.ImageIcon(getClass().getResource(LED_OFF)));
    }
    
    /*------------------------------------------------------------------------*/
    /** Change the appearance of the button so that user knows that the
     *  function associated with this button is "active" or "on".
     *  @param button The swing button.                                       */
    /*------------------------------------------------------------------------*/
    public void showButtonActiveON( JButton button ) {
    /*------------------------------------------------------------------------*/
     button.setIcon(
            new javax.swing.ImageIcon(getClass().getResource(LED_GREEN_ON)));
    }
    
    /*------------------------------------------------------------------------*/
    /** Change the appearance of the button so that user knows that the
     *  function associated with this button is "inactive" or "off".
     *  @param button The swing button.                                       */
    /*------------------------------------------------------------------------*/
    public void showButtonActiveOFF( JButton button ) {
    /*------------------------------------------------------------------------*/
     button.setIcon(
            new javax.swing.ImageIcon(getClass().getResource(LED_RED_ON)));
    }
    
    /*------------------------------------------------------------------------*/
    /** Change the appearance of the button so that user knows that the
     *  state of the function associated with this button is unknown.
     *  @param button The swing button.                                       */
    /*------------------------------------------------------------------------*/
    public void showButtonNeutral( JButton button ) {
    /*------------------------------------------------------------------------*/
     button.setIcon(
       new javax.swing.ImageIcon(getClass().getResource(LED_WHITE)));
    }
}
