/*
 * panelIO_cmd.java
 *
 * Created on July 25, 2001, 5:08 PM
 */

package ca.gc.space.quicksat.ground.control;

import ca.gc.space.quicksat.ground.client.*;
import ca.gc.space.quicksat.ground.satellite.*;
import ca.gc.space.quicksat.ground.control.*;
import ca.gc.space.quicksat.ground.util.*;

/**
 *
 * @author  jfcusson
 */
public class PanelIO_cmd extends javax.swing.JPanel {
ServerLink  srvLnk               = null;
Satellite   sat                  = null;
Log         log                  = null;

    /** Creates new form panelIO_cmd */
    public PanelIO_cmd( Log log ) {
        initComponents();
        this.log = log;                
        if( this.log == null ) this.log = new Log();        
    }
    /*========================================================================*/    
    /** Set the object that is in charge of managing the link with the ground
     *  station server.
     *  @param srvLnk ServerLink used to communicate with the server.     */
    /*========================================================================*/
    public void setServerLink( ServerLink srvLnk ) {
    /*========================================================================*/    
        this.srvLnk = srvLnk;
    }
    
    /*========================================================================*/
    /** Set the object representing the satellite that we want to communicate
     *  with, and understanding the format of the commands.
     *  @param sat Satellite object representing our satellite.               */
    /*========================================================================*/
    public void setSatellite( Satellite sat ) {
    /*========================================================================*/    
        this.sat = sat;
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
              panelIO = new javax.swing.JPanel();
              jPanel198 = new javax.swing.JPanel();
              jPanel200 = new javax.swing.JPanel();
              jLabel107 = new javax.swing.JLabel();
              txtIOReadBytePort = new javax.swing.JTextField();
              btnIOReadByte = new javax.swing.JButton();
              jLabel108 = new javax.swing.JLabel();
              txtIOReadByteResult = new javax.swing.JTextField();
              jPanel201 = new javax.swing.JPanel();
              jLabel109 = new javax.swing.JLabel();
              txtIOReadWordPort = new javax.swing.JTextField();
              btnIOReadWord = new javax.swing.JButton();
              jLabel110 = new javax.swing.JLabel();
              txtIOReadWordResult = new javax.swing.JTextField();
              jPanel199 = new javax.swing.JPanel();
              jPanel202 = new javax.swing.JPanel();
              jLabel111 = new javax.swing.JLabel();
              txtIOWriteBytePort = new javax.swing.JTextField();
              jLabel112 = new javax.swing.JLabel();
              txtIOWriteByteValue = new javax.swing.JTextField();
              btnIOWriteByte = new javax.swing.JButton();
              jPanel203 = new javax.swing.JPanel();
              jLabel113 = new javax.swing.JLabel();
              txtIOWriteWordPort = new javax.swing.JTextField();
              jLabel114 = new javax.swing.JLabel();
              txtIOWriteWordValue = new javax.swing.JTextField();
              btnWriteWord = new javax.swing.JButton();
              
              setLayout(new java.awt.BorderLayout());
              
              panelIO.setLayout(new javax.swing.BoxLayout(panelIO, javax.swing.BoxLayout.X_AXIS));
              
              panelIO.setPreferredSize(new java.awt.Dimension(755, 200));
              panelIO.setMaximumSize(new java.awt.Dimension(2147483647, 120));
              jPanel198.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 2, 5));
              
              jPanel198.setBorder(new javax.swing.border.TitledBorder(""));
              jPanel198.setPreferredSize(new java.awt.Dimension(300, 200));
              jPanel198.setMinimumSize(new java.awt.Dimension(200, 86));
              jPanel198.setMaximumSize(new java.awt.Dimension(32767, 300));
              jPanel200.setBorder(new javax.swing.border.TitledBorder("Read Byte"));
              jLabel107.setText("I/O Port:");
              jPanel200.add(jLabel107);
              
              txtIOReadBytePort.setPreferredSize(new java.awt.Dimension(50, 20));
              jPanel200.add(txtIOReadBytePort);
              
              btnIOReadByte.setText("Read");
              btnIOReadByte.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                      btnIOReadByteActionPerformed(evt);
                  }
              });
              
              jPanel200.add(btnIOReadByte);
              
              jLabel108.setText("Result:");
              jPanel200.add(jLabel108);
              
              txtIOReadByteResult.setPreferredSize(new java.awt.Dimension(50, 20));
              jPanel200.add(txtIOReadByteResult);
              
              jPanel198.add(jPanel200);
            
            jPanel201.setBorder(new javax.swing.border.TitledBorder(new javax.swing.border.EtchedBorder(), "Read Word"));
              jLabel109.setText("I/O Port:");
              jPanel201.add(jLabel109);
              
              txtIOReadWordPort.setPreferredSize(new java.awt.Dimension(50, 20));
              jPanel201.add(txtIOReadWordPort);
              
              btnIOReadWord.setText("Read");
              btnIOReadWord.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                      btnIOReadWordActionPerformed(evt);
                  }
              });
              
              jPanel201.add(btnIOReadWord);
              
              jLabel110.setText("Result:");
              jPanel201.add(jLabel110);
              
              txtIOReadWordResult.setPreferredSize(new java.awt.Dimension(50, 20));
              jPanel201.add(txtIOReadWordResult);
              
              jPanel198.add(jPanel201);
            
            panelIO.add(jPanel198);
          
          jPanel199.setBorder(new javax.swing.border.TitledBorder(""));
              jPanel199.setPreferredSize(new java.awt.Dimension(300, 86));
              jPanel199.setMinimumSize(new java.awt.Dimension(300, 86));
              jPanel199.setMaximumSize(new java.awt.Dimension(32767, 300));
              jPanel202.setBorder(new javax.swing.border.TitledBorder(new javax.swing.border.EtchedBorder(), "Write Byte"));
              jLabel111.setText("I/O Port:");
              jPanel202.add(jLabel111);
              
              txtIOWriteBytePort.setPreferredSize(new java.awt.Dimension(50, 20));
              jPanel202.add(txtIOWriteBytePort);
              
              jLabel112.setText("Value:");
              jPanel202.add(jLabel112);
              
              txtIOWriteByteValue.setPreferredSize(new java.awt.Dimension(50, 20));
              jPanel202.add(txtIOWriteByteValue);
              
              btnIOWriteByte.setText("Write");
              btnIOWriteByte.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                      btnIOWriteByteActionPerformed(evt);
                  }
              });
              
              jPanel202.add(btnIOWriteByte);
              
              jPanel199.add(jPanel202);
            
            jPanel203.setBorder(new javax.swing.border.TitledBorder(new javax.swing.border.EtchedBorder(), "Write Word"));
              jLabel113.setText("I/O Port:");
              jPanel203.add(jLabel113);
              
              txtIOWriteWordPort.setPreferredSize(new java.awt.Dimension(50, 20));
              jPanel203.add(txtIOWriteWordPort);
              
              jLabel114.setText("Value:");
              jPanel203.add(jLabel114);
              
              txtIOWriteWordValue.setPreferredSize(new java.awt.Dimension(50, 20));
              jPanel203.add(txtIOWriteWordValue);
              
              btnWriteWord.setText("Write");
              btnWriteWord.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                      btnWriteWordActionPerformed(evt);
                  }
              });
              
              jPanel203.add(btnWriteWord);
              
              jPanel199.add(jPanel203);
            
            panelIO.add(jPanel199);
          
          add(panelIO, java.awt.BorderLayout.CENTER);
        
    }//GEN-END:initComponents

    private void btnIOWriteByteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIOWriteByteActionPerformed
        SatControl ctrl = sat.getControl();
        if( (ctrl==null) || (srvLnk==null) ) return;
        srvLnk.sendPacketToSpacecraft(
                  ctrl.messageToWriteIOPortByte(txtIOWriteBytePort.getText(),
                                                txtIOWriteByteValue.getText()));
    }//GEN-LAST:event_btnIOWriteByteActionPerformed

    private void btnIOReadByteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIOReadByteActionPerformed
        SatControl ctrl = sat.getControl();
        if( (ctrl==null) || (srvLnk==null) ) return;
        srvLnk.sendPacketToSpacecraft(
                  ctrl.messageToReadIOPortByte(txtIOReadBytePort.getText()));
    }//GEN-LAST:event_btnIOReadByteActionPerformed

    private void btnIOReadWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIOReadWordActionPerformed
        SatControl ctrl = sat.getControl();
        if( (ctrl==null) || (srvLnk==null) ) return;
        srvLnk.sendPacketToSpacecraft(
                  ctrl.messageToReadIOPortWord(txtIOReadWordPort.getText()));
    }//GEN-LAST:event_btnIOReadWordActionPerformed

    private void btnWriteWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWriteWordActionPerformed
        SatControl ctrl = sat.getControl();
        if( (ctrl==null) || (srvLnk==null) ) return;
        srvLnk.sendPacketToSpacecraft(
                  ctrl.messageToWriteIOPortWord(txtIOWriteWordPort.getText(),
                                                txtIOWriteWordValue.getText()));
    }//GEN-LAST:event_btnWriteWordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelIO;
    private javax.swing.JPanel jPanel198;
    private javax.swing.JPanel jPanel200;
    private javax.swing.JLabel jLabel107;
    private javax.swing.JTextField txtIOReadBytePort;
    private javax.swing.JButton btnIOReadByte;
    private javax.swing.JLabel jLabel108;
    private javax.swing.JTextField txtIOReadByteResult;
    private javax.swing.JPanel jPanel201;
    private javax.swing.JLabel jLabel109;
    private javax.swing.JTextField txtIOReadWordPort;
    private javax.swing.JButton btnIOReadWord;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JTextField txtIOReadWordResult;
    private javax.swing.JPanel jPanel199;
    private javax.swing.JPanel jPanel202;
    private javax.swing.JLabel jLabel111;
    private javax.swing.JTextField txtIOWriteBytePort;
    private javax.swing.JLabel jLabel112;
    private javax.swing.JTextField txtIOWriteByteValue;
    private javax.swing.JButton btnIOWriteByte;
    private javax.swing.JPanel jPanel203;
    private javax.swing.JLabel jLabel113;
    private javax.swing.JTextField txtIOWriteWordPort;
    private javax.swing.JLabel jLabel114;
    private javax.swing.JTextField txtIOWriteWordValue;
    private javax.swing.JButton btnWriteWord;
    // End of variables declaration//GEN-END:variables

}
