/*
 * panelPayload_cmd.java
 *
 * Created on July 25, 2001, 5:03 PM
 */

package ca.gc.space.quicksat.ground.control;

import javax.swing.*;
import ca.gc.space.quicksat.ground.client.*;
import ca.gc.space.quicksat.ground.satellite.*;
import ca.gc.space.quicksat.ground.control.*;
import ca.gc.space.quicksat.ground.util.*;

/**
 *
 * @author  jfcusson
 */
public class PanelPayload_cmd extends javax.swing.JPanel {
ServerLink  srvLnk               = null;
Satellite   sat                  = null;
Log         log                  = null;
private final String LED_OFF="/ca/gc/space/quicksat/ground/images/led_off.gif";
private final String LED_GREEN_ON="/ca/gc/space/quicksat/ground/images/led_green_on.gif";
private final String LED_RED_ON="/ca/gc/space/quicksat/ground/images/led_red_on.gif";
private final String LED_WHITE="/ca/gc/space/quicksat/ground/images/led_white.gif";
    
    /** Creates new form panelPayload_cmd */
    public PanelPayload_cmd( Log log ) {
        initComponents();
        this.log = log;                
        if( this.log == null ) this.log = new Log();
    }
    /*========================================================================*/    
    /** Set the object that is in charge of managing the link with the ground
     *  station server.
     *  @param srvLnk ServerLink used to communicate with the server.     */
    /*========================================================================*/
    public void setServerLink( ServerLink srvLnk ) {
    /*========================================================================*/    
        this.srvLnk = srvLnk;
    }
    
    /*========================================================================*/
    /** Set the object representing the satellite that we want to communicate
     *  with, and understanding the format of the commands.
     *  @param sat Satellite object representing our satellite.               */
    /*========================================================================*/
    public void setSatellite( Satellite sat ) {
    /*========================================================================*/    
        this.sat = sat;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
            panelPayloads = new javax.swing.JPanel();
            jPanel213 = new javax.swing.JPanel();
            jLabel157 = new javax.swing.JLabel();
            lblPayloadCommandMode = new javax.swing.JLabel();
            jPanel241 = new javax.swing.JPanel();
            btnPayloadON = new javax.swing.JButton();
            btnPayloadOFF = new javax.swing.JButton();
            jPanel214 = new javax.swing.JPanel();
            jLabel162 = new javax.swing.JLabel();
            jLabel156 = new javax.swing.JLabel();
            jPanel240 = new javax.swing.JPanel();
            jPanel215 = new javax.swing.JPanel();
            jPanel217 = new javax.swing.JPanel();
            jLabel126 = new javax.swing.JLabel();
            btnPayload1Activate = new javax.swing.JButton();
            btnPayload1Deactivate = new javax.swing.JButton();
            jPanel218 = new javax.swing.JPanel();
            jLabel127 = new javax.swing.JLabel();
            btnPayload2Activate = new javax.swing.JButton();
            btnPayload2Deactivate = new javax.swing.JButton();
            jPanel219 = new javax.swing.JPanel();
            jLabel128 = new javax.swing.JLabel();
            btnPayload3Activate = new javax.swing.JButton();
            btnPayload3Deactivate = new javax.swing.JButton();
            jPanel220 = new javax.swing.JPanel();
            jLabel129 = new javax.swing.JLabel();
            btnPayload4Activate = new javax.swing.JButton();
            btnPayload4Deactivate = new javax.swing.JButton();
            jPanel216 = new javax.swing.JPanel();
            jPanel221 = new javax.swing.JPanel();
            jLabel130 = new javax.swing.JLabel();
            btnPayload5Activate = new javax.swing.JButton();
            btnPayload5Deactivate = new javax.swing.JButton();
            jPanel222 = new javax.swing.JPanel();
            jLabel131 = new javax.swing.JLabel();
            btnPayload6Activate = new javax.swing.JButton();
            btnPayload6Deactivate = new javax.swing.JButton();
            jPanel223 = new javax.swing.JPanel();
            jLabel132 = new javax.swing.JLabel();
            btnPayload7Activate = new javax.swing.JButton();
            btnPayload7Deactivate = new javax.swing.JButton();
            jPanel224 = new javax.swing.JPanel();
            jLabel133 = new javax.swing.JLabel();
            btnPayload8Activate = new javax.swing.JButton();
            btnPayload8Deactivate = new javax.swing.JButton();
            
            setLayout(new java.awt.BorderLayout());
            
            jPanel213.setLayout(new javax.swing.BoxLayout(jPanel213, javax.swing.BoxLayout.Y_AXIS));
            
            jPanel213.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
            jLabel157.setText("  PAYLOAD POWER  ");
            jLabel157.setForeground(java.awt.Color.yellow);
            jLabel157.setBackground(java.awt.Color.blue);
            jLabel157.setFont(new java.awt.Font("Arial Black", 0, 14));
            jLabel157.setAlignmentX(0.5F);
            jLabel157.setMaximumSize(new java.awt.Dimension(2000, 21));
            jLabel157.setOpaque(true);
            jPanel213.add(jLabel157);
            
            lblPayloadCommandMode.setText("Prime Commands");
            lblPayloadCommandMode.setForeground(java.awt.Color.yellow);
            lblPayloadCommandMode.setBackground(java.awt.Color.blue);
            lblPayloadCommandMode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            lblPayloadCommandMode.setFont(new java.awt.Font("Verdana", 2, 12));
            lblPayloadCommandMode.setAlignmentX(0.5F);
            lblPayloadCommandMode.setMaximumSize(new java.awt.Dimension(1000, 21));
            lblPayloadCommandMode.setOpaque(true);
            jPanel213.add(lblPayloadCommandMode);
            
            btnPayloadON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
              btnPayloadON.setText("ON");
              btnPayloadON.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                      btnPayloadONActionPerformed(evt);
                  }
              });
              
              jPanel241.add(btnPayloadON);
              
              btnPayloadOFF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
              btnPayloadOFF.setText("OFF");
              btnPayloadOFF.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                      btnPayloadOFFActionPerformed(evt);
                  }
              });
              
              jPanel241.add(btnPayloadOFF);
              
              jPanel213.add(jPanel241);
            
            panelPayloads.add(jPanel213);
          
          jPanel214.setLayout(new javax.swing.BoxLayout(jPanel214, javax.swing.BoxLayout.Y_AXIS));
            
            jPanel214.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
            jLabel162.setText("  PAYLOAD COMMANDS  ");
            jLabel162.setForeground(java.awt.Color.yellow);
            jLabel162.setBackground(java.awt.Color.blue);
            jLabel162.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel162.setFont(new java.awt.Font("Arial Black", 0, 14));
            jLabel162.setAlignmentX(0.5F);
            jLabel162.setMaximumSize(new java.awt.Dimension(2000, 21));
            jLabel162.setOpaque(true);
            jPanel214.add(jLabel162);
            
            jLabel156.setText(" NOTE: On the FLATSAT, indicator's logic is reversed (OFF = LED ON) ");
            jLabel156.setForeground(java.awt.Color.yellow);
            jLabel156.setBackground(java.awt.Color.blue);
            jLabel156.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel156.setFont(new java.awt.Font("Verdana", 2, 12));
            jLabel156.setAlignmentX(0.5F);
            jLabel156.setMaximumSize(new java.awt.Dimension(2000, 21));
            jLabel156.setOpaque(true);
            jPanel214.add(jLabel156);
            
            jPanel215.setLayout(new javax.swing.BoxLayout(jPanel215, javax.swing.BoxLayout.Y_AXIS));
                  
                  jPanel215.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                  jPanel217.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                  jLabel126.setText("  1  ");
                  jLabel126.setForeground(java.awt.Color.white);
                  jLabel126.setBackground(java.awt.Color.darkGray);
                  jLabel126.setFont(new java.awt.Font("Arial Black", 0, 14));
                  jLabel126.setOpaque(true);
                  jPanel217.add(jLabel126);
                  
                  btnPayload1Activate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                  btnPayload1Activate.setText("ON");
                  btnPayload1Activate.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnPayload1ActivateActionPerformed(evt);
                      }
                  });
                  
                  jPanel217.add(btnPayload1Activate);
                  
                  btnPayload1Deactivate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                  btnPayload1Deactivate.setText("OFF");
                  btnPayload1Deactivate.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnPayload1DeactivateActionPerformed(evt);
                      }
                  });
                  
                  jPanel217.add(btnPayload1Deactivate);
                  
                  jPanel215.add(jPanel217);
                
                jPanel218.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                  jLabel127.setText("  2  ");
                  jLabel127.setForeground(java.awt.Color.white);
                  jLabel127.setBackground(java.awt.Color.darkGray);
                  jLabel127.setFont(new java.awt.Font("Arial Black", 0, 14));
                  jLabel127.setOpaque(true);
                  jPanel218.add(jLabel127);
                  
                  btnPayload2Activate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                  btnPayload2Activate.setText("ON");
                  btnPayload2Activate.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnPayload2ActivateActionPerformed(evt);
                      }
                  });
                  
                  jPanel218.add(btnPayload2Activate);
                  
                  btnPayload2Deactivate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                  btnPayload2Deactivate.setText("OFF");
                  btnPayload2Deactivate.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnPayload2DeactivateActionPerformed(evt);
                      }
                  });
                  
                  jPanel218.add(btnPayload2Deactivate);
                  
                  jPanel215.add(jPanel218);
                
                jPanel219.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                  jLabel128.setText("  3  ");
                  jLabel128.setForeground(java.awt.Color.white);
                  jLabel128.setBackground(java.awt.Color.darkGray);
                  jLabel128.setFont(new java.awt.Font("Arial Black", 0, 14));
                  jLabel128.setOpaque(true);
                  jPanel219.add(jLabel128);
                  
                  btnPayload3Activate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                  btnPayload3Activate.setText("ON");
                  btnPayload3Activate.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnPayload3ActivateActionPerformed(evt);
                      }
                  });
                  
                  jPanel219.add(btnPayload3Activate);
                  
                  btnPayload3Deactivate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                  btnPayload3Deactivate.setText("OFF");
                  btnPayload3Deactivate.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnPayload3DeactivateActionPerformed(evt);
                      }
                  });
                  
                  jPanel219.add(btnPayload3Deactivate);
                  
                  jPanel215.add(jPanel219);
                
                jPanel220.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                  jLabel129.setText("  4  ");
                  jLabel129.setForeground(java.awt.Color.white);
                  jLabel129.setBackground(java.awt.Color.darkGray);
                  jLabel129.setFont(new java.awt.Font("Arial Black", 0, 14));
                  jLabel129.setOpaque(true);
                  jPanel220.add(jLabel129);
                  
                  btnPayload4Activate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                  btnPayload4Activate.setText("ON");
                  btnPayload4Activate.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnPayload4ActivateActionPerformed(evt);
                      }
                  });
                  
                  jPanel220.add(btnPayload4Activate);
                  
                  btnPayload4Deactivate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                  btnPayload4Deactivate.setText("OFF");
                  btnPayload4Deactivate.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnPayload4DeactivateActionPerformed(evt);
                      }
                  });
                  
                  jPanel220.add(btnPayload4Deactivate);
                  
                  jPanel215.add(jPanel220);
                
                jPanel240.add(jPanel215);
              
              jPanel216.setLayout(new javax.swing.BoxLayout(jPanel216, javax.swing.BoxLayout.Y_AXIS));
                  
                  jPanel216.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                  jPanel221.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                  jLabel130.setText("  5  ");
                  jLabel130.setForeground(java.awt.Color.white);
                  jLabel130.setBackground(java.awt.Color.darkGray);
                  jLabel130.setFont(new java.awt.Font("Arial Black", 0, 14));
                  jLabel130.setOpaque(true);
                  jPanel221.add(jLabel130);
                  
                  btnPayload5Activate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                  btnPayload5Activate.setText("ON");
                  btnPayload5Activate.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnPayload5ActivateActionPerformed(evt);
                      }
                  });
                  
                  jPanel221.add(btnPayload5Activate);
                  
                  btnPayload5Deactivate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                  btnPayload5Deactivate.setText("OFF");
                  btnPayload5Deactivate.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnPayload5DeactivateActionPerformed(evt);
                      }
                  });
                  
                  jPanel221.add(btnPayload5Deactivate);
                  
                  jPanel216.add(jPanel221);
                
                jPanel222.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                  jLabel131.setText("  6  ");
                  jLabel131.setForeground(java.awt.Color.white);
                  jLabel131.setBackground(java.awt.Color.darkGray);
                  jLabel131.setFont(new java.awt.Font("Arial Black", 0, 14));
                  jLabel131.setOpaque(true);
                  jPanel222.add(jLabel131);
                  
                  btnPayload6Activate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                  btnPayload6Activate.setText("ON");
                  btnPayload6Activate.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnPayload6ActivateActionPerformed(evt);
                      }
                  });
                  
                  jPanel222.add(btnPayload6Activate);
                  
                  btnPayload6Deactivate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                  btnPayload6Deactivate.setText("OFF");
                  btnPayload6Deactivate.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnPayload6DeactivateActionPerformed(evt);
                      }
                  });
                  
                  jPanel222.add(btnPayload6Deactivate);
                  
                  jPanel216.add(jPanel222);
                
                jPanel223.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                  jLabel132.setText("  7  ");
                  jLabel132.setForeground(java.awt.Color.white);
                  jLabel132.setBackground(java.awt.Color.darkGray);
                  jLabel132.setFont(new java.awt.Font("Arial Black", 0, 14));
                  jLabel132.setOpaque(true);
                  jPanel223.add(jLabel132);
                  
                  btnPayload7Activate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                  btnPayload7Activate.setText("ON");
                  btnPayload7Activate.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnPayload7ActivateActionPerformed(evt);
                      }
                  });
                  
                  jPanel223.add(btnPayload7Activate);
                  
                  btnPayload7Deactivate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                  btnPayload7Deactivate.setText("OFF");
                  btnPayload7Deactivate.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnPayload7DeactivateActionPerformed(evt);
                      }
                  });
                  
                  jPanel223.add(btnPayload7Deactivate);
                  
                  jPanel216.add(jPanel223);
                
                jPanel224.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                  jLabel133.setText("  8  ");
                  jLabel133.setForeground(java.awt.Color.white);
                  jLabel133.setBackground(java.awt.Color.darkGray);
                  jLabel133.setFont(new java.awt.Font("Arial Black", 0, 14));
                  jLabel133.setOpaque(true);
                  jPanel224.add(jLabel133);
                  
                  btnPayload8Activate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                  btnPayload8Activate.setText("ON");
                  btnPayload8Activate.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnPayload8ActivateActionPerformed(evt);
                      }
                  });
                  
                  jPanel224.add(btnPayload8Activate);
                  
                  btnPayload8Deactivate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                  btnPayload8Deactivate.setText("OFF");
                  btnPayload8Deactivate.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnPayload8DeactivateActionPerformed(evt);
                      }
                  });
                  
                  jPanel224.add(btnPayload8Deactivate);
                  
                  jPanel216.add(jPanel224);
                
                jPanel240.add(jPanel216);
              
              jPanel214.add(jPanel240);
            
            panelPayloads.add(jPanel214);
          
          add(panelPayloads, java.awt.BorderLayout.CENTER);
        
    }//GEN-END:initComponents

    private void btnPayload3DeactivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayload3DeactivateActionPerformed
      showButtonInactive( btnPayload3Activate );
      SatControl ctrl = sat.getControl();
      if( (ctrl==null) || (srvLnk==null) ) return;
      srvLnk.sendPacketToSpacecraft(ctrl.messageToDeactivatePayloadLine(3));
    }//GEN-LAST:event_btnPayload3DeactivateActionPerformed

    private void btnPayload3ActivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayload3ActivateActionPerformed
      showButtonInactive( btnPayload3Deactivate );
      SatControl ctrl = sat.getControl();
      if( (ctrl==null) || (srvLnk==null) ) return;
      srvLnk.sendPacketToSpacecraft(ctrl.messageToActivatePayloadLine(3));
    }//GEN-LAST:event_btnPayload3ActivateActionPerformed

    private void btnPayload2DeactivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayload2DeactivateActionPerformed
      showButtonInactive( btnPayload2Activate );
      SatControl ctrl = sat.getControl();
      if( (ctrl==null) || (srvLnk==null) ) return;
      srvLnk.sendPacketToSpacecraft(ctrl.messageToDeactivatePayloadLine(2));
    }//GEN-LAST:event_btnPayload2DeactivateActionPerformed

    private void btnPayload8ActivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayload8ActivateActionPerformed
      showButtonInactive( btnPayload8Deactivate );
      SatControl ctrl = sat.getControl();
      if( (ctrl==null) || (srvLnk==null) ) return;
      srvLnk.sendPacketToSpacecraft(ctrl.messageToActivatePayloadLine(8));
    }//GEN-LAST:event_btnPayload8ActivateActionPerformed

    private void btnPayload1DeactivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayload1DeactivateActionPerformed
      showButtonInactive( btnPayload1Activate );
      SatControl ctrl = sat.getControl();
      if( (ctrl==null) || (srvLnk==null) ) return;
      srvLnk.sendPacketToSpacecraft(ctrl.messageToDeactivatePayloadLine(1));
    }//GEN-LAST:event_btnPayload1DeactivateActionPerformed

    private void btnPayload1ActivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayload1ActivateActionPerformed
      showButtonInactive( btnPayload1Deactivate );
      SatControl ctrl = sat.getControl();
      if( (ctrl==null) || (srvLnk==null) ) return;
      srvLnk.sendPacketToSpacecraft(ctrl.messageToActivatePayloadLine(1));
    }//GEN-LAST:event_btnPayload1ActivateActionPerformed

    private void btnPayload6ActivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayload6ActivateActionPerformed
      showButtonInactive( btnPayload6Deactivate );
      SatControl ctrl = sat.getControl();
      if( (ctrl==null) || (srvLnk==null) ) return;
      srvLnk.sendPacketToSpacecraft(ctrl.messageToActivatePayloadLine(6));
    }//GEN-LAST:event_btnPayload6ActivateActionPerformed

    private void btnPayload8DeactivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayload8DeactivateActionPerformed
      showButtonInactive( btnPayload8Activate );
      SatControl ctrl = sat.getControl();
      if( (ctrl==null) || (srvLnk==null) ) return;
      srvLnk.sendPacketToSpacecraft(ctrl.messageToDeactivatePayloadLine(8));
    }//GEN-LAST:event_btnPayload8DeactivateActionPerformed

    private void btnPayload4ActivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayload4ActivateActionPerformed
      showButtonInactive( btnPayload4Deactivate );
      SatControl ctrl = sat.getControl();
      if( (ctrl==null) || (srvLnk==null) ) return;
      srvLnk.sendPacketToSpacecraft(ctrl.messageToActivatePayloadLine(4));
    }//GEN-LAST:event_btnPayload4ActivateActionPerformed

    private void btnPayloadOFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayloadOFFActionPerformed
      showButtonInactive( btnPayloadON );
      SatControl ctrl = sat.getControl();
      if( (ctrl==null) || (srvLnk==null) ) return;
      srvLnk.sendPacketToSpacecraft(ctrl.messageToTurnPayloadPowerOFF());        
    }//GEN-LAST:event_btnPayloadOFFActionPerformed

    private void btnPayload7DeactivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayload7DeactivateActionPerformed
      showButtonInactive( btnPayload7Activate );
      SatControl ctrl = sat.getControl();
      if( (ctrl==null) || (srvLnk==null) ) return;
      srvLnk.sendPacketToSpacecraft(ctrl.messageToDeactivatePayloadLine(7));
    }//GEN-LAST:event_btnPayload7DeactivateActionPerformed

    private void btnPayload6DeactivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayload6DeactivateActionPerformed
      showButtonInactive( btnPayload6Activate );
      SatControl ctrl = sat.getControl();
      if( (ctrl==null) || (srvLnk==null) ) return;
      srvLnk.sendPacketToSpacecraft(ctrl.messageToDeactivatePayloadLine(6));
    }//GEN-LAST:event_btnPayload6DeactivateActionPerformed

    private void btnPayload2ActivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayload2ActivateActionPerformed
      showButtonInactive( btnPayload2Deactivate );
      SatControl ctrl = sat.getControl();
      if( (ctrl==null) || (srvLnk==null) ) return;
      srvLnk.sendPacketToSpacecraft(ctrl.messageToActivatePayloadLine(2));
    }//GEN-LAST:event_btnPayload2ActivateActionPerformed

    private void btnPayload7ActivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayload7ActivateActionPerformed
      showButtonInactive( btnPayload7Deactivate );
      SatControl ctrl = sat.getControl();
      if( (ctrl==null) || (srvLnk==null) ) return;
      srvLnk.sendPacketToSpacecraft(ctrl.messageToActivatePayloadLine(7));
    }//GEN-LAST:event_btnPayload7ActivateActionPerformed

    private void btnPayload5DeactivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayload5DeactivateActionPerformed
      showButtonInactive( btnPayload5Activate );
      SatControl ctrl = sat.getControl();
      if( (ctrl==null) || (srvLnk==null) ) return;
      srvLnk.sendPacketToSpacecraft(ctrl.messageToDeactivatePayloadLine(5));
    }//GEN-LAST:event_btnPayload5DeactivateActionPerformed

    private void btnPayloadONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayloadONActionPerformed
      showButtonInactive( btnPayloadOFF );
      SatControl ctrl = sat.getControl();
      if( (ctrl==null) || (srvLnk==null) ) return;
      srvLnk.sendPacketToSpacecraft(ctrl.messageToTurnPayloadPowerON());
    }//GEN-LAST:event_btnPayloadONActionPerformed

    private void btnPayload4DeactivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayload4DeactivateActionPerformed
      showButtonInactive( btnPayload4Activate );
      SatControl ctrl = sat.getControl();
      if( (ctrl==null) || (srvLnk==null) ) return;
      srvLnk.sendPacketToSpacecraft(ctrl.messageToDeactivatePayloadLine(4));
    }//GEN-LAST:event_btnPayload4DeactivateActionPerformed

    private void btnPayload5ActivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayload5ActivateActionPerformed
      showButtonInactive( btnPayload5Deactivate );
      SatControl ctrl = sat.getControl();
      if( (ctrl==null) || (srvLnk==null) ) return;
      srvLnk.sendPacketToSpacecraft(ctrl.messageToActivatePayloadLine(5));
    }//GEN-LAST:event_btnPayload5ActivateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelPayloads;
    private javax.swing.JPanel jPanel213;
    private javax.swing.JLabel jLabel157;
    private javax.swing.JLabel lblPayloadCommandMode;
    private javax.swing.JPanel jPanel241;
    public javax.swing.JButton btnPayloadON;
    public javax.swing.JButton btnPayloadOFF;
    private javax.swing.JPanel jPanel214;
    private javax.swing.JLabel jLabel162;
    private javax.swing.JLabel jLabel156;
    private javax.swing.JPanel jPanel240;
    private javax.swing.JPanel jPanel215;
    private javax.swing.JPanel jPanel217;
    private javax.swing.JLabel jLabel126;
    public javax.swing.JButton btnPayload1Activate;
    public javax.swing.JButton btnPayload1Deactivate;
    private javax.swing.JPanel jPanel218;
    private javax.swing.JLabel jLabel127;
    public javax.swing.JButton btnPayload2Activate;
    public javax.swing.JButton btnPayload2Deactivate;
    private javax.swing.JPanel jPanel219;
    private javax.swing.JLabel jLabel128;
    public javax.swing.JButton btnPayload3Activate;
    public javax.swing.JButton btnPayload3Deactivate;
    private javax.swing.JPanel jPanel220;
    private javax.swing.JLabel jLabel129;
    public javax.swing.JButton btnPayload4Activate;
    public javax.swing.JButton btnPayload4Deactivate;
    private javax.swing.JPanel jPanel216;
    private javax.swing.JPanel jPanel221;
    private javax.swing.JLabel jLabel130;
    public javax.swing.JButton btnPayload5Activate;
    public javax.swing.JButton btnPayload5Deactivate;
    private javax.swing.JPanel jPanel222;
    private javax.swing.JLabel jLabel131;
    public javax.swing.JButton btnPayload6Activate;
    public javax.swing.JButton btnPayload6Deactivate;
    private javax.swing.JPanel jPanel223;
    private javax.swing.JLabel jLabel132;
    public javax.swing.JButton btnPayload7Activate;
    public javax.swing.JButton btnPayload7Deactivate;
    private javax.swing.JPanel jPanel224;
    private javax.swing.JLabel jLabel133;
    public javax.swing.JButton btnPayload8Activate;
    public javax.swing.JButton btnPayload8Deactivate;
    // End of variables declaration//GEN-END:variables
    /*------------------------------------------------------------------------*/
    /** Change the appearance of the button so that user knows that the
     *  function associated with this button is not known, but will be as soon
     *  as we receive telemetry information.
     *  @param button The swing button.                                       */
    /*------------------------------------------------------------------------*/
    public void showButtonInactive( JButton button ) {
    /*------------------------------------------------------------------------*/
     button.setIcon(
       new javax.swing.ImageIcon(
        getClass().getResource(LED_OFF)));
    }
    
    /*------------------------------------------------------------------------*/
    /** Change the appearance of the button so that user knows that the
     *  function associated with this button is "active" or "on".
     *  @param button The swing button.                                       */
    /*------------------------------------------------------------------------*/
    public void showButtonActiveON( JButton button ) {
    /*------------------------------------------------------------------------*/
     button.setIcon(
       new javax.swing.ImageIcon(
        getClass().getResource(LED_GREEN_ON)));
    }
    
    /*------------------------------------------------------------------------*/
    /** Change the appearance of the button so that user knows that the
     *  function associated with this button is "inactive" or "off".
     *  @param button The swing button.                                       */
    /*------------------------------------------------------------------------*/
    public void showButtonActiveOFF( JButton button ) {
    /*------------------------------------------------------------------------*/
     button.setIcon(
       new javax.swing.ImageIcon(
        getClass().getResource(LED_RED_ON)));
    }
    
    /*------------------------------------------------------------------------*/
    /** Change the appearance of the button so that user knows that the
     *  state of the function associated with this button is unknown.
     *  @param button The swing button.                                       */
    /*------------------------------------------------------------------------*/
    public void showButtonNeutral( JButton button ) {
    /*------------------------------------------------------------------------*/
     button.setIcon(
       new javax.swing.ImageIcon(
        getClass().getResource(LED_WHITE)));
    }
}
