/*
 * PanelPyros.java
 *
 * Created on July 25, 2001, 1:08 PM
 */

package ca.gc.space.quicksat.ground.control;

import javax.swing.*;
import ca.gc.space.quicksat.ground.client.*;
import ca.gc.space.quicksat.ground.satellite.*;
import ca.gc.space.quicksat.ground.control.*;
import ca.gc.space.quicksat.ground.util.*;

/**
 *
 * @author  jfcusson
 */
public class PanelPyros_cmd extends javax.swing.JPanel {
ServerLink  srvLnk               = null;
Satellite   sat                  = null;
Log         log                  = null;
private final String LED_OFF="/ca/gc/space/quicksat/ground/images/led_off.gif";
private final String LED_GREEN_ON="/ca/gc/space/quicksat/ground/images/led_green_on.gif";
private final String LED_RED_ON="/ca/gc/space/quicksat/ground/images/led_red_on.gif";
private final String LED_WHITE="/ca/gc/space/quicksat/ground/images/led_white.gif";

    
    /** Creates new form PanelPyros */
    public PanelPyros_cmd( Log log ) {
        initComponents();
        this.log = log;                
        if( this.log == null ) this.log = new Log();
    }
    /*========================================================================*/    
    /** Set the object that is in charge of managing the link with the ground
     *  station server.
     *  @param srvLnk ServerLink used to communicate with the server.     */
    /*========================================================================*/
    public void setServerLink( ServerLink srvLnk ) {
    /*========================================================================*/    
        this.srvLnk = srvLnk;
    }
    
    /*========================================================================*/
    /** Set the object representing the satellite that we want to communicate
     *  with, and understanding the format of the commands.
     *  @param sat Satellite object representing our satellite.               */
    /*========================================================================*/
    public void setSatellite( Satellite sat ) {
    /*========================================================================*/    
        this.sat = sat;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
                panelPyros = new javax.swing.JPanel();
                jPanel89 = new javax.swing.JPanel();
                jPanel90 = new javax.swing.JPanel();
                jPanel91 = new javax.swing.JPanel();
                btnPyrosEnable = new javax.swing.JButton();
                btnPyrosDisable = new javax.swing.JButton();
                panPyrosBank = new javax.swing.JPanel();
                jLabel27 = new javax.swing.JLabel();
                jPanel246 = new javax.swing.JPanel();
                btnPyrosON = new javax.swing.JButton();
                btnPyrosOFF = new javax.swing.JButton();
                jPanel93 = new javax.swing.JPanel();
                jPanel94 = new javax.swing.JPanel();
                jPanel96 = new javax.swing.JPanel();
                btnPyro1ON = new javax.swing.JButton();
                btnPyro1OFF = new javax.swing.JButton();
                jLabel37 = new javax.swing.JLabel();
                jPanel97 = new javax.swing.JPanel();
                btnPyro2ON = new javax.swing.JButton();
                btnPyro2OFF = new javax.swing.JButton();
                jLabel38 = new javax.swing.JLabel();
                jPanel98 = new javax.swing.JPanel();
                btnPyro3ON = new javax.swing.JButton();
                btnPyro3OFF = new javax.swing.JButton();
                jLabel39 = new javax.swing.JLabel();
                jPanel95 = new javax.swing.JPanel();
                jPanel101 = new javax.swing.JPanel();
                btnPyro4ON = new javax.swing.JButton();
                btnPyro4OFF = new javax.swing.JButton();
                jLabel40 = new javax.swing.JLabel();
                jPanel100 = new javax.swing.JPanel();
                btnPyro5ON = new javax.swing.JButton();
                btnPyro5OFF = new javax.swing.JButton();
                jLabel41 = new javax.swing.JLabel();
                jPanel102 = new javax.swing.JPanel();
                btnPyro6ON = new javax.swing.JButton();
                btnPyro6OFF = new javax.swing.JButton();
                jLabel42 = new javax.swing.JLabel();
                
                jPanel89.setLayout(new javax.swing.BoxLayout(jPanel89, javax.swing.BoxLayout.X_AXIS));
                
                jPanel89.setBorder(new javax.swing.border.TitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Black", 0, 12)));
                jPanel90.setLayout(new javax.swing.BoxLayout(jPanel90, javax.swing.BoxLayout.Y_AXIS));
                
                jPanel90.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                jPanel91.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));
                
                btnPyrosEnable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                btnPyrosEnable.setText("ENABLE");
                btnPyrosEnable.setPreferredSize(new java.awt.Dimension(110, 29));
                btnPyrosEnable.setMaximumSize(new java.awt.Dimension(1000, 29));
                btnPyrosEnable.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnPyrosMasterONActionPerformed(evt);
                    }
                });
                
                jPanel91.add(btnPyrosEnable);
                
                btnPyrosDisable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                btnPyrosDisable.setText("DISABLE");
                btnPyrosDisable.setPreferredSize(new java.awt.Dimension(110, 29));
                btnPyrosDisable.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnPyrosMasterOFFActionPerformed(evt);
                    }
                });
                
                jPanel91.add(btnPyrosDisable);
                
                jPanel90.add(jPanel91);
              
              panPyrosBank.setLayout(new javax.swing.BoxLayout(panPyrosBank, javax.swing.BoxLayout.Y_AXIS));
                
                panPyrosBank.setBorder(new javax.swing.border.TitledBorder("Power - Primary Commands"));
                jLabel27.setText("  NOT OPERATIONAL  ");
                jLabel27.setForeground(java.awt.Color.red);
                jLabel27.setBackground(java.awt.Color.pink);
                jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel27.setFont(new java.awt.Font("Verdana", 0, 14));
                jLabel27.setAlignmentX(0.5F);
                jLabel27.setMaximumSize(new java.awt.Dimension(1500, 21));
                jLabel27.setOpaque(true);
                panPyrosBank.add(jLabel27);
                
                btnPyrosON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                  btnPyrosON.setText("ON");
                  btnPyrosON.setPreferredSize(new java.awt.Dimension(99, 29));
                  btnPyrosON.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnPyrosONActionPerformed(evt);
                      }
                  });
                  
                  jPanel246.add(btnPyrosON);
                  
                  btnPyrosOFF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                  btnPyrosOFF.setText("OFF");
                  btnPyrosOFF.setPreferredSize(new java.awt.Dimension(99, 29));
                  btnPyrosOFF.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnPyrosOFFActionPerformed(evt);
                      }
                  });
                  
                  jPanel246.add(btnPyrosOFF);
                  
                  panPyrosBank.add(jPanel246);
                
                jPanel90.add(panPyrosBank);
              
              jPanel89.add(jPanel90);
            
            jPanel93.setLayout(new javax.swing.BoxLayout(jPanel93, javax.swing.BoxLayout.X_AXIS));
                  
                  jPanel93.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                  jPanel94.setLayout(new javax.swing.BoxLayout(jPanel94, javax.swing.BoxLayout.Y_AXIS));
                  
                  jPanel94.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                  jPanel96.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                  btnPyro1ON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                  btnPyro1ON.setFont(new java.awt.Font("Arial Narrow", 0, 10));
                  btnPyro1ON.setText("ON");
                  btnPyro1ON.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnPyro1ONActionPerformed(evt);
                      }
                  });
                  
                  jPanel96.add(btnPyro1ON);
                  
                  btnPyro1OFF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                  btnPyro1OFF.setFont(new java.awt.Font("Arial Narrow", 0, 10));
                  btnPyro1OFF.setText("OFF");
                  btnPyro1OFF.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnPyro1OFFActionPerformed(evt);
                      }
                  });
                  
                  jPanel96.add(btnPyro1OFF);
                  
                  jLabel37.setText(" 1 ");
                  jLabel37.setForeground(java.awt.Color.white);
                  jLabel37.setBackground(java.awt.Color.darkGray);
                  jLabel37.setFont(new java.awt.Font("Dialog", 1, 11));
                  jLabel37.setOpaque(true);
                  jPanel96.add(jLabel37);
                  
                  jPanel94.add(jPanel96);
                
                jPanel97.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                  btnPyro2ON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                  btnPyro2ON.setFont(new java.awt.Font("Arial Narrow", 0, 10));
                  btnPyro2ON.setText("ON");
                  btnPyro2ON.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnPyro2ONActionPerformed(evt);
                      }
                  });
                  
                  jPanel97.add(btnPyro2ON);
                  
                  btnPyro2OFF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                  btnPyro2OFF.setFont(new java.awt.Font("Arial Narrow", 0, 10));
                  btnPyro2OFF.setText("OFF");
                  btnPyro2OFF.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnPyro2OFFActionPerformed(evt);
                      }
                  });
                  
                  jPanel97.add(btnPyro2OFF);
                  
                  jLabel38.setText(" 2 ");
                  jLabel38.setForeground(java.awt.Color.white);
                  jLabel38.setBackground(java.awt.Color.darkGray);
                  jLabel38.setFont(new java.awt.Font("Dialog", 1, 11));
                  jLabel38.setOpaque(true);
                  jPanel97.add(jLabel38);
                  
                  jPanel94.add(jPanel97);
                
                jPanel98.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                  btnPyro3ON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                  btnPyro3ON.setFont(new java.awt.Font("Arial Narrow", 0, 10));
                  btnPyro3ON.setText("ON");
                  btnPyro3ON.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnPyro3ONActionPerformed(evt);
                      }
                  });
                  
                  jPanel98.add(btnPyro3ON);
                  
                  btnPyro3OFF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                  btnPyro3OFF.setFont(new java.awt.Font("Arial Narrow", 0, 10));
                  btnPyro3OFF.setText("OFF");
                  btnPyro3OFF.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnPyro3OFFActionPerformed(evt);
                      }
                  });
                  
                  jPanel98.add(btnPyro3OFF);
                  
                  jLabel39.setText(" 3 ");
                  jLabel39.setForeground(java.awt.Color.white);
                  jLabel39.setBackground(java.awt.Color.darkGray);
                  jLabel39.setFont(new java.awt.Font("Dialog", 1, 11));
                  jLabel39.setOpaque(true);
                  jPanel98.add(jLabel39);
                  
                  jPanel94.add(jPanel98);
                
                jPanel93.add(jPanel94);
              
              jPanel95.setLayout(new javax.swing.BoxLayout(jPanel95, javax.swing.BoxLayout.Y_AXIS));
                  
                  jPanel95.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                  jPanel101.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                  btnPyro4ON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                  btnPyro4ON.setFont(new java.awt.Font("Arial Narrow", 0, 10));
                  btnPyro4ON.setText("ON");
                  btnPyro4ON.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnPyro4ONActionPerformed(evt);
                      }
                  });
                  
                  jPanel101.add(btnPyro4ON);
                  
                  btnPyro4OFF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                  btnPyro4OFF.setFont(new java.awt.Font("Arial Narrow", 0, 10));
                  btnPyro4OFF.setText("OFF");
                  btnPyro4OFF.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnPyro4OFFActionPerformed(evt);
                      }
                  });
                  
                  jPanel101.add(btnPyro4OFF);
                  
                  jLabel40.setText(" 4 ");
                  jLabel40.setForeground(java.awt.Color.white);
                  jLabel40.setBackground(java.awt.Color.darkGray);
                  jLabel40.setFont(new java.awt.Font("Dialog", 1, 11));
                  jLabel40.setOpaque(true);
                  jPanel101.add(jLabel40);
                  
                  jPanel95.add(jPanel101);
                
                jPanel100.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                  btnPyro5ON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                  btnPyro5ON.setFont(new java.awt.Font("Arial Narrow", 0, 10));
                  btnPyro5ON.setText("ON");
                  btnPyro5ON.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnPyro5ONActionPerformed(evt);
                      }
                  });
                  
                  jPanel100.add(btnPyro5ON);
                  
                  btnPyro5OFF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                  btnPyro5OFF.setFont(new java.awt.Font("Arial Narrow", 0, 10));
                  btnPyro5OFF.setText("OFF");
                  btnPyro5OFF.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnPyro5OFFActionPerformed(evt);
                      }
                  });
                  
                  jPanel100.add(btnPyro5OFF);
                  
                  jLabel41.setText(" 5 ");
                  jLabel41.setForeground(java.awt.Color.white);
                  jLabel41.setBackground(java.awt.Color.darkGray);
                  jLabel41.setFont(new java.awt.Font("Dialog", 1, 11));
                  jLabel41.setOpaque(true);
                  jPanel100.add(jLabel41);
                  
                  jPanel95.add(jPanel100);
                
                jPanel102.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                  btnPyro6ON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                  btnPyro6ON.setFont(new java.awt.Font("Arial Narrow", 0, 10));
                  btnPyro6ON.setText("ON");
                  btnPyro6ON.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnPyro6ONActionPerformed(evt);
                      }
                  });
                  
                  jPanel102.add(btnPyro6ON);
                  
                  btnPyro6OFF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                  btnPyro6OFF.setFont(new java.awt.Font("Arial Narrow", 0, 10));
                  btnPyro6OFF.setText("OFF");
                  btnPyro6OFF.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnPyro6OFFActionPerformed(evt);
                      }
                  });
                  
                  jPanel102.add(btnPyro6OFF);
                  
                  jLabel42.setText(" 6 ");
                  jLabel42.setForeground(java.awt.Color.white);
                  jLabel42.setBackground(java.awt.Color.darkGray);
                  jLabel42.setFont(new java.awt.Font("Dialog", 1, 11));
                  jLabel42.setOpaque(true);
                  jPanel102.add(jLabel42);
                  
                  jPanel95.add(jPanel102);
                
                jPanel93.add(jPanel95);
              
              jPanel89.add(jPanel93);
            
            panelPyros.add(jPanel89);
          
          add(panelPyros);
        
    }//GEN-END:initComponents

    private void btnPyrosOFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPyrosOFFActionPerformed
      showButtonInactive( btnPyrosON );
      SatControl ctrl = sat.getControl();
      if( (ctrl==null) || (srvLnk==null) ) return;
      srvLnk.sendPacketToSpacecraft(ctrl.messageToTurnPyrosPowerOFF());  
    }//GEN-LAST:event_btnPyrosOFFActionPerformed

    private void btnPyrosONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPyrosONActionPerformed
      showButtonInactive( btnPyrosOFF );
      SatControl ctrl = sat.getControl();
      if( (ctrl==null) || (srvLnk==null) ) return;
      srvLnk.sendPacketToSpacecraft(ctrl.messageToTurnPyrosPowerON());
    }//GEN-LAST:event_btnPyrosONActionPerformed

    private void btnPyro1OFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPyro1OFFActionPerformed
      showButtonInactive( btnPyro1ON );
      SatControl ctrl = sat.getControl();
      if( (ctrl==null) || (srvLnk==null) ) return;
      srvLnk.sendPacketToSpacecraft(ctrl.messageToDeactivatePyro(1));
    }//GEN-LAST:event_btnPyro1OFFActionPerformed

    private void btnPyro6OFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPyro6OFFActionPerformed
      showButtonInactive( btnPyro6ON );
      SatControl ctrl = sat.getControl();
      if( (ctrl==null) || (srvLnk==null) ) return;
      srvLnk.sendPacketToSpacecraft(ctrl.messageToDeactivatePyro(6));
    }//GEN-LAST:event_btnPyro6OFFActionPerformed

    private void btnPyro5OFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPyro5OFFActionPerformed
      showButtonInactive( btnPyro5ON );
      SatControl ctrl = sat.getControl();
      if( (ctrl==null) || (srvLnk==null) ) return;
      srvLnk.sendPacketToSpacecraft(ctrl.messageToDeactivatePyro(5));
    }//GEN-LAST:event_btnPyro5OFFActionPerformed

    private void btnPyro3ONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPyro3ONActionPerformed
      showButtonInactive( btnPyro3OFF );
      SatControl ctrl = sat.getControl();
      if( (ctrl==null) || (srvLnk==null) ) return;
      srvLnk.sendPacketToSpacecraft(ctrl.messageToActivatePyro(3));
    }//GEN-LAST:event_btnPyro3ONActionPerformed

    private void btnPyro4ONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPyro4ONActionPerformed
      showButtonInactive( btnPyro4OFF );
      SatControl ctrl = sat.getControl();
      if( (ctrl==null) || (srvLnk==null) ) return;
      srvLnk.sendPacketToSpacecraft(ctrl.messageToActivatePyro(4));
    }//GEN-LAST:event_btnPyro4ONActionPerformed

    private void btnPyro4OFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPyro4OFFActionPerformed
      showButtonInactive( btnPyro4ON );
      SatControl ctrl = sat.getControl();
      if( (ctrl==null) || (srvLnk==null) ) return;
      srvLnk.sendPacketToSpacecraft(ctrl.messageToDeactivatePyro(4));
    }//GEN-LAST:event_btnPyro4OFFActionPerformed

    private void btnPyro3OFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPyro3OFFActionPerformed
      showButtonInactive( btnPyro3ON );
      SatControl ctrl = sat.getControl();
      if( (ctrl==null) || (srvLnk==null) ) return;
      srvLnk.sendPacketToSpacecraft(ctrl.messageToDeactivatePyro(3));
    }//GEN-LAST:event_btnPyro3OFFActionPerformed

    private void btnPyrosMasterOFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPyrosMasterOFFActionPerformed
      showButtonInactive( btnPyrosEnable );
      SatControl ctrl = sat.getControl();
      if( (ctrl==null) || (srvLnk==null) ) return;
      srvLnk.sendPacketToSpacecraft(ctrl.messageToDisablePyros());
    }//GEN-LAST:event_btnPyrosMasterOFFActionPerformed

    private void btnPyro1ONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPyro1ONActionPerformed
      showButtonInactive( btnPyro1OFF );
      SatControl ctrl = sat.getControl();
      if( (ctrl==null) || (srvLnk==null) ) return;
      srvLnk.sendPacketToSpacecraft(ctrl.messageToActivatePyro(1));
    }//GEN-LAST:event_btnPyro1ONActionPerformed

    private void btnPyro5ONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPyro5ONActionPerformed
      showButtonInactive( btnPyro5OFF );
      SatControl ctrl = sat.getControl();
      if( (ctrl==null) || (srvLnk==null) ) return;
      srvLnk.sendPacketToSpacecraft(ctrl.messageToActivatePyro(5));
    }//GEN-LAST:event_btnPyro5ONActionPerformed

    private void btnPyro2OFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPyro2OFFActionPerformed
      showButtonInactive( btnPyro2ON );
      SatControl ctrl = sat.getControl();
      if( (ctrl==null) || (srvLnk==null) ) return;
      srvLnk.sendPacketToSpacecraft(ctrl.messageToDeactivatePyro(2));
    }//GEN-LAST:event_btnPyro2OFFActionPerformed

    private void btnPyro2ONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPyro2ONActionPerformed
      showButtonInactive( btnPyro2OFF );
      SatControl ctrl = sat.getControl();
      if( (ctrl==null) || (srvLnk==null) ) return;
      srvLnk.sendPacketToSpacecraft(ctrl.messageToActivatePyro(2));
    }//GEN-LAST:event_btnPyro2ONActionPerformed

    private void btnPyro6ONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPyro6ONActionPerformed
      showButtonInactive( btnPyro6OFF );
      SatControl ctrl = sat.getControl();
      if( (ctrl==null) || (srvLnk==null) ) return;
      srvLnk.sendPacketToSpacecraft(ctrl.messageToActivatePyro(6));
    }//GEN-LAST:event_btnPyro6ONActionPerformed

    private void btnPyrosMasterONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPyrosMasterONActionPerformed
      showButtonInactive( btnPyrosDisable );
      SatControl ctrl = sat.getControl();
      if( (ctrl==null) || (srvLnk==null) ) return;
      srvLnk.sendPacketToSpacecraft(ctrl.messageToEnablePyros());
    }//GEN-LAST:event_btnPyrosMasterONActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelPyros;
    private javax.swing.JPanel jPanel89;
    private javax.swing.JPanel jPanel90;
    private javax.swing.JPanel jPanel91;
    public javax.swing.JButton btnPyrosEnable;
    public javax.swing.JButton btnPyrosDisable;
    private javax.swing.JPanel panPyrosBank;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel246;
    public javax.swing.JButton btnPyrosON;
    public javax.swing.JButton btnPyrosOFF;
    private javax.swing.JPanel jPanel93;
    private javax.swing.JPanel jPanel94;
    private javax.swing.JPanel jPanel96;
    public javax.swing.JButton btnPyro1ON;
    public javax.swing.JButton btnPyro1OFF;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JPanel jPanel97;
    public javax.swing.JButton btnPyro2ON;
    public javax.swing.JButton btnPyro2OFF;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JPanel jPanel98;
    public javax.swing.JButton btnPyro3ON;
    public javax.swing.JButton btnPyro3OFF;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JPanel jPanel95;
    private javax.swing.JPanel jPanel101;
    public javax.swing.JButton btnPyro4ON;
    public javax.swing.JButton btnPyro4OFF;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JPanel jPanel100;
    public javax.swing.JButton btnPyro5ON;
    public javax.swing.JButton btnPyro5OFF;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JPanel jPanel102;
    public javax.swing.JButton btnPyro6ON;
    public javax.swing.JButton btnPyro6OFF;
    private javax.swing.JLabel jLabel42;
    // End of variables declaration//GEN-END:variables
    /*------------------------------------------------------------------------*/
    /** Change the appearance of the button so that user knows that the
     *  function associated with this button is not known, but will be as soon
     *  as we receive telemetry information.
     *  @param button The swing button.                                       */
    /*------------------------------------------------------------------------*/
    public void showButtonInactive( JButton button ) {
    /*------------------------------------------------------------------------*/
     button.setIcon(
       new javax.swing.ImageIcon(
        getClass().getResource(LED_OFF)));
    }
    
    /*------------------------------------------------------------------------*/
    /** Change the appearance of the button so that user knows that the
     *  function associated with this button is "active" or "on".
     *  @param button The swing button.                                       */
    /*------------------------------------------------------------------------*/
    public void showButtonActiveON( JButton button ) {
    /*------------------------------------------------------------------------*/
     button.setIcon(
       new javax.swing.ImageIcon(
        getClass().getResource(LED_GREEN_ON)));
    }
    
    /*------------------------------------------------------------------------*/
    /** Change the appearance of the button so that user knows that the
     *  function associated with this button is "inactive" or "off".
     *  @param button The swing button.                                       */
    /*------------------------------------------------------------------------*/
    public void showButtonActiveOFF( JButton button ) {
    /*------------------------------------------------------------------------*/
     button.setIcon(
       new javax.swing.ImageIcon(
        getClass().getResource(LED_RED_ON)));
    }
    
    /*------------------------------------------------------------------------*/
    /** Change the appearance of the button so that user knows that the
     *  state of the function associated with this button is unknown.
     *  @param button The swing button.                                       */
    /*------------------------------------------------------------------------*/
    public void showButtonNeutral( JButton button ) {
    /*------------------------------------------------------------------------*/
     button.setIcon(
       new javax.swing.ImageIcon(
        getClass().getResource(LED_WHITE)));
    }  
}
