/*
 * panelModems_cmd.java
 *
 * Created on July 25, 2001, 5:05 PM
 */

package ca.gc.space.quicksat.ground.control;

import javax.swing.*;
import ca.gc.space.quicksat.ground.client.*;
import ca.gc.space.quicksat.ground.satellite.*;
import ca.gc.space.quicksat.ground.control.*;
import ca.gc.space.quicksat.ground.util.*;
import ca.gc.space.quicksat.ground.radio.*;

/**
 *
 * @author  jfcusson
 */
public class PanelModems_cmd extends javax.swing.JPanel {
ServerLink  srvLnk               = null;
Satellite   sat                  = null;
Log         log                  = null;
private final String LED_OFF="/ca/gc/space/quicksat/ground/images/led_off.gif";
private final String LED_GREEN_ON="/ca/gc/space/quicksat/ground/images/led_green_on.gif";
private final String LED_RED_ON="/ca/gc/space/quicksat/ground/images/led_red_on.gif";
private final String LED_WHITE="/ca/gc/space/quicksat/ground/images/led_white.gif";
    
    /** Creates new form panelModems_cmd */
    public PanelModems_cmd( Log log) {
        initComponents();
        this.log = log;                
        if( this.log == null ) this.log = new Log();
    }
    /*========================================================================*/    
    /** Set the object that is in charge of managing the link with the ground
     *  station server.
     *  @param srvLnk ServerLink used to communicate with the server.     */
    /*========================================================================*/
    public void setServerLink( ServerLink srvLnk ) {
    /*========================================================================*/    
        this.srvLnk = srvLnk;
    }
    
    /*========================================================================*/
    /** Set the object representing the satellite that we want to communicate
     *  with, and understanding the format of the commands.
     *  @param sat Satellite object representing our satellite.               */
    /*========================================================================*/
    public void setSatellite( Satellite sat ) {
    /*========================================================================*/    
        this.sat = sat;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
            panelModems = new javax.swing.JPanel();
            panelModemA = new javax.swing.JPanel();
            jLabel97 = new javax.swing.JLabel();
            panelModemACommands = new javax.swing.JPanel();
            jPanel186 = new javax.swing.JPanel();
            jPanel180 = new javax.swing.JPanel();
            btnModemASourceAnalog = new javax.swing.JButton();
            btnModemASourceDigital = new javax.swing.JButton();
            jPanel182 = new javax.swing.JPanel();
            jLabel45 = new javax.swing.JLabel();
            listModemACTCSS = new javax.swing.JComboBox();
            btnModemACTCSS = new javax.swing.JButton();
            jPanel187 = new javax.swing.JPanel();
            jPanel183 = new javax.swing.JPanel();
            jLabel26 = new javax.swing.JLabel();
            txtModemAOffset = new javax.swing.JTextField();
            jLabel100 = new javax.swing.JLabel();
            slidModemAOffset = new javax.swing.JSlider();
            jLabel101 = new javax.swing.JLabel();
            btnModemAOffset = new javax.swing.JButton();
            chkModemAOffsetContinuous = new javax.swing.JCheckBox();
            jPanel181 = new javax.swing.JPanel();
            jLabel43 = new javax.swing.JLabel();
            txtModemADeviation = new javax.swing.JTextField();
            jLabel98 = new javax.swing.JLabel();
            slidModemADeviation = new javax.swing.JSlider();
            jLabel99 = new javax.swing.JLabel();
            btnModemADeviation = new javax.swing.JButton();
            chkModemADeviationContinuous = new javax.swing.JCheckBox();
            jPanel169 = new javax.swing.JPanel();
            jPanel242 = new javax.swing.JPanel();
            btnModemsInit = new javax.swing.JButton();
            jPanel176 = new javax.swing.JPanel();
            jLabel96 = new javax.swing.JLabel();
            jPanel209 = new javax.swing.JPanel();
            btnDigipeatON = new javax.swing.JButton();
            btnDigipeatOFF = new javax.swing.JButton();
            panelModemB = new javax.swing.JPanel();
            jLabel102 = new javax.swing.JLabel();
            jPanel170 = new javax.swing.JPanel();
            jPanel171 = new javax.swing.JPanel();
            jPanel172 = new javax.swing.JPanel();
            btnModemBSourceAnalog = new javax.swing.JButton();
            btnModemBSourceDigital = new javax.swing.JButton();
            jPanel173 = new javax.swing.JPanel();
            jLabel55 = new javax.swing.JLabel();
            listModemBCTCSS = new javax.swing.JComboBox();
            btnModemBCTCSS = new javax.swing.JButton();
            jPanel174 = new javax.swing.JPanel();
            jPanel177 = new javax.swing.JPanel();
            jLabel56 = new javax.swing.JLabel();
            txtModemBOffset = new javax.swing.JTextField();
            jLabel103 = new javax.swing.JLabel();
            slidModemBOffset = new javax.swing.JSlider();
            jLabel104 = new javax.swing.JLabel();
            btnModemBOffset = new javax.swing.JButton();
            chkModemBOffsetContinuous = new javax.swing.JCheckBox();
            jPanel178 = new javax.swing.JPanel();
            jLabel95 = new javax.swing.JLabel();
            txtModemBDeviation = new javax.swing.JTextField();
            jLabel105 = new javax.swing.JLabel();
            slidModemBDeviation = new javax.swing.JSlider();
            jLabel106 = new javax.swing.JLabel();
            btnModemBDeviation = new javax.swing.JButton();
            chkModemBDeviationContinuous = new javax.swing.JCheckBox();
            jPanel189 = new javax.swing.JPanel();
            jPanel190 = new javax.swing.JPanel();
            listModemBRate = new javax.swing.JComboBox();
            btnModemBRate = new javax.swing.JButton();
            jPanel191 = new javax.swing.JPanel();
            btnModemBScrambleActivate = new javax.swing.JButton();
            btnModemBScrambleDeactivate = new javax.swing.JButton();
            
            setLayout(new java.awt.BorderLayout());
            
            panelModems.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 5, 2));
            
            panelModems.setPreferredSize(new java.awt.Dimension(775, 150));
            panelModems.setMinimumSize(new java.awt.Dimension(600, 111));
            panelModemA.setLayout(new javax.swing.BoxLayout(panelModemA, javax.swing.BoxLayout.Y_AXIS));
            
            panelModemA.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
            panelModemA.setPreferredSize(new java.awt.Dimension(550, 75));
            jLabel97.setText("  MODEM A  ");
            jLabel97.setForeground(java.awt.Color.yellow);
            jLabel97.setBackground(java.awt.Color.blue);
            jLabel97.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel97.setFont(new java.awt.Font("Arial Black", 0, 14));
            jLabel97.setMinimumSize(new java.awt.Dimension(95, 10));
            jLabel97.setAlignmentX(0.5F);
            jLabel97.setMaximumSize(new java.awt.Dimension(1500, 21));
            jLabel97.setOpaque(true);
            panelModemA.add(jLabel97);
            
            panelModemACommands.setLayout(new javax.swing.BoxLayout(panelModemACommands, javax.swing.BoxLayout.X_AXIS));
                  
                  panelModemACommands.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                  jPanel186.setLayout(new javax.swing.BoxLayout(jPanel186, javax.swing.BoxLayout.Y_AXIS));
                  
                  jPanel186.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                  jPanel186.setMaximumSize(new java.awt.Dimension(220, 32767));
                  jPanel180.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));
                  
                  jPanel180.setMinimumSize(new java.awt.Dimension(100, 29));
                  btnModemASourceAnalog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                  btnModemASourceAnalog.setText("Analog");
                  btnModemASourceAnalog.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnModemASourceAnalogActionPerformed(evt);
                      }
                  });
                  
                  jPanel180.add(btnModemASourceAnalog);
                  
                  btnModemASourceDigital.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                  btnModemASourceDigital.setText("Digital");
                  btnModemASourceDigital.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnModemASourceDigitalActionPerformed(evt);
                      }
                  });
                  
                  jPanel180.add(btnModemASourceDigital);
                  
                  jPanel186.add(jPanel180);
                
                jPanel182.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));
                  
                  jPanel182.setPreferredSize(new java.awt.Dimension(150, 27));
                  jPanel182.setMinimumSize(new java.awt.Dimension(100, 27));
                  jLabel45.setText("CTCSS:");
                  jPanel182.add(jLabel45);
                  
                  listModemACTCSS.setPreferredSize(new java.awt.Dimension(100, 25));
                  listModemACTCSS.setMinimumSize(new java.awt.Dimension(100, 25));
                  jPanel182.add(listModemACTCSS);
                  
                  btnModemACTCSS.setText("SET");
                  btnModemACTCSS.setMargin(new java.awt.Insets(2, 5, 2, 5));
                  btnModemACTCSS.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnModemACTCSSActionPerformed(evt);
                      }
                  });
                  
                  jPanel182.add(btnModemACTCSS);
                  
                  jPanel186.add(jPanel182);
                
                panelModemACommands.add(jPanel186);
              
              jPanel187.setLayout(new javax.swing.BoxLayout(jPanel187, javax.swing.BoxLayout.Y_AXIS));
                  
                  jPanel187.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                  jPanel183.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 1));
                  
                  jPanel183.setPreferredSize(new java.awt.Dimension(300, 64));
                  jLabel26.setText("Offset:");
                  jPanel183.add(jLabel26);
                  
                  txtModemAOffset.setText(" ");
                  txtModemAOffset.setPreferredSize(new java.awt.Dimension(30, 20));
                  txtModemAOffset.setMinimumSize(new java.awt.Dimension(30, 20));
                  txtModemAOffset.addKeyListener(new java.awt.event.KeyAdapter() {
                      public void keyReleased(java.awt.event.KeyEvent evt) {
                          txtModemAOffsetKeyReleased(evt);
                      }
                  });
                  
                  jPanel183.add(txtModemAOffset);
                  
                  jLabel100.setText("0");
                  jPanel183.add(jLabel100);
                  
                  slidModemAOffset.setPaintTicks(true);
                  slidModemAOffset.setMajorTickSpacing(10);
                  slidModemAOffset.setMaximum(255);
                  slidModemAOffset.setValue(10);
                  slidModemAOffset.setPreferredSize(new java.awt.Dimension(125, 27));
                  slidModemAOffset.setMinimumSize(new java.awt.Dimension(200, 27));
                  txtModemAOffset.setText(""+slidModemAOffset.getValue());
                  slidModemAOffset.addChangeListener(new javax.swing.event.ChangeListener() {
                      public void stateChanged(javax.swing.event.ChangeEvent evt) {
                          slidModemAOffsetStateChanged(evt);
                      }
                  });
                  
                  jPanel183.add(slidModemAOffset);
                  
                  jLabel101.setText("255");
                  jPanel183.add(jLabel101);
                  
                  btnModemAOffset.setText("SET");
                  btnModemAOffset.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnModemAOffsetActionPerformed(evt);
                      }
                  });
                  
                  jPanel183.add(btnModemAOffset);
                  
                  chkModemAOffsetContinuous.setLabel("Cont.");
                  jPanel183.add(chkModemAOffsetContinuous);
                  
                  jPanel187.add(jPanel183);
                
                jPanel181.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 1));
                  
                  jPanel181.setPreferredSize(new java.awt.Dimension(300, 64));
                  jLabel43.setText("Deviation:");
                  jPanel181.add(jLabel43);
                  
                  txtModemADeviation.setText(" ");
                  txtModemADeviation.setPreferredSize(new java.awt.Dimension(30, 20));
                  txtModemADeviation.setMinimumSize(new java.awt.Dimension(30, 20));
                  txtModemADeviation.addKeyListener(new java.awt.event.KeyAdapter() {
                      public void keyReleased(java.awt.event.KeyEvent evt) {
                          txtModemADeviationKeyReleased(evt);
                      }
                  });
                  
                  jPanel181.add(txtModemADeviation);
                  
                  jLabel98.setText("0");
                  jPanel181.add(jLabel98);
                  
                  slidModemADeviation.setPaintTicks(true);
                  slidModemADeviation.setMajorTickSpacing(10);
                  slidModemADeviation.setMaximum(255);
                  slidModemADeviation.setValue(10);
                  slidModemADeviation.setPreferredSize(new java.awt.Dimension(125, 27));
                  txtModemADeviation.setText(""+slidModemADeviation.getValue());
                  slidModemADeviation.addChangeListener(new javax.swing.event.ChangeListener() {
                      public void stateChanged(javax.swing.event.ChangeEvent evt) {
                          slidModemADeviationStateChanged(evt);
                      }
                  });
                  
                  jPanel181.add(slidModemADeviation);
                  
                  jLabel99.setText("255");
                  jPanel181.add(jLabel99);
                  
                  btnModemADeviation.setText("SET");
                  btnModemADeviation.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnModemADeviationActionPerformed(evt);
                      }
                  });
                  
                  jPanel181.add(btnModemADeviation);
                  
                  chkModemADeviationContinuous.setLabel("Cont.");
                  jPanel181.add(chkModemADeviationContinuous);
                  
                  jPanel187.add(jPanel181);
                
                panelModemACommands.add(jPanel187);
              
              panelModemA.add(panelModemACommands);
            
            panelModems.add(panelModemA);
          
          jPanel169.setLayout(new javax.swing.BoxLayout(jPanel169, javax.swing.BoxLayout.Y_AXIS));
              
              jPanel169.setPreferredSize(new java.awt.Dimension(200, 76));
              jPanel242.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 2));
              
              btnModemsInit.setText("Init Modems");
              btnModemsInit.setAlignmentX(0.5F);
              btnModemsInit.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                      btnModemsInitActionPerformed(evt);
                  }
              });
              
              jPanel242.add(btnModemsInit);
              
              jPanel169.add(jPanel242);
            
            jPanel176.setLayout(new javax.swing.BoxLayout(jPanel176, javax.swing.BoxLayout.Y_AXIS));
              
              jPanel176.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
              jPanel176.setPreferredSize(new java.awt.Dimension(161, 45));
              jLabel96.setText("  DIGIPEAT  ");
              jLabel96.setForeground(java.awt.Color.yellow);
              jLabel96.setBackground(java.awt.Color.blue);
              jLabel96.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
              jLabel96.setFont(new java.awt.Font("Arial Black", 0, 14));
              jLabel96.setMinimumSize(new java.awt.Dimension(90, 10));
              jLabel96.setAlignmentX(0.5F);
              jLabel96.setMaximumSize(new java.awt.Dimension(1500, 21));
              jLabel96.setOpaque(true);
              jPanel176.add(jLabel96);
              
              jPanel209.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));
                
                jPanel209.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                jPanel209.setPreferredSize(new java.awt.Dimension(115, 32));
                btnDigipeatON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                btnDigipeatON.setFont(new java.awt.Font("Arial Narrow", 0, 10));
                btnDigipeatON.setText("ON");
                btnDigipeatON.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnDigipeatONActionPerformed(evt);
                    }
                });
                
                jPanel209.add(btnDigipeatON);
                
                btnDigipeatOFF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                btnDigipeatOFF.setFont(new java.awt.Font("Arial Narrow", 0, 10));
                btnDigipeatOFF.setText("OFF");
                btnDigipeatOFF.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnDigipeatOFFActionPerformed(evt);
                    }
                });
                
                jPanel209.add(btnDigipeatOFF);
                
                jPanel176.add(jPanel209);
              
              jPanel169.add(jPanel176);
            
            panelModems.add(jPanel169);
          
          panelModemB.setLayout(new javax.swing.BoxLayout(panelModemB, javax.swing.BoxLayout.Y_AXIS));
            
            panelModemB.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
            panelModemB.setPreferredSize(new java.awt.Dimension(775, 100));
            panelModemB.setMinimumSize(new java.awt.Dimension(628, 75));
            jLabel102.setText("  MODEM B  ");
            jLabel102.setForeground(java.awt.Color.yellow);
            jLabel102.setBackground(java.awt.Color.blue);
            jLabel102.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel102.setFont(new java.awt.Font("Arial Black", 0, 14));
            jLabel102.setMinimumSize(new java.awt.Dimension(95, 10));
            jLabel102.setAlignmentX(0.5F);
            jLabel102.setMaximumSize(new java.awt.Dimension(1500, 21));
            jLabel102.setOpaque(true);
            panelModemB.add(jLabel102);
            
            jPanel170.setLayout(new javax.swing.BoxLayout(jPanel170, javax.swing.BoxLayout.X_AXIS));
                  
                  jPanel170.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                  jPanel171.setLayout(new javax.swing.BoxLayout(jPanel171, javax.swing.BoxLayout.Y_AXIS));
                  
                  jPanel171.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                  jPanel171.setMaximumSize(new java.awt.Dimension(220, 32767));
                  btnModemBSourceAnalog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                  btnModemBSourceAnalog.setText("Analog");
                  btnModemBSourceAnalog.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnModemBSourceAnalogActionPerformed(evt);
                      }
                  });
                  
                  jPanel172.add(btnModemBSourceAnalog);
                  
                  btnModemBSourceDigital.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                  btnModemBSourceDigital.setText("Digital");
                  btnModemBSourceDigital.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnModemBSourceDigitalActionPerformed(evt);
                      }
                  });
                  
                  jPanel172.add(btnModemBSourceDigital);
                  
                  jPanel171.add(jPanel172);
                
                jLabel55.setText("CTCSS:");
                  jPanel173.add(jLabel55);
                  
                  listModemBCTCSS.setPreferredSize(new java.awt.Dimension(100, 25));
                  listModemBCTCSS.setMinimumSize(new java.awt.Dimension(100, 25));
                  jPanel173.add(listModemBCTCSS);
                  
                  btnModemBCTCSS.setText("SET");
                  btnModemBCTCSS.setMargin(new java.awt.Insets(2, 5, 2, 5));
                  btnModemBCTCSS.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnModemBCTCSSActionPerformed(evt);
                      }
                  });
                  
                  jPanel173.add(btnModemBCTCSS);
                  
                  jPanel171.add(jPanel173);
                
                jPanel170.add(jPanel171);
              
              jPanel174.setLayout(new javax.swing.BoxLayout(jPanel174, javax.swing.BoxLayout.Y_AXIS));
                  
                  jPanel174.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                  jPanel177.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
                  
                  jPanel177.setPreferredSize(new java.awt.Dimension(300, 64));
                  jLabel56.setText("Offset:");
                  jPanel177.add(jLabel56);
                  
                  txtModemBOffset.setText(" ");
                  txtModemBOffset.setPreferredSize(new java.awt.Dimension(30, 20));
                  txtModemBOffset.setMinimumSize(new java.awt.Dimension(30, 20));
                  txtModemBOffset.addKeyListener(new java.awt.event.KeyAdapter() {
                      public void keyReleased(java.awt.event.KeyEvent evt) {
                          txtModemBOffsetKeyReleased(evt);
                      }
                  });
                  
                  jPanel177.add(txtModemBOffset);
                  
                  jLabel103.setText("0");
                  jPanel177.add(jLabel103);
                  
                  slidModemBOffset.setPaintTicks(true);
                  slidModemBOffset.setMajorTickSpacing(10);
                  slidModemBOffset.setMaximum(255);
                  slidModemBOffset.setValue(10);
                  slidModemBOffset.setPreferredSize(new java.awt.Dimension(125, 27));
                  txtModemBOffset.setText(""+slidModemBOffset.getValue());
                  slidModemBOffset.addChangeListener(new javax.swing.event.ChangeListener() {
                      public void stateChanged(javax.swing.event.ChangeEvent evt) {
                          slidModemBOffsetStateChanged(evt);
                      }
                  });
                  
                  jPanel177.add(slidModemBOffset);
                  
                  jLabel104.setText("255");
                  jPanel177.add(jLabel104);
                  
                  btnModemBOffset.setText("SET");
                  btnModemBOffset.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnModemBOffsetActionPerformed(evt);
                      }
                  });
                  
                  jPanel177.add(btnModemBOffset);
                  
                  chkModemBOffsetContinuous.setLabel("Cont.");
                  jPanel177.add(chkModemBOffsetContinuous);
                  
                  jPanel174.add(jPanel177);
                
                jPanel178.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
                  
                  jPanel178.setPreferredSize(new java.awt.Dimension(450, 64));
                  jLabel95.setText("Deviation:");
                  jPanel178.add(jLabel95);
                  
                  txtModemBDeviation.setText(" ");
                  txtModemBDeviation.setPreferredSize(new java.awt.Dimension(30, 20));
                  txtModemBDeviation.setMinimumSize(new java.awt.Dimension(30, 20));
                  txtModemBDeviation.addKeyListener(new java.awt.event.KeyAdapter() {
                      public void keyReleased(java.awt.event.KeyEvent evt) {
                          txtModemBDeviationKeyReleased(evt);
                      }
                  });
                  
                  jPanel178.add(txtModemBDeviation);
                  
                  jLabel105.setText("0");
                  jPanel178.add(jLabel105);
                  
                  slidModemBDeviation.setPaintTicks(true);
                  slidModemBDeviation.setMajorTickSpacing(10);
                  slidModemBDeviation.setMaximum(255);
                  slidModemBDeviation.setValue(10);
                  slidModemBDeviation.setPreferredSize(new java.awt.Dimension(125, 27));
                  txtModemBDeviation.setText(""+slidModemBDeviation.getValue());
                  slidModemBDeviation.addChangeListener(new javax.swing.event.ChangeListener() {
                      public void stateChanged(javax.swing.event.ChangeEvent evt) {
                          slidModemBDeviationStateChanged(evt);
                      }
                  });
                  
                  jPanel178.add(slidModemBDeviation);
                  
                  jLabel106.setText("255");
                  jPanel178.add(jLabel106);
                  
                  btnModemBDeviation.setText("SET");
                  btnModemBDeviation.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnModemBDeviationActionPerformed(evt);
                      }
                  });
                  
                  jPanel178.add(btnModemBDeviation);
                  
                  chkModemBDeviationContinuous.setLabel("Cont.");
                  jPanel178.add(chkModemBDeviationContinuous);
                  
                  jPanel174.add(jPanel178);
                
                jPanel170.add(jPanel174);
              
              jPanel189.setLayout(new javax.swing.BoxLayout(jPanel189, javax.swing.BoxLayout.Y_AXIS));
                  
                  jPanel189.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                  jPanel190.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));
                  
                  listModemBRate.setPreferredSize(new java.awt.Dimension(100, 25));
                  listModemBRate.setMinimumSize(new java.awt.Dimension(60, 25));
                  jPanel190.add(listModemBRate);
                  
                  btnModemBRate.setText("SET");
                  btnModemBRate.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnModemBRateActionPerformed(evt);
                      }
                  });
                  
                  jPanel190.add(btnModemBRate);
                  
                  jPanel189.add(jPanel190);
                
                jPanel191.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 0));
                  
                  jPanel191.setBorder(new javax.swing.border.TitledBorder("Scramble"));
                  btnModemBScrambleActivate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                  btnModemBScrambleActivate.setText("ON");
                  btnModemBScrambleActivate.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnModemBScrambleActivateActionPerformed(evt);
                      }
                  });
                  
                  jPanel191.add(btnModemBScrambleActivate);
                  
                  btnModemBScrambleDeactivate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/led_white.gif")));
                  btnModemBScrambleDeactivate.setText("OFF");
                  btnModemBScrambleDeactivate.addActionListener(new java.awt.event.ActionListener() {
                      public void actionPerformed(java.awt.event.ActionEvent evt) {
                          btnModemBScrambleDeactivateActionPerformed(evt);
                      }
                  });
                  
                  jPanel191.add(btnModemBScrambleDeactivate);
                  
                  jPanel189.add(jPanel191);
                
                jPanel170.add(jPanel189);
              
              panelModemB.add(jPanel170);
            
            panelModems.add(panelModemB);
          
          add(panelModems, java.awt.BorderLayout.CENTER);
        
    }//GEN-END:initComponents

    private void btnModemBScrambleActivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModemBScrambleActivateActionPerformed
        showButtonInactive( btnModemBScrambleDeactivate );
        SatControl ctrl = sat.getControl();
        if( (ctrl==null) || (srvLnk==null) ) return;
        srvLnk.sendPacketToSpacecraft(ctrl.messageToActivateModemBScrambler());
    }//GEN-LAST:event_btnModemBScrambleActivateActionPerformed

    private void btnModemASourceDigitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModemASourceDigitalActionPerformed
        showButtonInactive( btnModemASourceAnalog );
        SatControl ctrl = sat.getControl();
        if( (ctrl==null) || (srvLnk==null) ) return;
        srvLnk.sendPacketToSpacecraft(ctrl.messageToSetModemASource("D"));
    }//GEN-LAST:event_btnModemASourceDigitalActionPerformed

    private void txtModemAOffsetKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModemAOffsetKeyReleased
      try {
          slidModemAOffset.setValue( Integer.parseInt(txtModemAOffset.getText()) );
      }catch( NumberFormatException nfe ) {
          slidModemAOffset.setValue( 0 );
      }
    }//GEN-LAST:event_txtModemAOffsetKeyReleased

    private void btnModemBCTCSSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModemBCTCSSActionPerformed
        CTCSS ctcss = (CTCSS)listModemBCTCSS.getSelectedItem();
        SatControl ctrl = sat.getControl();
        if( (ctrl==null) || (srvLnk==null) ) return;
        srvLnk.sendPacketToSpacecraft(ctrl.messageToSetModemBCTCSS(ctcss.code));
    }//GEN-LAST:event_btnModemBCTCSSActionPerformed

    private void btnModemBSourceAnalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModemBSourceAnalogActionPerformed
      showButtonInactive( btnModemBSourceDigital );
      SatControl ctrl = sat.getControl();
      if( (ctrl==null) || (srvLnk==null) ) return;
      srvLnk.sendPacketToSpacecraft(ctrl.messageToSetModemBSource("A"));
    }//GEN-LAST:event_btnModemBSourceAnalogActionPerformed

    private void slidModemADeviationStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slidModemADeviationStateChanged
    txtModemADeviation.setText(""+slidModemADeviation.getValue());
    if( chkModemADeviationContinuous.isSelected() ) {
        SatControl ctrl = sat.getControl();
        if( (ctrl==null) || (srvLnk==null) ) return;
        String strVal = new String(""+slidModemADeviation.getValue());
        srvLnk.sendPacketToSpacecraft(ctrl.messageToSetModemADeviation(strVal));
    }
    }//GEN-LAST:event_slidModemADeviationStateChanged

    private void txtModemBOffsetKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModemBOffsetKeyReleased
      try {
          slidModemBOffset.setValue( Integer.parseInt(txtModemBOffset.getText()) );
      }catch( NumberFormatException nfe ) {
          slidModemBOffset.setValue( 0 );
      }
    }//GEN-LAST:event_txtModemBOffsetKeyReleased

    private void btnModemASourceAnalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModemASourceAnalogActionPerformed
      showButtonInactive( btnModemASourceDigital );
      SatControl ctrl = sat.getControl();
      if( (ctrl==null) || (srvLnk==null) ) return;
      srvLnk.sendPacketToSpacecraft(ctrl.messageToSetModemASource("A"));
    }//GEN-LAST:event_btnModemASourceAnalogActionPerformed

    private void txtModemBDeviationKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModemBDeviationKeyReleased
      try {
          slidModemBDeviation.setValue( Integer.parseInt(txtModemBDeviation.getText()) );
      }catch( NumberFormatException nfe ) {
          slidModemBDeviation.setValue( 0 );
      }
    }//GEN-LAST:event_txtModemBDeviationKeyReleased

    private void btnModemBRateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModemBRateActionPerformed
    /*-------------------------------------------------------------*/
    /* Eventually, since the modem 4 predefined settings for rates */
    /* can change we should put the mapping into a file so that we */
    /* canm change it without recompile it...                      */
    /*-------------------------------------------------------------*/
    String selected = (String)listModemBRate.getSelectedItem();
    if( selected.equals("1200") ) {
        SatControl ctrl = sat.getControl();
        if( (ctrl==null) || (srvLnk==null) ) return;
        srvLnk.sendPacketToSpacecraft(ctrl.messageToSetModemBRate("1"));
    } else if( selected.equals("2400") ) {
        SatControl ctrl = sat.getControl();
        if( (ctrl==null) || (srvLnk==null) ) return;
        srvLnk.sendPacketToSpacecraft(ctrl.messageToSetModemBRate("2"));
    } else if( selected.equals("4800") ) {
        SatControl ctrl = sat.getControl();
        if( (ctrl==null) || (srvLnk==null) ) return;
        srvLnk.sendPacketToSpacecraft(ctrl.messageToSetModemBRate("4"));
    } else if( selected.equals("9600") ) {
        SatControl ctrl = sat.getControl();
        if( (ctrl==null) || (srvLnk==null) ) return;
        srvLnk.sendPacketToSpacecraft(ctrl.messageToSetModemBRate("9"));
    } else {
        System.out.println("ERROR: Invalid modemB rate selection");
    }
    }//GEN-LAST:event_btnModemBRateActionPerformed

    private void txtModemADeviationKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtModemADeviationKeyReleased
      try {
          slidModemADeviation.setValue( Integer.parseInt(txtModemADeviation.getText()) );
      }catch( NumberFormatException nfe ) {
          slidModemADeviation.setValue( 0 );
      }
    }//GEN-LAST:event_txtModemADeviationKeyReleased

    private void btnModemBDeviationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModemBDeviationActionPerformed
        SatControl ctrl = sat.getControl();
        if( (ctrl==null) || (srvLnk==null) ) return;
        String strVal = new String(""+slidModemBDeviation.getValue());
        srvLnk.sendPacketToSpacecraft(ctrl.messageToSetModemBDeviation(strVal));
    }//GEN-LAST:event_btnModemBDeviationActionPerformed

    private void btnModemADeviationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModemADeviationActionPerformed
        SatControl ctrl = sat.getControl();
        if( (ctrl==null) || (srvLnk==null) ) return;
        String strVal = new String(""+slidModemADeviation.getValue());
        srvLnk.sendPacketToSpacecraft(ctrl.messageToSetModemADeviation(strVal));
    }//GEN-LAST:event_btnModemADeviationActionPerformed

    private void btnModemsInitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModemsInitActionPerformed
        SatControl ctrl = sat.getControl();
        if( (ctrl==null) || (srvLnk==null) ) return;
        srvLnk.sendPacketToSpacecraft(ctrl.messageToInitializeModems());
    }//GEN-LAST:event_btnModemsInitActionPerformed

    private void btnModemBOffsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModemBOffsetActionPerformed
        SatControl ctrl = sat.getControl();
        if( (ctrl==null) || (srvLnk==null) ) return;
        String strVal = new String(""+slidModemBOffset.getValue());
        srvLnk.sendPacketToSpacecraft(ctrl.messageToSetModemBOffset(strVal));
    }//GEN-LAST:event_btnModemBOffsetActionPerformed

    private void btnModemBScrambleDeactivateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModemBScrambleDeactivateActionPerformed
      showButtonInactive( btnModemBScrambleActivate );
      SatControl ctrl = sat.getControl();
      if( (ctrl==null) || (srvLnk==null) ) return;
      srvLnk.sendPacketToSpacecraft(ctrl.messageToDeactivateModemBScrambler());
    }//GEN-LAST:event_btnModemBScrambleDeactivateActionPerformed

    private void slidModemBDeviationStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slidModemBDeviationStateChanged
    txtModemBDeviation.setText(""+slidModemBDeviation.getValue());
    if( chkModemBDeviationContinuous.isSelected() ) {
        SatControl ctrl = sat.getControl();
        if( (ctrl==null) || (srvLnk==null) ) return;
        String strVal = new String(""+slidModemBDeviation.getValue());
        srvLnk.sendPacketToSpacecraft(ctrl.messageToSetModemBDeviation(strVal));
    }
    }//GEN-LAST:event_slidModemBDeviationStateChanged

    private void btnDigipeatONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigipeatONActionPerformed
      showButtonInactive( btnDigipeatOFF );
      SatControl ctrl = sat.getControl();
      if( (ctrl==null) || (srvLnk==null) ) return;
      srvLnk.sendPacketToSpacecraft(ctrl.messageToActivateDigipeat());
    }//GEN-LAST:event_btnDigipeatONActionPerformed

    private void slidModemBOffsetStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slidModemBOffsetStateChanged
    txtModemBOffset.setText(""+slidModemBOffset.getValue());
    if( chkModemBOffsetContinuous.isSelected() ) {
        SatControl ctrl = sat.getControl();
        if( (ctrl==null) || (srvLnk==null) ) return;
        String strVal = new String(""+slidModemBOffset.getValue());
        srvLnk.sendPacketToSpacecraft(ctrl.messageToSetModemBOffset(strVal));
    }
    }//GEN-LAST:event_slidModemBOffsetStateChanged

    private void btnModemACTCSSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModemACTCSSActionPerformed
        CTCSS ctcss = (CTCSS)listModemACTCSS.getSelectedItem();
        SatControl ctrl = sat.getControl();
        if( (ctrl==null) || (srvLnk==null) ) return;
        srvLnk.sendPacketToSpacecraft(ctrl.messageToSetModemACTCSS(ctcss.code));
    }//GEN-LAST:event_btnModemACTCSSActionPerformed

    private void slidModemAOffsetStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slidModemAOffsetStateChanged
    txtModemAOffset.setText(""+slidModemAOffset.getValue());
    if( chkModemAOffsetContinuous.isSelected() ) {
        SatControl ctrl = sat.getControl();
        if( (ctrl==null) || (srvLnk==null) ) return;
        String strVal = new String(""+slidModemAOffset.getValue());
        srvLnk.sendPacketToSpacecraft(ctrl.messageToSetModemAOffset(strVal));
    }
    }//GEN-LAST:event_slidModemAOffsetStateChanged

    private void btnModemAOffsetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModemAOffsetActionPerformed
        SatControl ctrl = sat.getControl();
        if( (ctrl==null) || (srvLnk==null) ) return;
        String strVal = new String(""+slidModemAOffset.getValue());
        srvLnk.sendPacketToSpacecraft(ctrl.messageToSetModemAOffset(strVal));
    }//GEN-LAST:event_btnModemAOffsetActionPerformed

    private void btnModemBSourceDigitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModemBSourceDigitalActionPerformed
      showButtonInactive( btnModemBSourceAnalog );        
      SatControl ctrl = sat.getControl();
      if( (ctrl==null) || (srvLnk==null) ) return;
      srvLnk.sendPacketToSpacecraft(ctrl.messageToSetModemBSource("D"));
    }//GEN-LAST:event_btnModemBSourceDigitalActionPerformed

    private void btnDigipeatOFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDigipeatOFFActionPerformed
      showButtonInactive( btnDigipeatON );        
      SatControl ctrl = sat.getControl();
      if( (ctrl==null) || (srvLnk==null) ) return;
      srvLnk.sendPacketToSpacecraft(ctrl.messageToDeactivateDigipeat());
    }//GEN-LAST:event_btnDigipeatOFFActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelModems;
    private javax.swing.JPanel panelModemA;
    private javax.swing.JLabel jLabel97;
    private javax.swing.JPanel panelModemACommands;
    private javax.swing.JPanel jPanel186;
    private javax.swing.JPanel jPanel180;
    public javax.swing.JButton btnModemASourceAnalog;
    public javax.swing.JButton btnModemASourceDigital;
    private javax.swing.JPanel jPanel182;
    private javax.swing.JLabel jLabel45;
    public javax.swing.JComboBox listModemACTCSS;
    private javax.swing.JButton btnModemACTCSS;
    private javax.swing.JPanel jPanel187;
    public javax.swing.JPanel jPanel183;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JTextField txtModemAOffset;
    private javax.swing.JLabel jLabel100;
    private javax.swing.JSlider slidModemAOffset;
    private javax.swing.JLabel jLabel101;
    private javax.swing.JButton btnModemAOffset;
    private javax.swing.JCheckBox chkModemAOffsetContinuous;
    private javax.swing.JPanel jPanel181;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JTextField txtModemADeviation;
    private javax.swing.JLabel jLabel98;
    private javax.swing.JSlider slidModemADeviation;
    private javax.swing.JLabel jLabel99;
    private javax.swing.JButton btnModemADeviation;
    private javax.swing.JCheckBox chkModemADeviationContinuous;
    private javax.swing.JPanel jPanel169;
    private javax.swing.JPanel jPanel242;
    private javax.swing.JButton btnModemsInit;
    private javax.swing.JPanel jPanel176;
    private javax.swing.JLabel jLabel96;
    private javax.swing.JPanel jPanel209;
    public javax.swing.JButton btnDigipeatON;
    public javax.swing.JButton btnDigipeatOFF;
    private javax.swing.JPanel panelModemB;
    private javax.swing.JLabel jLabel102;
    private javax.swing.JPanel jPanel170;
    private javax.swing.JPanel jPanel171;
    private javax.swing.JPanel jPanel172;
    public javax.swing.JButton btnModemBSourceAnalog;
    public javax.swing.JButton btnModemBSourceDigital;
    private javax.swing.JPanel jPanel173;
    private javax.swing.JLabel jLabel55;
    public javax.swing.JComboBox listModemBCTCSS;
    private javax.swing.JButton btnModemBCTCSS;
    private javax.swing.JPanel jPanel174;
    private javax.swing.JPanel jPanel177;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JTextField txtModemBOffset;
    private javax.swing.JLabel jLabel103;
    private javax.swing.JSlider slidModemBOffset;
    private javax.swing.JLabel jLabel104;
    private javax.swing.JButton btnModemBOffset;
    private javax.swing.JCheckBox chkModemBOffsetContinuous;
    private javax.swing.JPanel jPanel178;
    private javax.swing.JLabel jLabel95;
    private javax.swing.JTextField txtModemBDeviation;
    private javax.swing.JLabel jLabel105;
    private javax.swing.JSlider slidModemBDeviation;
    private javax.swing.JLabel jLabel106;
    private javax.swing.JButton btnModemBDeviation;
    private javax.swing.JCheckBox chkModemBDeviationContinuous;
    private javax.swing.JPanel jPanel189;
    private javax.swing.JPanel jPanel190;
    public javax.swing.JComboBox listModemBRate;
    private javax.swing.JButton btnModemBRate;
    private javax.swing.JPanel jPanel191;
    public javax.swing.JButton btnModemBScrambleActivate;
    public javax.swing.JButton btnModemBScrambleDeactivate;
    // End of variables declaration//GEN-END:variables
    /*------------------------------------------------------------------------*/
    /** Change the appearance of the button so that user knows that the
     *  function associated with this button is not known, but will be as soon
     *  as we receive telemetry information.
     *  @param button The swing button.                                       */
    /*------------------------------------------------------------------------*/
    public void showButtonInactive( JButton button ) {
    /*------------------------------------------------------------------------*/
     button.setIcon(
       new javax.swing.ImageIcon(
        getClass().getResource(LED_OFF)));
    }
    
    /*------------------------------------------------------------------------*/
    /** Change the appearance of the button so that user knows that the
     *  function associated with this button is "active" or "on".
     *  @param button The swing button.                                       */
    /*------------------------------------------------------------------------*/
    public void showButtonActiveON( JButton button ) {
    /*------------------------------------------------------------------------*/
     button.setIcon(
       new javax.swing.ImageIcon(
        getClass().getResource(LED_GREEN_ON)));
    }
    
    /*------------------------------------------------------------------------*/
    /** Change the appearance of the button so that user knows that the
     *  function associated with this button is "inactive" or "off".
     *  @param button The swing button.                                       */
    /*------------------------------------------------------------------------*/
    public void showButtonActiveOFF( JButton button ) {
    /*------------------------------------------------------------------------*/
     button.setIcon(
       new javax.swing.ImageIcon(
        getClass().getResource(LED_RED_ON)));
    }
    
    /*------------------------------------------------------------------------*/
    /** Change the appearance of the button so that user knows that the
     *  state of the function associated with this button is unknown.
     *  @param button The swing button.                                       */
    /*------------------------------------------------------------------------*/
    public void showButtonNeutral( JButton button ) {
    /*------------------------------------------------------------------------*/
     button.setIcon(
       new javax.swing.ImageIcon(
        getClass().getResource(LED_WHITE)));
    }
}
