/*
 * UploadScript.java
 *
 * Created on January 14, 2002, 9:53 AM
 */

package ca.gc.space.quicksat.ground.control;

/**
 *
 * @author  jfcusson
 */
public class UploadScript extends javax.swing.JPanel {

    /** Creates new form UploadScript */
    public UploadScript() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
                jPanel1 = new javax.swing.JPanel();
                jPanel2 = new javax.swing.JPanel();
                jPanel3 = new javax.swing.JPanel();
                jScrollPane1 = new javax.swing.JScrollPane();
                tblScript = new javax.swing.JTable();
                jPanel4 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                listScripts = new javax.swing.JComboBox();
                jPanel5 = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();
                txtDataSize = new javax.swing.JTextField();
                slidDataSize = new javax.swing.JSlider();
                chkDynDataSize = new javax.swing.JCheckBox();
                jPanel6 = new javax.swing.JPanel();
                jPanel7 = new javax.swing.JPanel();
                jLabel3 = new javax.swing.JLabel();
                jLabel4 = new javax.swing.JLabel();
                jPanel8 = new javax.swing.JPanel();
                btnLoad = new javax.swing.JButton();
                lblLoadTaskAck = new javax.swing.JLabel();
                lblLoadAck = new javax.swing.JLabel();
                lblAdress = new javax.swing.JLabel();
                jLabel8 = new javax.swing.JLabel();
                lblAddressAck = new javax.swing.JLabel();
                jPanel9 = new javax.swing.JPanel();
                btnSetSegment = new javax.swing.JButton();
                txtSetSegment = new javax.swing.JTextField();
                lblSetSegmentAck = new javax.swing.JLabel();
                jPanel10 = new javax.swing.JPanel();
                btnSendData = new javax.swing.JButton();
                txtDataSegment = new javax.swing.JTextField();
                jLabel11 = new javax.swing.JLabel();
                txtDataOffset = new javax.swing.JTextField();
                lblSendDataAck = new javax.swing.JLabel();
                jPanel11 = new javax.swing.JPanel();
                btnSendEOF = new javax.swing.JButton();
                lblSendEOFAck = new javax.swing.JLabel();
                jPanel12 = new javax.swing.JPanel();
                btnCreateTask = new javax.swing.JButton();
                lblCreateTaskAck = new javax.swing.JLabel();
                jPanel13 = new javax.swing.JPanel();
                btnRun = new javax.swing.JButton();
                btnReset = new javax.swing.JButton();
                
                setLayout(new java.awt.BorderLayout());
                
                jPanel1.setLayout(new java.awt.GridLayout(1, 2));
                
                jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.Y_AXIS));
                
                jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.Y_AXIS));
                
                jScrollPane1.setPreferredSize(new java.awt.Dimension(380, 100));
                tblScript.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
                },
                new String [] {
                    "File to Upload", "Command Line", "Size", "Progress"
                }
                ) {
                    Class[] types = new Class [] {
                        java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
                    };
                    boolean[] canEdit = new boolean [] {
                        true, true, false, false
                    };
                    
                    public Class getColumnClass(int columnIndex) {
                        return types [columnIndex];
                    }
                    
                    public boolean isCellEditable(int rowIndex, int columnIndex) {
                        return canEdit [columnIndex];
                    }
                });
                tblScript.setPreferredScrollableViewportSize(new java.awt.Dimension(400, 400));
                jScrollPane1.setViewportView(tblScript);
                
                jPanel3.add(jScrollPane1);
              
              jLabel1.setText("Upload Script:");
                jPanel4.add(jLabel1);
                
                jPanel4.add(listScripts);
                
                jPanel3.add(jPanel4);
              
              jPanel2.add(jPanel3);
            
            jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 1, 2));
              
              jPanel5.setBorder(new javax.swing.border.EtchedBorder());
              jLabel2.setText("Packet Size:");
              jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
              jPanel5.add(jLabel2);
              
              txtDataSize.setEditable(false);
              txtDataSize.setText(" ");
              txtDataSize.setPreferredSize(new java.awt.Dimension(30, 20));
              txtDataSize.setMinimumSize(new java.awt.Dimension(30, 20));
              jPanel5.add(txtDataSize);
              
              slidDataSize.setMinorTickSpacing(10);
              slidDataSize.setPaintTicks(true);
              slidDataSize.setMinimum(1);
              slidDataSize.setMajorTickSpacing(100);
              slidDataSize.setMaximum(230);
              slidDataSize.setName("PacketSize");
              jPanel5.add(slidDataSize);
              
              chkDynDataSize.setSelected(true);
              chkDynDataSize.setText("Dynamic");
              jPanel5.add(chkDynDataSize);
              
              jPanel2.add(jPanel5);
            
            jPanel1.add(jPanel2);
          
          jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.Y_AXIS));
              
              jPanel6.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
              jPanel6.setBackground(java.awt.Color.black);
              jPanel7.setLayout(new java.awt.GridLayout(8, 2));
              
              jPanel7.setName("Progress");
              jLabel3.setText("GROUND");
              jLabel3.setForeground(java.awt.Color.yellow);
              jLabel3.setBackground(java.awt.Color.black);
              jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
              jLabel3.setFont(new java.awt.Font("Dialog", 3, 12));
              jLabel3.setOpaque(true);
              jPanel7.add(jLabel3);
              
              jLabel4.setText("SATELLITE");
              jLabel4.setForeground(java.awt.Color.yellow);
              jLabel4.setBackground(java.awt.Color.black);
              jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
              jLabel4.setFont(new java.awt.Font("Dialog", 3, 12));
              jLabel4.setOpaque(true);
              jPanel7.add(jLabel4);
              
              jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.X_AXIS));
                
                btnLoad.setText("Load Task");
                btnLoad.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
                btnLoad.setMaximumSize(new java.awt.Dimension(1000, 50));
                jPanel8.add(btnLoad);
                
                jPanel7.add(jPanel8);
              
              lblLoadTaskAck.setText("ACK");
              lblLoadTaskAck.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
              lblLoadTaskAck.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
              lblLoadTaskAck.setOpaque(true);
              jPanel7.add(lblLoadTaskAck);
              
              lblLoadAck.setText(" ");
              lblLoadAck.setBackground(java.awt.Color.lightGray);
              lblLoadAck.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
              lblLoadAck.setOpaque(true);
              jPanel7.add(lblLoadAck);
              
              lblAdress.setText("LOAD");
              lblAdress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
              lblAdress.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
              lblAdress.setOpaque(true);
              jPanel7.add(lblAdress);
              
              jLabel8.setText(" ");
              jLabel8.setBackground(java.awt.Color.lightGray);
              jLabel8.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
              jLabel8.setOpaque(true);
              jPanel7.add(jLabel8);
              
              lblAddressAck.setText("ADDRESS");
              lblAddressAck.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
              lblAddressAck.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
              lblAddressAck.setOpaque(true);
              jPanel7.add(lblAddressAck);
              
              jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.X_AXIS));
                
                btnSetSegment.setText("Set Segment");
                btnSetSegment.setPreferredSize(new java.awt.Dimension(85, 23));
                btnSetSegment.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
                btnSetSegment.setMaximumSize(new java.awt.Dimension(1000, 50));
                jPanel9.add(btnSetSegment);
                
                txtSetSegment.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
                jPanel9.add(txtSetSegment);
                
                jPanel7.add(jPanel9);
              
              lblSetSegmentAck.setText("ACK");
              lblSetSegmentAck.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
              lblSetSegmentAck.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
              lblSetSegmentAck.setOpaque(true);
              jPanel7.add(lblSetSegmentAck);
              
              jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.X_AXIS));
                
                btnSendData.setText("Send Data");
                btnSendData.setPreferredSize(new java.awt.Dimension(85, 23));
                btnSendData.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
                btnSendData.setMaximumSize(new java.awt.Dimension(1000, 50));
                jPanel10.add(btnSendData);
                
                txtDataSegment.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
                jPanel10.add(txtDataSegment);
                
                jLabel11.setText(":");
                jPanel10.add(jLabel11);
                
                txtDataOffset.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
                jPanel10.add(txtDataOffset);
                
                jPanel7.add(jPanel10);
              
              lblSendDataAck.setText("ACK");
              lblSendDataAck.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
              lblSendDataAck.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
              lblSendDataAck.setOpaque(true);
              jPanel7.add(lblSendDataAck);
              
              jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.X_AXIS));
                
                btnSendEOF.setText("Send EOF");
                btnSendEOF.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
                btnSendEOF.setMaximumSize(new java.awt.Dimension(1000, 50));
                jPanel11.add(btnSendEOF);
                
                jPanel7.add(jPanel11);
              
              lblSendEOFAck.setText("ACK");
              lblSendEOFAck.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
              lblSendEOFAck.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
              lblSendEOFAck.setOpaque(true);
              jPanel7.add(lblSendEOFAck);
              
              jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.X_AXIS));
                
                btnCreateTask.setText("Create Task");
                btnCreateTask.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
                btnCreateTask.setMaximumSize(new java.awt.Dimension(1000, 50));
                jPanel12.add(btnCreateTask);
                
                jPanel7.add(jPanel12);
              
              lblCreateTaskAck.setText("ACK");
              lblCreateTaskAck.setToolTipText("");
              lblCreateTaskAck.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
              lblCreateTaskAck.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
              lblCreateTaskAck.setOpaque(true);
              jPanel7.add(lblCreateTaskAck);
              
              jPanel6.add(jPanel7);
            
            btnRun.setText("Execute Loaded Tasks");
              jPanel13.add(btnRun);
              
              btnReset.setForeground(java.awt.Color.yellow);
              btnReset.setFont(new java.awt.Font("Dialog", 3, 11));
              btnReset.setText("RESET LOAD");
              btnReset.setBackground(java.awt.Color.red);
              jPanel13.add(btnReset);
              
              jPanel6.add(jPanel13);
            
            jPanel1.add(jPanel6);
          
          add(jPanel1, java.awt.BorderLayout.CENTER);
        
    }//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblScript;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox listScripts;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtDataSize;
    private javax.swing.JSlider slidDataSize;
    private javax.swing.JCheckBox chkDynDataSize;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JButton btnLoad;
    private javax.swing.JLabel lblLoadTaskAck;
    private javax.swing.JLabel lblLoadAck;
    private javax.swing.JLabel lblAdress;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblAddressAck;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton btnSetSegment;
    private javax.swing.JTextField txtSetSegment;
    private javax.swing.JLabel lblSetSegmentAck;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JButton btnSendData;
    private javax.swing.JTextField txtDataSegment;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JTextField txtDataOffset;
    private javax.swing.JLabel lblSendDataAck;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JButton btnSendEOF;
    private javax.swing.JLabel lblSendEOFAck;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JButton btnCreateTask;
    private javax.swing.JLabel lblCreateTaskAck;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JButton btnRun;
    private javax.swing.JButton btnReset;
    // End of variables declaration//GEN-END:variables

}
