/*
 * PanelTelemetry.java
 *
 * Created on June 19, 2001, 10:48 AM
 */

package ca.gc.space.quicksat.ground.telemetry;

import ca.gc.space.quicksat.ground.util.*;

/**
 *
 * @author  jfcusson
 * @version 
 */
public class PanelTelemetry extends javax.swing.JPanel {
Log         log                  = null;

    /** Creates new form PanelTelemetry */
    public PanelTelemetry( Log log ) {
        initComponents ();
        this.log = log;                
        if( this.log == null ) this.log = new Log();        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the FormEditor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
              jTabbedPane1 = new javax.swing.JTabbedPane();
              panelRawTelem = new javax.swing.JPanel();
              jScrollPane2 = new javax.swing.JScrollPane();
              tblRawTelem = new javax.swing.JTable();
              jPanel2 = new javax.swing.JPanel();
              panelPayloads = new javax.swing.JPanel();
              jLabel2 = new javax.swing.JLabel();
              jPanel1 = new javax.swing.JPanel();
              jPanel3 = new javax.swing.JPanel();
              jPanel4 = new javax.swing.JPanel();
              jLabel1 = new javax.swing.JLabel();
              prgrssPayload1 = new javax.swing.JProgressBar();
              jPanel5 = new javax.swing.JPanel();
              jLabel3 = new javax.swing.JLabel();
              prgrssPayload2 = new javax.swing.JProgressBar();
              jPanel6 = new javax.swing.JPanel();
              jLabel4 = new javax.swing.JLabel();
              prgrssPayload3 = new javax.swing.JProgressBar();
              jPanel7 = new javax.swing.JPanel();
              jLabel5 = new javax.swing.JLabel();
              prgrssPayload4 = new javax.swing.JProgressBar();
              jPanel8 = new javax.swing.JPanel();
              jLabel6 = new javax.swing.JLabel();
              prgrssPayload5 = new javax.swing.JProgressBar();
              jPanel9 = new javax.swing.JPanel();
              jLabel7 = new javax.swing.JLabel();
              prgrssPayload6 = new javax.swing.JProgressBar();
              jPanel10 = new javax.swing.JPanel();
              jLabel8 = new javax.swing.JLabel();
              prgrssPayload7 = new javax.swing.JProgressBar();
              jPanel11 = new javax.swing.JPanel();
              jLabel9 = new javax.swing.JLabel();
              prgrssPayload8 = new javax.swing.JProgressBar();
              jPanel12 = new javax.swing.JPanel();
              jLabel10 = new javax.swing.JLabel();
              prgrssPayload9 = new javax.swing.JProgressBar();
              jPanel13 = new javax.swing.JPanel();
              jLabel11 = new javax.swing.JLabel();
              prgrssPayload10 = new javax.swing.JProgressBar();
              jPanel14 = new javax.swing.JPanel();
              jLabel12 = new javax.swing.JLabel();
              prgrssPayload11 = new javax.swing.JProgressBar();
              jPanel15 = new javax.swing.JPanel();
              jLabel13 = new javax.swing.JLabel();
              prgrssPayload12 = new javax.swing.JProgressBar();
              panelTX = new javax.swing.JPanel();
              panelTX1 = new javax.swing.JPanel();
              jLabel16 = new javax.swing.JLabel();
              jPanel17 = new javax.swing.JPanel();
              jPanel18 = new javax.swing.JPanel();
              jPanel19 = new javax.swing.JPanel();
              jLabel14 = new javax.swing.JLabel();
              prgrssTX1RFOut1 = new javax.swing.JProgressBar();
              txtTX1RFOut1 = new javax.swing.JTextField();
              jPanel16 = new javax.swing.JPanel();
              jLabel15 = new javax.swing.JLabel();
              prgrssTX1RFOut2 = new javax.swing.JProgressBar();
              txtTX1RFOut2 = new javax.swing.JTextField();
              jPanel20 = new javax.swing.JPanel();
              jPanel21 = new javax.swing.JPanel();
              jLabel17 = new javax.swing.JLabel();
              prgrssTX1_5V = new javax.swing.JProgressBar();
              txtTX1_5V = new javax.swing.JTextField();
              jPanel22 = new javax.swing.JPanel();
              jPanel23 = new javax.swing.JPanel();
              jLabel18 = new javax.swing.JLabel();
              prgrssTX1Temp = new javax.swing.JProgressBar();
              txtTX1Temp = new javax.swing.JTextField();
              jPanel24 = new javax.swing.JPanel();
              lblTX1PTT = new javax.swing.JLabel();
              lblTX1PLLError = new javax.swing.JLabel();
              jPanel25 = new javax.swing.JPanel();
              jLabel19 = new javax.swing.JLabel();
              jPanel26 = new javax.swing.JPanel();
              jPanel27 = new javax.swing.JPanel();
              jPanel28 = new javax.swing.JPanel();
              jLabel20 = new javax.swing.JLabel();
              prgrssTX2RFOut1 = new javax.swing.JProgressBar();
              txtTX2RFOut1 = new javax.swing.JTextField();
              jPanel29 = new javax.swing.JPanel();
              jLabel21 = new javax.swing.JLabel();
              prgrssTX2RFOut2 = new javax.swing.JProgressBar();
              txtTX2RFOut2 = new javax.swing.JTextField();
              jPanel30 = new javax.swing.JPanel();
              jPanel31 = new javax.swing.JPanel();
              jLabel22 = new javax.swing.JLabel();
              prgrssTX2_5V = new javax.swing.JProgressBar();
              txtTX2_5V = new javax.swing.JTextField();
              jPanel32 = new javax.swing.JPanel();
              jPanel33 = new javax.swing.JPanel();
              jLabel23 = new javax.swing.JLabel();
              prgrssTX2Temp = new javax.swing.JProgressBar();
              txtTX2Temp = new javax.swing.JTextField();
              jPanel34 = new javax.swing.JPanel();
              lblTX2PTT = new javax.swing.JLabel();
              lblTX2PLLError = new javax.swing.JLabel();
              jPanel35 = new javax.swing.JPanel();
              jPanel36 = new javax.swing.JPanel();
              jButton1 = new javax.swing.JButton();
              jPanel37 = new javax.swing.JPanel();
              jCheckBox1 = new javax.swing.JCheckBox();
              jCheckBox2 = new javax.swing.JCheckBox();
              jCheckBox3 = new javax.swing.JCheckBox();
              jCheckBox4 = new javax.swing.JCheckBox();
              jButton2 = new javax.swing.JButton();
              
              setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.X_AXIS));
              
              jTabbedPane1.setPreferredSize(new java.awt.Dimension(500, 200));
              panelRawTelem.setLayout(new javax.swing.BoxLayout(panelRawTelem, javax.swing.BoxLayout.X_AXIS));
              
              panelRawTelem.setPreferredSize(new java.awt.Dimension(500, 200));
              tblRawTelem.setModel(new javax.swing.table.DefaultTableModel(
              new Object [][] {
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null},
                  {null, null, null, null}
              },
              new String [] {
                  "Index", "Description", "Raw Value", "Refresh"
              }
              ) {
                  Class[] types = new Class [] {
                      java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
                  };
                  boolean[] canEdit = new boolean [] {
                      false, false, false, false
                  };
                  
                  public Class getColumnClass(int columnIndex) {
                      return types [columnIndex];
                  }
                  
                  public boolean isCellEditable(int rowIndex, int columnIndex) {
                      return canEdit [columnIndex];
                  }
              });
              tblRawTelem.setColumnModel(tblRawTelem.getColumnModel());
              jScrollPane2.setViewportView(tblRawTelem);
              
              panelRawTelem.add(jScrollPane2);
            
            panelRawTelem.add(jPanel2);
            
            jTabbedPane1.addTab("Raw Data", panelRawTelem);
          
          panelPayloads.setLayout(new javax.swing.BoxLayout(panelPayloads, javax.swing.BoxLayout.Y_AXIS));
            
            jLabel2.setText("  PAYLOAD MONITOR TELEMETRY  ");
            jLabel2.setForeground(java.awt.Color.yellow);
            jLabel2.setBackground(java.awt.Color.blue);
            jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14));
            jLabel2.setAlignmentX(0.5F);
            jLabel2.setMaximumSize(new java.awt.Dimension(2000, 21));
            jLabel2.setOpaque(true);
            panelPayloads.add(jLabel2);
            
            jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.X_AXIS));
                  
                  jPanel1.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                  jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.X_AXIS));
                  
                  jPanel4.setLayout(new javax.swing.BoxLayout(jPanel4, javax.swing.BoxLayout.Y_AXIS));
                  
                  jPanel4.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                  jLabel1.setText("  1  ");
                  jLabel1.setForeground(java.awt.Color.white);
                  jLabel1.setBackground(java.awt.Color.darkGray);
                  jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                  jLabel1.setFont(new java.awt.Font("Arial Black", 0, 14));
                  jLabel1.setPreferredSize(new java.awt.Dimension(40, 17));
                  jLabel1.setMinimumSize(new java.awt.Dimension(25, 15));
                  jLabel1.setAlignmentX(0.5F);
                  jLabel1.setMaximumSize(new java.awt.Dimension(200, 21));
                  jLabel1.setOpaque(true);
                  jPanel4.add(jLabel1);
                  
                  prgrssPayload1.setOrientation(javax.swing.SwingConstants.VERTICAL);
                  prgrssPayload1.setMinimum(-2048);
                  prgrssPayload1.setMaximum(2047);
                  prgrssPayload1.setForeground(java.awt.Color.orange);
                  prgrssPayload1.setBackground(java.awt.Color.white);
                  prgrssPayload1.setPreferredSize(new java.awt.Dimension(25, 100));
                  prgrssPayload1.setMaximumSize(new java.awt.Dimension(32767, 2000));
                  jPanel4.add(prgrssPayload1);
                  
                  jPanel3.add(jPanel4);
                
                jPanel5.setLayout(new javax.swing.BoxLayout(jPanel5, javax.swing.BoxLayout.Y_AXIS));
                  
                  jPanel5.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                  jLabel3.setText("  2  ");
                  jLabel3.setForeground(java.awt.Color.white);
                  jLabel3.setBackground(java.awt.Color.darkGray);
                  jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                  jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14));
                  jLabel3.setPreferredSize(new java.awt.Dimension(40, 17));
                  jLabel3.setMinimumSize(new java.awt.Dimension(25, 15));
                  jLabel3.setAlignmentX(0.5F);
                  jLabel3.setMaximumSize(new java.awt.Dimension(200, 21));
                  jLabel3.setOpaque(true);
                  jPanel5.add(jLabel3);
                  
                  prgrssPayload2.setOrientation(javax.swing.SwingConstants.VERTICAL);
                  prgrssPayload2.setMinimum(-2048);
                  prgrssPayload2.setMaximum(2047);
                  prgrssPayload2.setForeground(java.awt.Color.orange);
                  prgrssPayload2.setBackground(java.awt.Color.white);
                  prgrssPayload2.setPreferredSize(new java.awt.Dimension(25, 100));
                  prgrssPayload2.setMaximumSize(new java.awt.Dimension(32767, 2000));
                  jPanel5.add(prgrssPayload2);
                  
                  jPanel3.add(jPanel5);
                
                jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.Y_AXIS));
                  
                  jPanel6.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                  jLabel4.setText("  3  ");
                  jLabel4.setForeground(java.awt.Color.white);
                  jLabel4.setBackground(java.awt.Color.darkGray);
                  jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                  jLabel4.setFont(new java.awt.Font("Arial Black", 0, 14));
                  jLabel4.setPreferredSize(new java.awt.Dimension(40, 17));
                  jLabel4.setMinimumSize(new java.awt.Dimension(25, 15));
                  jLabel4.setAlignmentX(0.5F);
                  jLabel4.setMaximumSize(new java.awt.Dimension(200, 21));
                  jLabel4.setOpaque(true);
                  jPanel6.add(jLabel4);
                  
                  prgrssPayload3.setOrientation(javax.swing.SwingConstants.VERTICAL);
                  prgrssPayload3.setMinimum(-2048);
                  prgrssPayload3.setMaximum(2047);
                  prgrssPayload3.setForeground(java.awt.Color.orange);
                  prgrssPayload3.setBackground(java.awt.Color.white);
                  prgrssPayload3.setPreferredSize(new java.awt.Dimension(25, 100));
                  prgrssPayload3.setMaximumSize(new java.awt.Dimension(32767, 2000));
                  jPanel6.add(prgrssPayload3);
                  
                  jPanel3.add(jPanel6);
                
                jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.Y_AXIS));
                  
                  jPanel7.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                  jLabel5.setText("  4  ");
                  jLabel5.setForeground(java.awt.Color.white);
                  jLabel5.setBackground(java.awt.Color.darkGray);
                  jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                  jLabel5.setFont(new java.awt.Font("Arial Black", 0, 14));
                  jLabel5.setPreferredSize(new java.awt.Dimension(40, 17));
                  jLabel5.setMinimumSize(new java.awt.Dimension(25, 15));
                  jLabel5.setAlignmentX(0.5F);
                  jLabel5.setMaximumSize(new java.awt.Dimension(200, 21));
                  jLabel5.setOpaque(true);
                  jPanel7.add(jLabel5);
                  
                  prgrssPayload4.setOrientation(javax.swing.SwingConstants.VERTICAL);
                  prgrssPayload4.setMinimum(-2048);
                  prgrssPayload4.setMaximum(2047);
                  prgrssPayload4.setForeground(java.awt.Color.orange);
                  prgrssPayload4.setBackground(java.awt.Color.white);
                  prgrssPayload4.setPreferredSize(new java.awt.Dimension(25, 100));
                  prgrssPayload4.setMaximumSize(new java.awt.Dimension(32767, 2000));
                  jPanel7.add(prgrssPayload4);
                  
                  jPanel3.add(jPanel7);
                
                jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.Y_AXIS));
                  
                  jPanel8.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                  jLabel6.setText("  5  ");
                  jLabel6.setForeground(java.awt.Color.white);
                  jLabel6.setBackground(java.awt.Color.darkGray);
                  jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                  jLabel6.setFont(new java.awt.Font("Arial Black", 0, 14));
                  jLabel6.setPreferredSize(new java.awt.Dimension(40, 17));
                  jLabel6.setMinimumSize(new java.awt.Dimension(25, 15));
                  jLabel6.setAlignmentX(0.5F);
                  jLabel6.setMaximumSize(new java.awt.Dimension(200, 21));
                  jLabel6.setOpaque(true);
                  jPanel8.add(jLabel6);
                  
                  prgrssPayload5.setOrientation(javax.swing.SwingConstants.VERTICAL);
                  prgrssPayload5.setMinimum(-2048);
                  prgrssPayload5.setMaximum(2047);
                  prgrssPayload5.setForeground(java.awt.Color.orange);
                  prgrssPayload5.setBackground(java.awt.Color.white);
                  prgrssPayload5.setPreferredSize(new java.awt.Dimension(25, 100));
                  prgrssPayload5.setMaximumSize(new java.awt.Dimension(32767, 2000));
                  jPanel8.add(prgrssPayload5);
                  
                  jPanel3.add(jPanel8);
                
                jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.Y_AXIS));
                  
                  jPanel9.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                  jLabel7.setText("  6  ");
                  jLabel7.setForeground(java.awt.Color.white);
                  jLabel7.setBackground(java.awt.Color.darkGray);
                  jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                  jLabel7.setFont(new java.awt.Font("Arial Black", 0, 14));
                  jLabel7.setPreferredSize(new java.awt.Dimension(40, 17));
                  jLabel7.setMinimumSize(new java.awt.Dimension(25, 15));
                  jLabel7.setAlignmentX(0.5F);
                  jLabel7.setMaximumSize(new java.awt.Dimension(200, 21));
                  jLabel7.setOpaque(true);
                  jPanel9.add(jLabel7);
                  
                  prgrssPayload6.setOrientation(javax.swing.SwingConstants.VERTICAL);
                  prgrssPayload6.setMinimum(-2048);
                  prgrssPayload6.setMaximum(2047);
                  prgrssPayload6.setForeground(java.awt.Color.orange);
                  prgrssPayload6.setBackground(java.awt.Color.white);
                  prgrssPayload6.setPreferredSize(new java.awt.Dimension(25, 100));
                  prgrssPayload6.setMaximumSize(new java.awt.Dimension(32767, 2000));
                  jPanel9.add(prgrssPayload6);
                  
                  jPanel3.add(jPanel9);
                
                jPanel10.setLayout(new javax.swing.BoxLayout(jPanel10, javax.swing.BoxLayout.Y_AXIS));
                  
                  jPanel10.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                  jLabel8.setText("  7  ");
                  jLabel8.setForeground(java.awt.Color.white);
                  jLabel8.setBackground(java.awt.Color.darkGray);
                  jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                  jLabel8.setFont(new java.awt.Font("Arial Black", 0, 14));
                  jLabel8.setPreferredSize(new java.awt.Dimension(40, 17));
                  jLabel8.setMinimumSize(new java.awt.Dimension(25, 15));
                  jLabel8.setAlignmentX(0.5F);
                  jLabel8.setMaximumSize(new java.awt.Dimension(200, 21));
                  jLabel8.setOpaque(true);
                  jPanel10.add(jLabel8);
                  
                  prgrssPayload7.setOrientation(javax.swing.SwingConstants.VERTICAL);
                  prgrssPayload7.setMinimum(-2048);
                  prgrssPayload7.setMaximum(2047);
                  prgrssPayload7.setForeground(java.awt.Color.orange);
                  prgrssPayload7.setBackground(java.awt.Color.white);
                  prgrssPayload7.setPreferredSize(new java.awt.Dimension(25, 100));
                  prgrssPayload7.setMaximumSize(new java.awt.Dimension(32767, 2000));
                  jPanel10.add(prgrssPayload7);
                  
                  jPanel3.add(jPanel10);
                
                jPanel11.setLayout(new javax.swing.BoxLayout(jPanel11, javax.swing.BoxLayout.Y_AXIS));
                  
                  jPanel11.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                  jLabel9.setText("  8  ");
                  jLabel9.setForeground(java.awt.Color.white);
                  jLabel9.setBackground(java.awt.Color.darkGray);
                  jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                  jLabel9.setFont(new java.awt.Font("Arial Black", 0, 14));
                  jLabel9.setPreferredSize(new java.awt.Dimension(40, 17));
                  jLabel9.setMinimumSize(new java.awt.Dimension(25, 15));
                  jLabel9.setAlignmentX(0.5F);
                  jLabel9.setMaximumSize(new java.awt.Dimension(200, 21));
                  jLabel9.setOpaque(true);
                  jPanel11.add(jLabel9);
                  
                  prgrssPayload8.setOrientation(javax.swing.SwingConstants.VERTICAL);
                  prgrssPayload8.setMinimum(-2048);
                  prgrssPayload8.setMaximum(2047);
                  prgrssPayload8.setForeground(java.awt.Color.orange);
                  prgrssPayload8.setBackground(java.awt.Color.white);
                  prgrssPayload8.setPreferredSize(new java.awt.Dimension(25, 100));
                  prgrssPayload8.setMaximumSize(new java.awt.Dimension(32767, 2000));
                  jPanel11.add(prgrssPayload8);
                  
                  jPanel3.add(jPanel11);
                
                jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.Y_AXIS));
                  
                  jPanel12.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                  jLabel10.setText("  9  ");
                  jLabel10.setForeground(java.awt.Color.white);
                  jLabel10.setBackground(java.awt.Color.darkGray);
                  jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                  jLabel10.setFont(new java.awt.Font("Arial Black", 0, 14));
                  jLabel10.setPreferredSize(new java.awt.Dimension(40, 17));
                  jLabel10.setMinimumSize(new java.awt.Dimension(25, 15));
                  jLabel10.setAlignmentX(0.5F);
                  jLabel10.setMaximumSize(new java.awt.Dimension(200, 21));
                  jLabel10.setOpaque(true);
                  jPanel12.add(jLabel10);
                  
                  prgrssPayload9.setOrientation(javax.swing.SwingConstants.VERTICAL);
                  prgrssPayload9.setMinimum(-2048);
                  prgrssPayload9.setMaximum(2047);
                  prgrssPayload9.setForeground(java.awt.Color.orange);
                  prgrssPayload9.setBackground(java.awt.Color.white);
                  prgrssPayload9.setPreferredSize(new java.awt.Dimension(25, 100));
                  prgrssPayload9.setMaximumSize(new java.awt.Dimension(32767, 2000));
                  jPanel12.add(prgrssPayload9);
                  
                  jPanel3.add(jPanel12);
                
                jPanel13.setLayout(new javax.swing.BoxLayout(jPanel13, javax.swing.BoxLayout.Y_AXIS));
                  
                  jPanel13.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                  jLabel11.setText("  10  ");
                  jLabel11.setForeground(java.awt.Color.white);
                  jLabel11.setBackground(java.awt.Color.darkGray);
                  jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                  jLabel11.setFont(new java.awt.Font("Arial Black", 0, 14));
                  jLabel11.setPreferredSize(new java.awt.Dimension(40, 17));
                  jLabel11.setMinimumSize(new java.awt.Dimension(25, 15));
                  jLabel11.setAlignmentX(0.5F);
                  jLabel11.setMaximumSize(new java.awt.Dimension(200, 21));
                  jLabel11.setOpaque(true);
                  jPanel13.add(jLabel11);
                  
                  prgrssPayload10.setOrientation(javax.swing.SwingConstants.VERTICAL);
                  prgrssPayload10.setMinimum(-2048);
                  prgrssPayload10.setMaximum(2047);
                  prgrssPayload10.setForeground(java.awt.Color.orange);
                  prgrssPayload10.setBackground(java.awt.Color.white);
                  prgrssPayload10.setPreferredSize(new java.awt.Dimension(25, 100));
                  prgrssPayload10.setMaximumSize(new java.awt.Dimension(32767, 2000));
                  jPanel13.add(prgrssPayload10);
                  
                  jPanel3.add(jPanel13);
                
                jPanel14.setLayout(new javax.swing.BoxLayout(jPanel14, javax.swing.BoxLayout.Y_AXIS));
                  
                  jPanel14.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                  jLabel12.setText("  11  ");
                  jLabel12.setForeground(java.awt.Color.white);
                  jLabel12.setBackground(java.awt.Color.darkGray);
                  jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                  jLabel12.setFont(new java.awt.Font("Arial Black", 0, 14));
                  jLabel12.setPreferredSize(new java.awt.Dimension(40, 17));
                  jLabel12.setMinimumSize(new java.awt.Dimension(25, 15));
                  jLabel12.setAlignmentX(0.5F);
                  jLabel12.setMaximumSize(new java.awt.Dimension(200, 21));
                  jLabel12.setOpaque(true);
                  jPanel14.add(jLabel12);
                  
                  prgrssPayload11.setOrientation(javax.swing.SwingConstants.VERTICAL);
                  prgrssPayload11.setMinimum(-2048);
                  prgrssPayload11.setMaximum(2047);
                  prgrssPayload11.setForeground(java.awt.Color.orange);
                  prgrssPayload11.setBackground(java.awt.Color.white);
                  prgrssPayload11.setPreferredSize(new java.awt.Dimension(25, 100));
                  prgrssPayload11.setMaximumSize(new java.awt.Dimension(32767, 2000));
                  jPanel14.add(prgrssPayload11);
                  
                  jPanel3.add(jPanel14);
                
                jPanel15.setLayout(new javax.swing.BoxLayout(jPanel15, javax.swing.BoxLayout.Y_AXIS));
                  
                  jPanel15.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                  jLabel13.setText("  12  ");
                  jLabel13.setForeground(java.awt.Color.white);
                  jLabel13.setBackground(java.awt.Color.darkGray);
                  jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                  jLabel13.setFont(new java.awt.Font("Arial Black", 0, 14));
                  jLabel13.setPreferredSize(new java.awt.Dimension(40, 17));
                  jLabel13.setMinimumSize(new java.awt.Dimension(25, 15));
                  jLabel13.setAlignmentX(0.5F);
                  jLabel13.setMaximumSize(new java.awt.Dimension(200, 21));
                  jLabel13.setOpaque(true);
                  jPanel15.add(jLabel13);
                  
                  prgrssPayload12.setOrientation(javax.swing.SwingConstants.VERTICAL);
                  prgrssPayload12.setMinimum(-2048);
                  prgrssPayload12.setMaximum(2047);
                  prgrssPayload12.setForeground(java.awt.Color.orange);
                  prgrssPayload12.setBackground(java.awt.Color.white);
                  prgrssPayload12.setPreferredSize(new java.awt.Dimension(25, 100));
                  prgrssPayload12.setMaximumSize(new java.awt.Dimension(32767, 2000));
                  jPanel15.add(prgrssPayload12);
                  
                  jPanel3.add(jPanel15);
                
                jPanel1.add(jPanel3);
              
              panelPayloads.add(jPanel1);
            
            jTabbedPane1.addTab("Payload Monitors", panelPayloads);
          
          panelTX.setLayout(new javax.swing.BoxLayout(panelTX, javax.swing.BoxLayout.X_AXIS));
              
              panelTX1.setLayout(new javax.swing.BoxLayout(panelTX1, javax.swing.BoxLayout.Y_AXIS));
              
              panelTX1.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
              jLabel16.setText("  TX1  ");
              jLabel16.setForeground(java.awt.Color.yellow);
              jLabel16.setBackground(java.awt.Color.blue);
              jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
              jLabel16.setFont(new java.awt.Font("Arial Black", 0, 14));
              jLabel16.setPreferredSize(new java.awt.Dimension(50, 17));
              jLabel16.setMinimumSize(new java.awt.Dimension(50, 17));
              jLabel16.setAlignmentX(0.5F);
              jLabel16.setMaximumSize(new java.awt.Dimension(1500, 21));
              jLabel16.setOpaque(true);
              panelTX1.add(jLabel16);
              
              jPanel17.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 2, 5));
                    
                    jPanel18.setBorder(new javax.swing.border.TitledBorder("RF Output"));
                    jPanel19.setLayout(new javax.swing.BoxLayout(jPanel19, javax.swing.BoxLayout.Y_AXIS));
                    
                    jPanel19.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                    jLabel14.setText("1");
                    jLabel14.setForeground(java.awt.Color.white);
                    jLabel14.setBackground(java.awt.Color.black);
                    jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                    jLabel14.setFont(new java.awt.Font("Dialog", 1, 11));
                    jLabel14.setPreferredSize(new java.awt.Dimension(40, 16));
                    jLabel14.setAlignmentX(0.5F);
                    jLabel14.setMaximumSize(new java.awt.Dimension(40, 16));
                    jLabel14.setOpaque(true);
                    jPanel19.add(jLabel14);
                    
                    prgrssTX1RFOut1.setOrientation(javax.swing.SwingConstants.VERTICAL);
                    prgrssTX1RFOut1.setMaximum(2047);
                    prgrssTX1RFOut1.setForeground(java.awt.Color.red);
                    prgrssTX1RFOut1.setPreferredSize(new java.awt.Dimension(40, 75));
                    prgrssTX1RFOut1.setMaximumSize(new java.awt.Dimension(40, 32767));
                    jPanel19.add(prgrssTX1RFOut1);
                    
                    txtTX1RFOut1.setPreferredSize(new java.awt.Dimension(40, 20));
                    jPanel19.add(txtTX1RFOut1);
                    
                    jPanel18.add(jPanel19);
                  
                  jPanel16.setLayout(new javax.swing.BoxLayout(jPanel16, javax.swing.BoxLayout.Y_AXIS));
                    
                    jPanel16.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                    jLabel15.setText("2");
                    jLabel15.setForeground(java.awt.Color.white);
                    jLabel15.setBackground(java.awt.Color.black);
                    jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                    jLabel15.setFont(new java.awt.Font("Dialog", 1, 11));
                    jLabel15.setPreferredSize(new java.awt.Dimension(40, 16));
                    jLabel15.setAlignmentX(0.5F);
                    jLabel15.setMaximumSize(new java.awt.Dimension(40, 16));
                    jLabel15.setOpaque(true);
                    jPanel16.add(jLabel15);
                    
                    prgrssTX1RFOut2.setOrientation(javax.swing.SwingConstants.VERTICAL);
                    prgrssTX1RFOut2.setMaximum(2047);
                    prgrssTX1RFOut2.setForeground(java.awt.Color.red);
                    prgrssTX1RFOut2.setPreferredSize(new java.awt.Dimension(40, 75));
                    prgrssTX1RFOut2.setMaximumSize(new java.awt.Dimension(40, 32767));
                    jPanel16.add(prgrssTX1RFOut2);
                    
                    txtTX1RFOut2.setPreferredSize(new java.awt.Dimension(40, 20));
                    jPanel16.add(txtTX1RFOut2);
                    
                    jPanel18.add(jPanel16);
                  
                  jPanel17.add(jPanel18);
                
                jPanel20.setBorder(new javax.swing.border.TitledBorder(new javax.swing.border.EtchedBorder(), "5V Test"));
                    jPanel21.setLayout(new javax.swing.BoxLayout(jPanel21, javax.swing.BoxLayout.Y_AXIS));
                    
                    jPanel21.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                    jLabel17.setText("5V");
                    jLabel17.setForeground(java.awt.Color.white);
                    jLabel17.setBackground(java.awt.Color.black);
                    jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                    jLabel17.setFont(new java.awt.Font("Dialog", 1, 11));
                    jLabel17.setPreferredSize(new java.awt.Dimension(40, 16));
                    jLabel17.setAlignmentX(0.5F);
                    jLabel17.setMaximumSize(new java.awt.Dimension(40, 16));
                    jLabel17.setOpaque(true);
                    jPanel21.add(jLabel17);
                    
                    prgrssTX1_5V.setOrientation(javax.swing.SwingConstants.VERTICAL);
                    prgrssTX1_5V.setMaximum(2047);
                    prgrssTX1_5V.setForeground(java.awt.Color.orange);
                    prgrssTX1_5V.setPreferredSize(new java.awt.Dimension(40, 75));
                    prgrssTX1_5V.setMaximumSize(new java.awt.Dimension(40, 32767));
                    jPanel21.add(prgrssTX1_5V);
                    
                    txtTX1_5V.setPreferredSize(new java.awt.Dimension(40, 20));
                    jPanel21.add(txtTX1_5V);
                    
                    jPanel20.add(jPanel21);
                  
                  jPanel17.add(jPanel20);
                
                jPanel22.setBorder(new javax.swing.border.TitledBorder(new javax.swing.border.EtchedBorder(), "Temp"));
                    jPanel23.setLayout(new javax.swing.BoxLayout(jPanel23, javax.swing.BoxLayout.Y_AXIS));
                    
                    jPanel23.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                    jLabel18.setText("Temp");
                    jLabel18.setForeground(java.awt.Color.white);
                    jLabel18.setBackground(java.awt.Color.black);
                    jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                    jLabel18.setFont(new java.awt.Font("Dialog", 1, 11));
                    jLabel18.setPreferredSize(new java.awt.Dimension(40, 16));
                    jLabel18.setAlignmentX(0.5F);
                    jLabel18.setMaximumSize(new java.awt.Dimension(40, 16));
                    jLabel18.setOpaque(true);
                    jPanel23.add(jLabel18);
                    
                    prgrssTX1Temp.setOrientation(javax.swing.SwingConstants.VERTICAL);
                    prgrssTX1Temp.setMaximum(2047);
                    prgrssTX1Temp.setForeground(java.awt.Color.red);
                    prgrssTX1Temp.setPreferredSize(new java.awt.Dimension(40, 75));
                    prgrssTX1Temp.setMaximumSize(new java.awt.Dimension(40, 32767));
                    jPanel23.add(prgrssTX1Temp);
                    
                    txtTX1Temp.setPreferredSize(new java.awt.Dimension(40, 20));
                    jPanel23.add(txtTX1Temp);
                    
                    jPanel22.add(jPanel23);
                  
                  jPanel17.add(jPanel22);
                
                jPanel24.setLayout(new javax.swing.BoxLayout(jPanel24, javax.swing.BoxLayout.Y_AXIS));
                  
                  jPanel24.setBorder(new javax.swing.border.TitledBorder("Misc."));
                  lblTX1PTT.setText("PTT");
                  lblTX1PTT.setForeground(java.awt.Color.gray);
                  lblTX1PTT.setBackground(new java.awt.Color(0, 51, 0));
                  lblTX1PTT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                  lblTX1PTT.setFont(new java.awt.Font("Dialog", 1, 11));
                  lblTX1PTT.setPreferredSize(new java.awt.Dimension(80, 40));
                  lblTX1PTT.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black, 1, true));
                  lblTX1PTT.setAlignmentX(0.5F);
                  lblTX1PTT.setMaximumSize(new java.awt.Dimension(100, 40));
                  lblTX1PTT.setOpaque(true);
                  jPanel24.add(lblTX1PTT);
                  
                  lblTX1PLLError.setText("PLL ERROR");
                  lblTX1PLLError.setForeground(java.awt.Color.gray);
                  lblTX1PLLError.setBackground(new java.awt.Color(102, 51, 0));
                  lblTX1PLLError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                  lblTX1PLLError.setFont(new java.awt.Font("Dialog", 1, 11));
                  lblTX1PLLError.setPreferredSize(new java.awt.Dimension(80, 40));
                  lblTX1PLLError.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black, 1, true));
                  lblTX1PLLError.setAlignmentX(0.5F);
                  lblTX1PLLError.setMaximumSize(new java.awt.Dimension(100, 40));
                  lblTX1PLLError.setOpaque(true);
                  jPanel24.add(lblTX1PLLError);
                  
                  jPanel17.add(jPanel24);
                
                panelTX1.add(jPanel17);
              
              panelTX.add(panelTX1);
            
            jPanel25.setLayout(new javax.swing.BoxLayout(jPanel25, javax.swing.BoxLayout.Y_AXIS));
              
              jPanel25.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
              jLabel19.setText("  TX2  ");
              jLabel19.setForeground(java.awt.Color.yellow);
              jLabel19.setBackground(java.awt.Color.blue);
              jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
              jLabel19.setFont(new java.awt.Font("Arial Black", 0, 14));
              jLabel19.setPreferredSize(new java.awt.Dimension(50, 17));
              jLabel19.setMinimumSize(new java.awt.Dimension(50, 17));
              jLabel19.setAlignmentX(0.5F);
              jLabel19.setMaximumSize(new java.awt.Dimension(1500, 21));
              jLabel19.setOpaque(true);
              jPanel25.add(jLabel19);
              
              jPanel26.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 2, 5));
                    
                    jPanel27.setBorder(new javax.swing.border.TitledBorder(new javax.swing.border.EtchedBorder(), "RF Output"));
                    jPanel28.setLayout(new javax.swing.BoxLayout(jPanel28, javax.swing.BoxLayout.Y_AXIS));
                    
                    jPanel28.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                    jLabel20.setText("1");
                    jLabel20.setForeground(java.awt.Color.white);
                    jLabel20.setBackground(java.awt.Color.black);
                    jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                    jLabel20.setFont(new java.awt.Font("Dialog", 1, 11));
                    jLabel20.setPreferredSize(new java.awt.Dimension(40, 16));
                    jLabel20.setAlignmentX(0.5F);
                    jLabel20.setMaximumSize(new java.awt.Dimension(40, 16));
                    jLabel20.setOpaque(true);
                    jPanel28.add(jLabel20);
                    
                    prgrssTX2RFOut1.setOrientation(javax.swing.SwingConstants.VERTICAL);
                    prgrssTX2RFOut1.setMaximum(2047);
                    prgrssTX2RFOut1.setForeground(java.awt.Color.red);
                    prgrssTX2RFOut1.setPreferredSize(new java.awt.Dimension(40, 75));
                    prgrssTX2RFOut1.setMaximumSize(new java.awt.Dimension(40, 32767));
                    jPanel28.add(prgrssTX2RFOut1);
                    
                    txtTX2RFOut1.setPreferredSize(new java.awt.Dimension(40, 20));
                    jPanel28.add(txtTX2RFOut1);
                    
                    jPanel27.add(jPanel28);
                  
                  jPanel29.setLayout(new javax.swing.BoxLayout(jPanel29, javax.swing.BoxLayout.Y_AXIS));
                    
                    jPanel29.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                    jLabel21.setText("2");
                    jLabel21.setForeground(java.awt.Color.white);
                    jLabel21.setBackground(java.awt.Color.black);
                    jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                    jLabel21.setFont(new java.awt.Font("Dialog", 1, 11));
                    jLabel21.setPreferredSize(new java.awt.Dimension(40, 16));
                    jLabel21.setAlignmentX(0.5F);
                    jLabel21.setMaximumSize(new java.awt.Dimension(40, 16));
                    jLabel21.setOpaque(true);
                    jPanel29.add(jLabel21);
                    
                    prgrssTX2RFOut2.setOrientation(javax.swing.SwingConstants.VERTICAL);
                    prgrssTX2RFOut2.setMaximum(2047);
                    prgrssTX2RFOut2.setForeground(java.awt.Color.red);
                    prgrssTX2RFOut2.setPreferredSize(new java.awt.Dimension(40, 75));
                    prgrssTX2RFOut2.setMaximumSize(new java.awt.Dimension(40, 32767));
                    jPanel29.add(prgrssTX2RFOut2);
                    
                    txtTX2RFOut2.setPreferredSize(new java.awt.Dimension(40, 20));
                    jPanel29.add(txtTX2RFOut2);
                    
                    jPanel27.add(jPanel29);
                  
                  jPanel26.add(jPanel27);
                
                jPanel30.setBorder(new javax.swing.border.TitledBorder(new javax.swing.border.EtchedBorder(), "5V Test"));
                    jPanel31.setLayout(new javax.swing.BoxLayout(jPanel31, javax.swing.BoxLayout.Y_AXIS));
                    
                    jPanel31.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                    jLabel22.setText("5V");
                    jLabel22.setForeground(java.awt.Color.white);
                    jLabel22.setBackground(java.awt.Color.black);
                    jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                    jLabel22.setFont(new java.awt.Font("Dialog", 1, 11));
                    jLabel22.setPreferredSize(new java.awt.Dimension(40, 16));
                    jLabel22.setAlignmentX(0.5F);
                    jLabel22.setMaximumSize(new java.awt.Dimension(40, 16));
                    jLabel22.setOpaque(true);
                    jPanel31.add(jLabel22);
                    
                    prgrssTX2_5V.setOrientation(javax.swing.SwingConstants.VERTICAL);
                    prgrssTX2_5V.setMaximum(2047);
                    prgrssTX2_5V.setForeground(java.awt.Color.orange);
                    prgrssTX2_5V.setPreferredSize(new java.awt.Dimension(40, 75));
                    prgrssTX2_5V.setMaximumSize(new java.awt.Dimension(40, 32767));
                    jPanel31.add(prgrssTX2_5V);
                    
                    txtTX2_5V.setPreferredSize(new java.awt.Dimension(40, 20));
                    jPanel31.add(txtTX2_5V);
                    
                    jPanel30.add(jPanel31);
                  
                  jPanel26.add(jPanel30);
                
                jPanel32.setBorder(new javax.swing.border.TitledBorder(new javax.swing.border.EtchedBorder(), "Temp"));
                    jPanel33.setLayout(new javax.swing.BoxLayout(jPanel33, javax.swing.BoxLayout.Y_AXIS));
                    
                    jPanel33.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
                    jLabel23.setText("Temp");
                    jLabel23.setForeground(java.awt.Color.white);
                    jLabel23.setBackground(java.awt.Color.black);
                    jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                    jLabel23.setFont(new java.awt.Font("Dialog", 1, 11));
                    jLabel23.setPreferredSize(new java.awt.Dimension(40, 16));
                    jLabel23.setAlignmentX(0.5F);
                    jLabel23.setMaximumSize(new java.awt.Dimension(40, 16));
                    jLabel23.setOpaque(true);
                    jPanel33.add(jLabel23);
                    
                    prgrssTX2Temp.setOrientation(javax.swing.SwingConstants.VERTICAL);
                    prgrssTX2Temp.setMaximum(2047);
                    prgrssTX2Temp.setForeground(java.awt.Color.red);
                    prgrssTX2Temp.setPreferredSize(new java.awt.Dimension(40, 75));
                    prgrssTX2Temp.setMaximumSize(new java.awt.Dimension(40, 32767));
                    jPanel33.add(prgrssTX2Temp);
                    
                    txtTX2Temp.setPreferredSize(new java.awt.Dimension(40, 20));
                    jPanel33.add(txtTX2Temp);
                    
                    jPanel32.add(jPanel33);
                  
                  jPanel26.add(jPanel32);
                
                jPanel34.setLayout(new javax.swing.BoxLayout(jPanel34, javax.swing.BoxLayout.Y_AXIS));
                  
                  jPanel34.setBorder(new javax.swing.border.TitledBorder(new javax.swing.border.EtchedBorder(), "Misc."));
                  lblTX2PTT.setText("PTT");
                  lblTX2PTT.setForeground(java.awt.Color.gray);
                  lblTX2PTT.setBackground(new java.awt.Color(0, 51, 0));
                  lblTX2PTT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                  lblTX2PTT.setFont(new java.awt.Font("Dialog", 1, 11));
                  lblTX2PTT.setPreferredSize(new java.awt.Dimension(80, 40));
                  lblTX2PTT.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black, 1, true));
                  lblTX2PTT.setAlignmentX(0.5F);
                  lblTX2PTT.setMaximumSize(new java.awt.Dimension(100, 40));
                  lblTX2PTT.setOpaque(true);
                  jPanel34.add(lblTX2PTT);
                  
                  lblTX2PLLError.setText("PLL ERROR");
                  lblTX2PLLError.setForeground(java.awt.Color.gray);
                  lblTX2PLLError.setBackground(new java.awt.Color(102, 51, 0));
                  lblTX2PLLError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                  lblTX2PLLError.setFont(new java.awt.Font("Dialog", 1, 11));
                  lblTX2PLLError.setPreferredSize(new java.awt.Dimension(80, 40));
                  lblTX2PLLError.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black, 1, true));
                  lblTX2PLLError.setAlignmentX(0.5F);
                  lblTX2PLLError.setMaximumSize(new java.awt.Dimension(100, 40));
                  lblTX2PLLError.setOpaque(true);
                  jPanel34.add(lblTX2PLLError);
                  
                  jPanel26.add(jPanel34);
                
                jPanel25.add(jPanel26);
              
              panelTX.add(jPanel25);
            
            jTabbedPane1.addTab("Transmitters", panelTX);
          
          jPanel36.setBorder(new javax.swing.border.LineBorder(java.awt.Color.black));
              jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ca/gc/space/quicksat/ground/images/Graph.jpg")));
              jButton1.setBackground(java.awt.Color.white);
              jPanel36.add(jButton1);
              
              jPanel35.add(jPanel36);
            
            jPanel37.setLayout(new javax.swing.BoxLayout(jPanel37, javax.swing.BoxLayout.Y_AXIS));
              
              jPanel37.setBorder(new javax.swing.border.TitledBorder("Data Items"));
              jCheckBox1.setText("Data Item 1");
              jPanel37.add(jCheckBox1);
              
              jCheckBox2.setText("Data Item 2");
              jPanel37.add(jCheckBox2);
              
              jCheckBox3.setText("Data Item 3");
              jPanel37.add(jCheckBox3);
              
              jCheckBox4.setText("Data Item 4");
              jPanel37.add(jCheckBox4);
              
              jButton2.setText("Save As...");
              jPanel37.add(jButton2);
              
              jPanel35.add(jPanel37);
            
            jTabbedPane1.addTab("Trend", jPanel35);
          
          add(jTabbedPane1);
        
    }//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel panelRawTelem;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable tblRawTelem;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panelPayloads;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JProgressBar prgrssPayload1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel jLabel3;
    public javax.swing.JProgressBar prgrssPayload2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JProgressBar prgrssPayload3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JProgressBar prgrssPayload4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JProgressBar prgrssPayload5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JProgressBar prgrssPayload6;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JProgressBar prgrssPayload7;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JProgressBar prgrssPayload8;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JLabel jLabel10;
    public javax.swing.JProgressBar prgrssPayload9;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JLabel jLabel11;
    public javax.swing.JProgressBar prgrssPayload10;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JLabel jLabel12;
    public javax.swing.JProgressBar prgrssPayload11;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JLabel jLabel13;
    public javax.swing.JProgressBar prgrssPayload12;
    private javax.swing.JPanel panelTX;
    private javax.swing.JPanel panelTX1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JLabel jLabel14;
    public javax.swing.JProgressBar prgrssTX1RFOut1;
    public javax.swing.JTextField txtTX1RFOut1;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JLabel jLabel15;
    public javax.swing.JProgressBar prgrssTX1RFOut2;
    public javax.swing.JTextField txtTX1RFOut2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JLabel jLabel17;
    public javax.swing.JProgressBar prgrssTX1_5V;
    public javax.swing.JTextField txtTX1_5V;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JLabel jLabel18;
    public javax.swing.JProgressBar prgrssTX1Temp;
    public javax.swing.JTextField txtTX1Temp;
    private javax.swing.JPanel jPanel24;
    public javax.swing.JLabel lblTX1PTT;
    public javax.swing.JLabel lblTX1PLLError;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JLabel jLabel20;
    public javax.swing.JProgressBar prgrssTX2RFOut1;
    public javax.swing.JTextField txtTX2RFOut1;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JLabel jLabel21;
    public javax.swing.JProgressBar prgrssTX2RFOut2;
    public javax.swing.JTextField txtTX2RFOut2;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JLabel jLabel22;
    public javax.swing.JProgressBar prgrssTX2_5V;
    public javax.swing.JTextField txtTX2_5V;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JLabel jLabel23;
    public javax.swing.JProgressBar prgrssTX2Temp;
    public javax.swing.JTextField txtTX2Temp;
    private javax.swing.JPanel jPanel34;
    public javax.swing.JLabel lblTX2PTT;
    public javax.swing.JLabel lblTX2PLLError;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables

}
